const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const quizQuestions = [
  // Lesson 60-69 - Project quizzes
  // Lesson 60 - Todo App
  {lessonId:60,question:"What data structure best represents a list of todos with ordering?",options:["A Set","An ordered array with id, text, done, createdAt fields","A Map","A linked list"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:60,question:"How do you persist todo state across page refreshes?",options:["React state only","localStorage or a database backend","sessionStorage only","Cookie only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:60,question:"What is the best way to filter todos (all/active/completed)?",options:["Keep three separate arrays","Derive filtered list from a single source array based on filter state","Delete completed todos","Use separate API calls"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:60,question:"How should you handle optimistic deletion in a todo app?",options:["Only delete after server confirms","Remove from UI immediately, restore if API fails","Show loading spinner","Disable UI during delete"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:60,question:"What keyboard shortcut should be supported for accessibility in a todo app?",options:["Only mouse clicks","Enter to add, Escape to cancel edit, Delete/Backspace for deletion","Only tab navigation","No keyboard shortcuts needed"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:60,question:"How do you implement drag-and-drop reordering in a todo list?",options:["Use HTML drag events only","Use a library like dnd-kit or react-beautiful-dnd; update order IDs in state","Not possible in React","Only with jQuery"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:60,question:"What ARIA attributes improve todo list accessibility?",options:["None needed","role='list' on ul, role='listitem' on li, aria-label on buttons, aria-checked on checkboxes","Only alt text","Only tab index"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:60,question:"How should you handle the empty state when no todos exist?",options:["Show nothing","Show a friendly message and call-to-action to add the first todo","Show an error","Hide the input"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:60,question:"What is the best database schema for a todo app with categories?",options:["One todos table","Users, Todos (with userId FK), Categories (with userId FK), todo_categories junction","Flat JSON file","Single JSON column"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:60,question:"How do you implement 'mark all complete' efficiently?",options:["Loop and update each one","Single API call: PATCH /todos/bulk with {done: true} or DB: UPDATE todos SET done=true","Not possible","Use setTimeout loop"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 61 - Kanban Board
  {lessonId:61,question:"What data model represents a Kanban board with columns and cards?",options:["A flat array","Board has Columns; each Column has Cards; cards have columnId FK","A tree","A matrix"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:61,question:"What library is commonly used for drag-and-drop in Kanban boards?",options:["jQuery UI","dnd-kit, react-beautiful-dnd, or Sortable.js","HTML5 drag events only","No library needed"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:61,question:"How do you track card order within a column?",options:["Array position only","Order/position field on each card that gets updated when cards are moved","By ID","Alphabetically"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:61,question:"What is an optimistic update strategy for moving a card between columns?",options:["Lock UI until server responds","Update local state immediately, send API request, rollback on failure","Show loading on card","Only server-confirmed moves"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:61,question:"What is the challenge with reordering cards and how do you solve the 'order' field problem?",options:["No challenge","Integer ordering causes conflicts; use float or fractional indexing (LexoRank) for sparse ordering","Use timestamps","Sort alphabetically"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:61,question:"How do you implement real-time collaboration in a Kanban board?",options:["Polling every second","WebSockets to push card moves to all connected clients; handle conflicts with last-write-wins","Not possible in browser","Email notifications"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:61,question:"What is a WIP (Work In Progress) limit in Kanban?",options:["A bug tracking limit","Maximum number of cards allowed in a column at one time to prevent bottlenecks","A sprint limit","A user limit"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:61,question:"How should card colors or labels be implemented?",options:["Hardcode colors","Store label as a string key; map to color/text in a labels config object; support custom labels","CSS classes only","Not needed"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:61,question:"What UX pattern indicates a valid drop zone during drag?",options:["No indicator needed","Visual highlight (border, shadow, background color change) on valid drop targets","Cursor change only","Alert message"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:61,question:"How do you implement card filtering by assignee or label in a Kanban board?",options:["Delete unmatched cards","Derive visible cards from all cards by applying filter predicates; store filter state in URL","Server-side only","Separate board per filter"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 62 - E-commerce Cart
  {lessonId:62,question:"Where should cart state be stored in a React e-commerce app?",options:["Local component state only","Context + useReducer or Zustand for global cart; localStorage for persistence","Redux required","Server only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:62,question:"How do you calculate cart total with discounts?",options:["Manual addition","subtotal = sum(item.price * item.qty), discount = applyCode(subtotal), total = subtotal - discount + tax + shipping","Round all values","Use float arithmetic directly"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:62,question:"What is the optimistic update challenge when adding items to a cart?",options:["No challenge","If adding requires server auth check (stock, user), optimistic add may need rollback on failure","Always pessimistic","Not applicable"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:62,question:"How should you handle floating point arithmetic for prices?",options:["Use Math.round()","Store prices as integers (cents), convert to dollars for display: 999 = $9.99","Use toFixed(2)","Prices are always exact"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:62,question:"What data should persist in the cart if the user leaves and comes back?",options:["Nothing","Cart items (id, qty, price at add time), applied coupon code, and shipping address","Only item IDs","Only total"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:62,question:"How do you implement a 'you may also like' recommendation section?",options:["Random items","Based on current cart items, query related products by category, tags, or collaborative filtering","Only most popular","Static list"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:62,question:"What is the purpose of a cart merge strategy?",options:["No purpose","When a guest user logs in, their guest cart is merged with their account cart (quantity or latest wins)","Delete guest cart","Error message"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:62,question:"What payment integration steps occur during checkout?",options:["Direct card storage","Client: get payment intent from server, collect card via Stripe Elements, confirm payment; server: fulfill on webhook","Only PayPal","Bank transfer only"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:62,question:"How should out-of-stock items be handled in the cart?",options:["Remove silently","Mark item as out of stock, show message, disable checkout, offer alternatives","Error 500","Ignore stock"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:62,question:"What is a mini-cart and when should it appear?",options:["A small app","A dropdown/drawer showing cart summary, triggered by adding item or hovering cart icon; no page navigation","A modal always","Only on cart page"],correctAnswer:1,difficulty:"Easy"},

  // Lesson 63 - Chat Application UI
  {lessonId:63,question:"What technology powers real-time message delivery in chat apps?",options:["HTTP polling only","WebSockets (Socket.io or native) for persistent bidirectional connection","Long polling","Server-Sent Events only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:63,question:"How do you handle message ordering in a chat app?",options:["By insertion order","Assign timestamp on server, sort by timestamp; use sequence numbers for tie-breaking","Client timestamps","Alphabetically"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:63,question:"What is the optimistic UI pattern for sent messages?",options:["Show after server confirms","Show message immediately with 'sending' status; update to 'sent' on confirmation; remove on failure","Show loading spinner","Never optimistic for messages"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:63,question:"How do you implement 'typing indicators' (User is typing...)?",options:["Not possible","Client emits typing event on keypress; server broadcasts to room; clear after timeout","Polling","Only with WebRTC"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:63,question:"What is the challenge of rendering large message histories?",options:["No challenge","Performance: virtualize long lists, paginate (load more), implement virtual scroll for thousands of messages","Load all messages","Server-side render only"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:63,question:"How do you implement unread message count badges?",options:["Not needed","Track lastReadAt per user per conversation; badge = messages after lastReadAt; reset on conversation open","Count all messages","Server-only badge"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:63,question:"What is end-to-end encryption in chat and why is it important?",options:["Server encryption only","Messages encrypted client-side; server never sees plaintext; only sender/recipient can decrypt","Password protection","HTTPS only"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:63,question:"How should images/files be shared in a chat application?",options:["Base64 in messages","Upload to cloud storage (S3), store URL in message; stream directly to recipient for large files","Email attachments","Not supported"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:63,question:"What is message threading vs flat chat?",options:["No difference","Flat: all messages in sequence; threaded: messages can have replies creating subtrees","Threading is required","Flat is deprecated"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:63,question:"How do you implement read receipts (delivered/read indicators)?",options:["Not possible","Track message state: sent -> delivered (recipient connected) -> read (recipient viewed); emit events","Not important","Only for 1-1 chats"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 64 - Notes App
  {lessonId:64,question:"What rich text editor library is commonly used in React notes apps?",options:["textarea only","TipTap, Slate.js, Quill, or Draft.js for rich text editing with formatting","contentEditable directly","Monaco editor"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:64,question:"How do you implement auto-save in a notes application?",options:["Manual save only","Debounce onChange by 1-2 seconds; save when user stops typing; show saved indicator","Save on unmount","Timer every 30s"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:64,question:"What data format should note content be stored in?",options:["Plain text only","Rich text as JSON (TipTap/Slate format) or HTML; plain text for simple apps","Binary","XML"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:64,question:"How do you implement note search with rich text content?",options:["Can't search rich text","Extract plain text from rich text format for indexing; search the plain text; highlight matches in display","Full-text DB only","Not possible"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:64,question:"What is conflict resolution when a note is edited on multiple devices simultaneously?",options:["Last write wins always","CRDT-based merge (Yjs, Automerge), operational transforms, or simple last-write-wins with warning","Block second edit","Not a real problem"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:64,question:"How should note tags/labels be implemented?",options:["Categories only","Free-form tags stored as array; filter by tag; many-to-many relation in DB","Single category","No organization needed"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:64,question:"What is the difference between a note being archived vs deleted?",options:["Same thing","Archived: hidden from main view but accessible; Deleted: soft-deleted with 30-day restore window","Both remove permanently","Only delete exists"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:64,question:"How do you implement note version history?",options:["Not possible","Store each save as a version record; show diff between versions; allow restore","Git integration only","Database logs"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:64,question:"What is the purpose of note pinning?",options:["Nothing","Keep important notes at the top of the list regardless of sort order","A visual feature only","For shared notes"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:64,question:"How should offline note editing be handled?",options:["Block editing offline","Use service worker + IndexedDB to store notes offline; sync when back online; handle conflicts","Disable offline","Show error"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 65 - URL Shortener Frontend
  {lessonId:65,question:"How do you generate a short code for a URL?",options:["MD5 of URL","Random alphanumeric string (6-8 chars) or base62 encoding of auto-increment ID","URL encoding","Timestamp"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:65,question:"What happens when a user visits a short URL?",options:["Shows the short URL page","Server looks up the full URL, responds with 301/302 redirect to original URL","Downloads a file","Shows a preview"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:65,question:"What is the difference between 301 and 302 redirects for URL shortening?",options:["No difference","301 is permanent (browser caches it, analytics may be lost); 302 is temporary (browser always checks server, analytics captured)","301 is faster","302 is deprecated"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:65,question:"How do you track analytics for a short URL?",options:["No tracking","On each redirect, log: timestamp, IP, user-agent, referrer; aggregate in background","Browser-side only","Not possible"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:65,question:"How should you prevent abuse (spam URLs, malware) in a URL shortener?",options:["No prevention needed","Domain blacklist, rate limiting per IP, Google Safe Browsing API check, user authentication for bulk","Only premium users can use","CAPTCHA only"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:65,question:"What is a custom alias in URL shortening?",options:["A different domain","Allowing users to specify their own short code: mysite.com/my-brand instead of mysite.com/x7k2","Not possible","Premium feature only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:65,question:"How should expired URLs be handled?",options:["Return 200","Return 410 Gone (vs 404 Not Found) to indicate the URL existed but is now intentionally gone","Redirect to homepage","Delete immediately"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:65,question:"What frontend UX should be shown after creating a short URL?",options:["Nothing","Display short URL with copy button, QR code, basic analytics preview; allow sharing directly","Redirect to short URL","Form reset only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:65,question:"How do you scale a URL shortener to handle millions of redirects?",options:["More RAM","CDN at edge for redirects, Redis cache for URL lookups (sub-millisecond), DB for persistence","More servers only","Not possible"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:65,question:"What is a QR code and how is it generated for a short URL?",options:["A barcode","A 2D matrix barcode encoding the URL; generated client-side with qrcode.js or server-side","A logo","An image format"],correctAnswer:1,difficulty:"Easy"},

  // Lesson 66 - Analytics Dashboard
  {lessonId:66,question:"What is the difference between client-side and server-side analytics?",options:["No difference","Client-side: JavaScript tracks events in browser (blocked by ad blockers); Server-side: logged on server (accurate but limited)","Server is always better","Client is deprecated"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:66,question:"What charting library is commonly used in React dashboards?",options:["D3 only","Recharts, Chart.js (via react-chartjs-2), Nivo, or Visx for React-friendly charts","Canvas only","SVG only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:66,question:"What is a time series chart and when is it used?",options:["A type of pie chart","A line/area chart with time on X-axis showing metric changes over time; used for pageviews, revenue trends","Bar chart with dates","Not a real chart type"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:66,question:"How do you handle real-time metrics updates in a dashboard?",options:["Manual refresh","WebSocket or SSE for live data, or polling every 30s; optimistically add new data points to chart","Not possible","Full page reload"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:66,question:"What is data aggregation and why is it needed for dashboards?",options:["Data backup","Summarizing raw events into computed metrics (hourly/daily/weekly totals) to enable fast queries on large data","Data export","A charting technique"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:66,question:"How do you implement date range filtering in an analytics dashboard?",options:["Hardcode ranges","Provide preset ranges (today, 7d, 30d) and custom date picker; pass range as API params","Not needed","Monthly only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:66,question:"What is a funnel chart and what does it represent?",options:["A cone shape","Conversion steps from start to end (e.g., visits -> signup -> purchase); shows drop-off at each stage","A pie chart variant","Not a real chart"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:66,question:"How should you design the dashboard layout for multiple metrics?",options:["Random placement","Grid of KPI cards at top, then charts below; responsive grid (CSS Grid); allow user customization","All in one chart","List format only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:66,question:"What is a heatmap chart and what data does it visualize?",options:["Temperature data","2D grid showing density/intensity; used for day-of-week by hour traffic patterns, geographic maps","A bar chart","An error map"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:66,question:"How do you export dashboard data in React?",options:["Not possible","Client-side CSV with PapaParse, PDF with jsPDF or react-pdf, chart image with Canvas.toDataURL","Server only","Email only"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 67 - File Explorer Tree
  {lessonId:67,question:"What data structure represents a file system tree?",options:["A flat array","A recursive tree: nodes with name, type (file/folder), and children array for folders","A linked list","A matrix"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:67,question:"How do you efficiently render a large directory tree with 10,000+ nodes?",options:["Render all nodes","Virtualize with react-window; lazy-load children on expand; only render visible nodes","Server-side render","Not possible"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:67,question:"What is tree traversal and how do you implement breadth-first search?",options:["Random order","BFS: use a queue; dequeue node, process, enqueue its children; visits level by level","Recursion always","Alphabetical order"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:67,question:"How do you implement file selection with multi-select support?",options:["Single select only","Track selected set; Ctrl+click adds/removes; Shift+click selects range; Command+A selects all","Radio buttons","Checkboxes only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:67,question:"What is expand/collapse state management for a tree component?",options:["Server-managed","Track expandedIds Set in state; toggle on click; persist to localStorage for UX","CSS only","No state needed"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:67,question:"How do you implement drag-and-drop file moving in a file explorer?",options:["Not possible","Drag source node; drop target validates (can't drop parent into child); update parent_id on drop; optimistic","Only for desktop apps","Copy always"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:67,question:"What is breadcrumb navigation in a file explorer?",options:["A decorative element","Path display showing hierarchy: Root > Documents > Projects; each segment is clickable to navigate up","URL display only","Not needed"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:67,question:"How do you implement file search in a tree structure?",options:["DFS through all nodes","Recursive DFS to find matching nodes; show matches with their full path; filter tree to show only matching paths","Server only","Not possible"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:67,question:"How do you handle file icons for different file types?",options:["One icon for all","Map file extension to icon: .pdf -> pdf icon, .jpg -> image icon, .js -> js icon; fallback generic file","Text labels","Color coding only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:67,question:"What keyboard navigation should a file explorer support?",options:["None","Arrow keys to navigate, Enter to open/expand, Space to select, F2 to rename, Delete to delete","Tab only","Mouse required"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 68 - Pagination System
  {lessonId:68,question:"What are the two main approaches to pagination?",options:["Client and server","Offset/limit (simple, slower at scale) and cursor-based (scalable, stable under inserts)","Page numbers and infinite scroll","Ajax and non-Ajax"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:68,question:"What is the main performance problem with offset pagination on large tables?",options:["No problem","OFFSET N requires the database to count and skip N rows every query - O(N) cost that grows with page number","Index not used","Too many columns"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:68,question:"How does infinite scroll work technically?",options:["Loads all data upfront","IntersectionObserver on sentinel element at bottom of list; fires loadMore when sentinel enters viewport","JavaScript scroll event","Timer-based loading"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:68,question:"What is 'load more' button pagination and when is it preferred over infinite scroll?",options:["Same as infinite scroll","User explicitly clicks to load more; preferred for content that needs to be scannable (articles vs social feed)","Deprecated pattern","Not a real pattern"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:68,question:"How should page state be preserved in the URL?",options:["Session storage","Query params: ?page=2&limit=10; allows bookmarking, sharing, browser back button to return to same page","localStorage","Not needed"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:68,question:"What is a page size selector and what are typical values?",options:["Not needed","UI to choose items per page (10, 25, 50, 100); default 20-25 for good UX; cap at 100 to prevent abuse","Unlimited option","Only developer option"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:68,question:"How do you implement keyboard navigation in pagination controls?",options:["No keyboard support","Left/right arrows for prev/next; number keys for page; Home/End for first/last; Enter on focused page button","Not needed","Mouse required"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:68,question:"What is the correct ARIA pattern for a pagination component?",options:["No ARIA needed","nav element with aria-label='Pagination'; aria-current='page' on active page; meaningful aria-labels on prev/next","role='list' only","tabindex only"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:68,question:"How do you show pagination range text like '21-30 of 150'?",options:["Not standard","Calculate: start=(page-1)*limit+1, end=min(page*limit,total); display: 'start-end of total'","Server provides it only","Estimated only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:68,question:"What happens to pagination when items are deleted from the list?",options:["No issue","Current page may become empty (goto prev page) or show shifted items; cursor pagination handles this better than offset","Error always","Reload page"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 69 - Typeahead / Search
  {lessonId:69,question:"What is debouncing in a search input and why is it needed?",options:["Making search slow","Delaying the search API call until the user stops typing for N ms; prevents a request on every keystroke","A caching technique","An animation"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:69,question:"How do you handle race conditions in typeahead search?",options:["No race conditions","Abort previous request with AbortController when new query starts; or use a requestId and only apply latest response","Use setTimeout","Server handles it"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:69,question:"What ARIA attributes make a combobox/typeahead accessible?",options:["None needed","role='combobox' on input, aria-expanded, aria-autocomplete, role='listbox' on dropdown, role='option' on items","aria-label only","tabindex only"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:69,question:"How do you implement keyboard navigation in typeahead results?",options:["No keyboard support","Arrow keys move through options; Enter selects; Escape closes; Tab moves focus out; index tracked in state","Tab only","Not needed"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:69,question:"What is result highlighting in typeahead?",options:["Color the entire result","Bold/underline the part of the result that matches the search query; helps user understand why result appeared","Not needed","Server highlights"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:69,question:"How do you cache typeahead results to avoid repeated API calls?",options:["No caching","Memoize results by query string in a Map; cache for short TTL (30s); return cached results instantly","Browser cache only","Redis only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:69,question:"What is a minimum character threshold for triggering search?",options:["Always search","Require 2-3 characters before searching; prevents high-volume queries on 'a', 'b' etc; show placeholder text before threshold","1 character minimum","No threshold"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:69,question:"How do you implement recent searches?",options:["Not possible","Store last N searches in localStorage; show them when input is focused and empty; allow clearing","Server only","Session only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:69,question:"What is server-side vs client-side search filtering?",options:["Same result","Server: full dataset, handles large data, index-optimized; Client: already-loaded data only, instant, limited dataset","Client is always better","Server only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:69,question:"What is a fuzzy search and how is it different from exact match?",options:["A slow search","Fuzzy: matches approximate strings (typos tolerated) using algorithms like Levenshtein distance; Exact: only perfect matches","A search type","Case insensitive only"],correctAnswer:1,difficulty:"Medium"}
];

const codingQuestions = [
  // Lesson 43 - Node.js Internals coding (10 questions)
  {lessonId:43,difficulty:"Easy",title:"Event Loop Order Demo",problemStatement:"Write a script demonstrating Node.js event loop phase order: process.nextTick, Promise, setTimeout(0), setImmediate. Show execution order.",examples:"Execute all four and log execution order. Expected: nextTick -> Promise -> setTimeout(0) -> setImmediate",starterCodeJs:"console.log('1: Script start');\nsetTimeout(() => console.log('5: setTimeout(0)'), 0);\nsetImmediate(() => console.log('6: setImmediate'));\nPromise.resolve().then(() => console.log('3: Promise'));\nprocess.nextTick(() => console.log('2: nextTick'));\nprocess.nextTick(() => {\n  console.log('2b: nextTick 2');\n  Promise.resolve().then(() => console.log('3b: Promise inside nextTick'));\n});\nconsole.log('1b: Script end');\n// Output order:\n// 1: Script start\n// 1b: Script end\n// 2: nextTick\n// 2b: nextTick 2\n// 3: Promise\n// 3b: Promise inside nextTick\n// 5: setTimeout(0)\n// 6: setImmediate",hints:"nextTick queue drains before any I/O or timer callbacks. Promise microtasks run after nextTick. setTimeout(0) and setImmediate order depends on when they're called.",solutionExplanation:"Event loop phases: 1) call stack, 2) nextTick queue, 3) microtasks (promises), 4) timers phase (setTimeout), 5) check phase (setImmediate)."},
  {lessonId:43,difficulty:"Medium",title:"Thread Pool Demonstration",problemStatement:"Demonstrate Node.js thread pool: run multiple crypto operations and show they execute in parallel (not sequentially). Measure performance.",examples:"4 crypto.pbkdf2 calls finish at nearly the same time (parallel) vs sequential.",starterCodeJs:"const crypto = require('crypto');\nconst { Worker, isMainThread, workerData, parentPort } = require('worker_threads');\n// Thread pool demonstration via crypto (uses libuv thread pool)\nfunction hashPassword(password) {\n  return new Promise((resolve, reject) => {\n    const start = Date.now();\n    crypto.pbkdf2(password, 'salt', 100000, 64, 'sha512', (err, key) => {\n      if (err) reject(err);\n      else resolve({ key: key.toString('hex').slice(0,8), ms: Date.now()-start });\n    });\n  });\n}\nconst start = Date.now();\nPromise.all([\n  hashPassword('password1'),\n  hashPassword('password2'),\n  hashPassword('password3'),\n  hashPassword('password4')\n]).then(results => {\n  console.log('Total time:', Date.now()-start, 'ms');\n  console.log('Each hash:', results.map(r=>r.ms+'ms').join(', '));\n  console.log('If sequential would be ~4x each hash time. Parallel = ~1x.');\n});",hints:"crypto.pbkdf2 uses libuv thread pool (default 4 threads). All 4 run concurrently. Compare total time vs one hash time.",solutionExplanation:"libuv thread pool: synchronous CPU work runs in pool threads, not the event loop. Default 4 threads (UV_THREADPOOL_SIZE). Promise.all shows true parallelism."},
  {lessonId:43,difficulty:"Medium",title:"Non-Blocking I/O Example",problemStatement:"Demonstrate the difference between blocking and non-blocking I/O in Node.js. Show how blocking I/O stops the event loop.",examples:"readFileSync blocks: server can't handle requests. readFile async: server stays responsive.",starterCodeJs:"const fs = require('fs');\nconst http = require('http');\n// BLOCKING (bad for server)\nhttp.createServer((req, res) => {\n  if (req.url === '/blocking') {\n    const data = fs.readFileSync('/dev/urandom').slice(0, 1000000).toString('hex'); // BLOCKS event loop\n    res.end('Done');\n  }\n}).listen(3001);\n// NON-BLOCKING (correct)\nhttp.createServer((req, res) => {\n  if (req.url === '/non-blocking') {\n    fs.readFile('/path/to/file', (err, data) => {\n      res.end(err ? 'Error' : 'Done');\n    });\n    // Event loop continues handling other requests while reading\n  }\n}).listen(3002);\n// Demonstration: block the event loop\nfunction blockEventLoop(ms) {\n  const end = Date.now() + ms;\n  while (Date.now() < end); // busy wait - blocks event loop\n  console.log('Unblocked after', ms, 'ms');\n}\nconsole.log('Starting block...');\nsetTimeout(() => console.log('This should run at 0ms but was delayed by block'), 0);\nblockEventLoop(1000);\nconsole.log('Block complete. setTimeout will now run.');",hints:"Blocking: while loop or fs.readFileSync stops event loop. All requests queue behind it. Async I/O: kernel handles I/O, callback fires when done.",solutionExplanation:"Event loop is single-threaded. Blocking code prevents it from processing other events. Non-blocking I/O: kernel does I/O, callback queued when done."},
  {lessonId:43,difficulty:"Hard",title:"Cluster Module Load Balancing",problemStatement:"Build an HTTP server that uses cluster to spawn workers. Show load distribution across workers. Handle worker crashes with restart.",examples:"Server shows which worker PID handled each request. Workers restart automatically on crash.",starterCodeJs:"const cluster = require('cluster');\nconst http = require('http');\nconst numCPUs = require('os').cpus().length;\nif (cluster.isPrimary) {\n  console.log(`Primary ${process.pid} forking ${numCPUs} workers`);\n  const workers = {};\n  const spawnWorker = () => {\n    const w = cluster.fork();\n    workers[w.id] = w;\n    w.on('message', msg => console.log(`Worker ${w.process.pid}:`, msg));\n    return w;\n  };\n  for (let i=0; i<numCPUs; i++) spawnWorker();\n  cluster.on('exit', (worker, code, signal) => {\n    console.log(`Worker ${worker.process.pid} died (${signal||code})`);\n    delete workers[worker.id];\n    if (!worker.exitedAfterDisconnect) spawnWorker(); // respawn crashed workers\n  });\n  // Graceful shutdown\n  process.on('SIGTERM', () => Object.values(workers).forEach(w => { w.exitedAfterDisconnect = true; w.disconnect(); }));\n} else {\n  http.createServer((req, res) => {\n    process.send({ pid: process.pid, url: req.url }); // IPC to master\n    // Simulate occasional crash for demo\n    if (Math.random() < 0.001) process.exit(1);\n    res.end(`Worker ${process.pid}\\n`);\n  }).listen(3000);\n  console.log(`Worker ${process.pid} started`);\n}",hints:"isPrimary check separates master/worker code. exitedAfterDisconnect distinguishes graceful vs crash exit. IPC via process.send/worker.on('message').",solutionExplanation:"Cluster: master forks workers, OS distributes connections (round-robin). exitedAfterDisconnect false = crash = respawn. IPC for coordination."},
  {lessonId:43,difficulty:"Medium",title:"Custom Module System",problemStatement:"Implement a simplified version of Node's require() that reads files, caches modules, and handles circular dependencies.",examples:"myRequire('./module') reads file, wraps in function, executes, returns exports. Cached on second call.",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nconst moduleCache = {};\nfunction myRequire(modulePath) {\n  const fullPath = path.resolve(modulePath + (modulePath.endsWith('.js') ? '' : '.js'));\n  // Cache check\n  if (moduleCache[fullPath]) {\n    if (moduleCache[fullPath]._loading) return moduleCache[fullPath].exports; // circular dep: return partial exports\n    return moduleCache[fullPath].exports;\n  }\n  // Create module object\n  const mod = { id: fullPath, filename: fullPath, exports: {}, _loading: true };\n  moduleCache[fullPath] = mod;\n  // Read and execute module\n  const code = fs.readFileSync(fullPath, 'utf8');\n  const wrapper = `(function(module, exports, require, __filename, __dirname) { ${code} \\n})`;\n  const fn = eval(wrapper);\n  fn(mod, mod.exports, (dep) => myRequire(path.resolve(path.dirname(fullPath), dep)), fullPath, path.dirname(fullPath));\n  mod._loading = false;\n  return mod.exports;\n}",hints:"Wrap module code in a function to give it module, exports, require scope. Cache before executing to handle circular deps. _loading flag for circular dep detection.",solutionExplanation:"Node require: wrap code in function, inject module/exports/require. Cache module BEFORE executing it (enables circular deps to get partial exports)."},
  {lessonId:43,difficulty:"Easy",title:"Timer Internals Demo",problemStatement:"Demonstrate how Node.js timers work with the event loop. Show setTimeout vs setImmediate vs process.nextTick in I/O context.",examples:"Inside fs.readFile callback: setImmediate fires before setTimeout(0). Outside I/O: order unpredictable.",starterCodeJs:"const fs = require('fs');\n// Inside I/O callback: setImmediate ALWAYS before setTimeout(0)\nfs.readFile(__filename, () => {\n  console.log('Inside I/O callback:');\n  setTimeout(() => console.log('  setTimeout(0) - runs in timers phase (AFTER check)'), 0);\n  setImmediate(() => console.log('  setImmediate - runs in check phase (BEFORE timers next round)'));\n});\n// Outside I/O: order depends on how long setTimeout prep takes\nconsole.log('Outside I/O (order may vary):');\nsetTimeout(() => console.log('  setTimeout(0)'), 0);\nsetImmediate(() => console.log('  setImmediate'));\n// nextTick is NOT part of event loop - runs before any I/O\nprocess.nextTick(() => console.log('nextTick: runs before any event loop phase'));\n// Timer accuracy\nconsole.log('Timer minimum:', 1, 'ms (Node.js clamps setTimeout(0) to 1ms)');\nsetTimeout(() => console.log('Delayed 1ms'), 1);",hints:"Inside I/O: check phase (setImmediate) comes before next timers phase. Outside: race condition based on OS timer resolution. nextTick: before all I/O.",solutionExplanation:"Event loop phases: timers -> pending callbacks -> idle -> poll -> check(setImmediate) -> close. Inside I/O callback: poll phase just ran, next is check phase."},
  {lessonId:43,difficulty:"Hard",title:"Memory Profiling Script",problemStatement:"Write a script that deliberately creates a memory leak, then demonstrates how to detect it using heapStatistics and snapshots.",examples:"A closure that captures an ever-growing array. process.memoryUsage() shows heap growing over time.",starterCodeJs:"const v8 = require('v8');\n// Memory leak: growing array held by closure in setInterval\nlet leakyArray = [];\nlet leakInterval;\nfunction startLeak() {\n  leakInterval = setInterval(() => {\n    leakyArray.push(new Array(1000).fill('leak'));\n  }, 10);\n}\nfunction stopLeak() { clearInterval(leakInterval); leakyArray = []; }\n// Monitor heap growth\nfunction monitorMemory(durationMs=5000) {\n  const samples = [];\n  startLeak();\n  const monitor = setInterval(() => {\n    const stats = v8.getHeapStatistics();\n    const mem = process.memoryUsage();\n    samples.push({ heap: (mem.heapUsed/1024/1024).toFixed(1), time: Date.now() });\n    console.log(`Heap: ${(mem.heapUsed/1024/1024).toFixed(1)}MB`);\n  }, 500);\n  setTimeout(() => {\n    clearInterval(monitor);\n    stopLeak();\n    const first = parseFloat(samples[0]?.heap||0);\n    const last = parseFloat(samples[samples.length-1]?.heap||0);\n    console.log(`Growth: ${(last-first).toFixed(1)}MB over ${durationMs/1000}s`);\n    console.log(samples.length > 5 && last > first + 5 ? 'LEAK DETECTED' : 'No significant leak');\n  }, durationMs);\n}\nmonitorMemory();",hints:"v8.getHeapStatistics() provides detailed heap info. Growing heap across samples indicates leak. clearInterval + nullify the array to stop and verify fix.",solutionExplanation:"Memory leak: reference prevents GC. Growing heap = unreachable objects accumulating. Fix: ensure references are released. Null arrays, clear timers, remove listeners."},
  {lessonId:43,difficulty:"Medium",title:"Libuv Thread Pool Sizing",problemStatement:"Demonstrate UV_THREADPOOL_SIZE effect. Run 8 file system operations with default pool size (4) vs expanded pool size (8).",examples:"Default 4 workers: 8 ops take ~2x as long as with 8 workers. Show timing difference.",starterCodeJs:"const { execSync } = require('child_process');\nconst crypto = require('crypto');\nfunction runWithPoolSize(size, count) {\n  process.env.UV_THREADPOOL_SIZE = String(size);\n  const start = Date.now();\n  return Promise.all(\n    Array.from({length:count}, (_, i) => new Promise((res, rej) => {\n      crypto.pbkdf2(`password${i}`, 'salt', 50000, 64, 'sha512', (err, key) => err ? rej(err) : res(key));\n    }))\n  ).then(() => Date.now() - start);\n}\nasync function demo() {\n  const count = 8;\n  console.log(`Running ${count} crypto ops...`);\n  // Note: UV_THREADPOOL_SIZE must be set BEFORE first libuv I/O\n  // This is for demonstration - changing after startup may not take effect\n  const result4 = await runWithPoolSize(4, count);\n  console.log(`Pool size 4: ${result4}ms`);\n  const result8 = await runWithPoolSize(8, count);\n  console.log(`Pool size 8: ${result8}ms`);\n  console.log(`Speedup: ${(result4/result8).toFixed(1)}x`);\n}",hints:"UV_THREADPOOL_SIZE must be set before any I/O. Default is 4. For CPU-heavy apps, increase to CPU count. Max is 1024.",solutionExplanation:"Thread pool bottleneck: with 4 threads, 8 concurrent ops queue. 4 run, then next 4 run. Doubling threads halves time for CPU-bound parallel work."},
  {lessonId:43,difficulty:"Easy",title:"Blocking vs Non-Blocking Comparison",problemStatement:"Write a benchmark that compares blocking readFileSync vs non-blocking readFile for reading 100 files. Show throughput difference.",examples:"readFileSync: 100 files in N seconds. readFile (async): 100 files in M seconds (much less).",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nconst os = require('os');\nconst testFile = path.join(os.tmpdir(), 'test.txt');\n// Create test file\nfs.writeFileSync(testFile, 'x'.repeat(10000));\nconst N = 100;\nasync function benchmarkSync() {\n  const t = Date.now();\n  for (let i=0; i<N; i++) fs.readFileSync(testFile);\n  return Date.now()-t;\n}\nasync function benchmarkAsync() {\n  const t = Date.now();\n  await Promise.all(Array.from({length:N},()=>fs.promises.readFile(testFile)));\n  return Date.now()-t;\n}\nasync function run() {\n  const syncMs = await benchmarkSync();\n  const asyncMs = await benchmarkAsync();\n  console.log(`Sync: ${syncMs}ms (${(N/syncMs*1000).toFixed(0)} files/sec)`);\n  console.log(`Async: ${asyncMs}ms (${(N/asyncMs*1000).toFixed(0)} files/sec)`);\n  console.log(`Async is ${(syncMs/asyncMs).toFixed(1)}x faster for parallel reads`);\n  fs.unlinkSync(testFile);\n}\nrun();",hints:"Promise.all runs all reads in parallel. readFileSync runs sequentially. On SSD the difference may be small but on network drives it's huge.",solutionExplanation:"Async parallel I/O: OS handles all reads concurrently, callbacks queue. Sync: each read blocks until complete. Throughput: N/(async_total) >> N/(sync_total)."},
  {lessonId:43,difficulty:"Hard",title:"Custom Scheduler",problemStatement:"Build a priority task scheduler that processes tasks in priority order using the event loop. High priority tasks preempt low priority ones.",examples:"scheduler.add(task, 'high'). scheduler.add(task, 'low'). High priority runs first each tick.",starterCodeJs:"class PriorityScheduler {\n  constructor() {\n    this._queues = { critical: [], high: [], normal: [], low: [] };\n    this._running = false;\n  }\n  add(task, priority='normal', label='') {\n    const p = this._queues[priority];\n    if (!p) throw new Error(`Unknown priority: ${priority}`);\n    p.push({ task, label, addedAt: Date.now() });\n    if (!this._running) this._schedule();\n  }\n  _schedule() {\n    setImmediate(() => this._tick()); // yield to event loop between ticks\n  }\n  async _tick() {\n    const item = this._getNext();\n    if (!item) { this._running = false; return; }\n    this._running = true;\n    try { await item.task(); } catch(e) { console.error('Task error:', e); }\n    if (this._hasPending()) this._schedule();\n    else this._running = false;\n  }\n  _getNext() {\n    for (const priority of ['critical','high','normal','low']) {\n      if (this._queues[priority].length) return this._queues[priority].shift();\n    }\n    return null;\n  }\n  _hasPending() { return Object.values(this._queues).some(q=>q.length>0); }\n  get pending() { return Object.fromEntries(Object.entries(this._queues).map(([k,v])=>[k,v.length])); }\n}",hints:"setImmediate yields between tasks, allowing I/O callbacks to run. Priority: always check highest priority queues first. Running flag prevents concurrent ticks.",solutionExplanation:"Priority scheduler: check queues in priority order. setImmediate yields to event loop between tasks (critical: other events can still fire). Cooperative scheduling."},

  // Small gap fills for 49, 50, 52, 53
  {lessonId:49,difficulty:"Easy",title:"SQL CRUD Operations",problemStatement:"Write complete SQL for creating, reading, updating, and deleting blog posts. Include proper error handling for not found cases.",examples:"INSERT INTO posts... SELECT * FROM posts WHERE id=?... UPDATE posts SET... DELETE FROM posts WHERE id=?",starterCodeJs:"// CREATE\nconst createPost = `INSERT INTO posts (title, body, author_id, published, created_at) VALUES (?, ?, ?, 0, CURRENT_TIMESTAMP)`;\n// READ ONE\nconst getPost = `SELECT posts.*, users.name as author_name FROM posts JOIN users ON posts.author_id = users.id WHERE posts.id = ?`;\n// READ MANY with pagination\nconst getPosts = `\n  SELECT posts.id, posts.title, posts.created_at, users.name as author_name,\n         COUNT(comments.id) as comment_count\n  FROM posts\n  LEFT JOIN users ON posts.author_id = users.id\n  LEFT JOIN comments ON comments.post_id = posts.id\n  WHERE posts.published = 1\n  GROUP BY posts.id\n  ORDER BY posts.created_at DESC\n  LIMIT ? OFFSET ?\n`;\n// UPDATE\nconst updatePost = `UPDATE posts SET title=?, body=?, updated_at=CURRENT_TIMESTAMP WHERE id=? AND author_id=?`;\n// DELETE\nconst deletePost = `DELETE FROM posts WHERE id=? AND author_id=?`;\n// PUBLISH\nconst publishPost = `UPDATE posts SET published=1, published_at=CURRENT_TIMESTAMP WHERE id=? AND author_id=?`;",hints:"Join for related data. COUNT(comments) uses LEFT JOIN + GROUP BY. Include author_id in UPDATE/DELETE WHERE to prevent unauthorized changes.",solutionExplanation:"SQL CRUD: always scope UPDATE/DELETE to the owner (author_id) to prevent unauthorized changes. LEFT JOIN for optional relations. GROUP BY for aggregates."},
  {lessonId:49,difficulty:"Hard",title:"Complex Join Queries",problemStatement:"Write complex SQL: users with their post count, average views, and most recent post. Use subqueries and CTEs.",examples:"SELECT users.name, post_stats.count, post_stats.avg_views FROM users LEFT JOIN (subquery) post_stats...",starterCodeJs:"-- Using CTE for readability\nconst userStatsQuery = `\nWITH post_stats AS (\n  SELECT\n    author_id,\n    COUNT(*) as post_count,\n    AVG(views) as avg_views,\n    MAX(created_at) as last_post_at,\n    SUM(views) as total_views\n  FROM posts\n  WHERE published = 1\n  GROUP BY author_id\n),\ntop_posts AS (\n  SELECT author_id, title as top_post_title,\n    ROW_NUMBER() OVER(PARTITION BY author_id ORDER BY views DESC) as rn\n  FROM posts WHERE published = 1\n)\nSELECT\n  u.id, u.name, u.email,\n  COALESCE(ps.post_count, 0) as post_count,\n  COALESCE(ROUND(ps.avg_views, 1), 0) as avg_views,\n  ps.last_post_at,\n  tp.top_post_title\nFROM users u\nLEFT JOIN post_stats ps ON ps.author_id = u.id\nLEFT JOIN top_posts tp ON tp.author_id = u.id AND tp.rn = 1\nORDER BY post_count DESC\n`;",hints:"CTE breaks complex query into readable parts. ROW_NUMBER() OVER(PARTITION BY) gets first per group. COALESCE handles NULL from LEFT JOIN.",solutionExplanation:"CTEs: WITH name AS (...) creates named subquery. ROW_NUMBER() OVER(PARTITION BY author_id) ranks each author's posts. Filter rn=1 for top post."},

  {lessonId:50,difficulty:"Hard",title:"Redis-like Sorted Set",problemStatement:"Implement a sorted set data structure (like Redis ZADD/ZRANGE/ZRANK). Members are scored and returned in score order.",examples:"ss.zadd('leaderboard', 100, 'alice'). ss.zrange('leaderboard', 0, 9). ss.zrank('leaderboard', 'alice').",starterCodeJs:"class SortedSetStore {\n  constructor() { this._sets = new Map(); }\n  _getSet(key) {\n    if (!this._sets.has(key)) this._sets.set(key, new Map()); // member -> score\n    return this._sets.get(key);\n  }\n  zadd(key, score, member) {\n    const set = this._getSet(key);\n    const isNew = !set.has(member);\n    set.set(member, score);\n    return isNew ? 1 : 0;\n  }\n  zscore(key, member) { return this._getSet(key).get(member) ?? null; }\n  zrank(key, member) {\n    const sorted = this._getSorted(key);\n    return sorted.findIndex(([m]) => m === member);\n  }\n  _getSorted(key) { return [...this._getSet(key).entries()].sort((a,b)=>a[1]-b[1]); }\n  zrange(key, start, stop, withScores=false) {\n    const sorted = this._getSorted(key).slice(start, stop<0?undefined:stop+1);\n    return withScores ? sorted.flatMap(([m,s])=>[m,s]) : sorted.map(([m])=>m);\n  }\n  zrevrange(key, start, stop) {\n    const sorted = this._getSorted(key).reverse().slice(start, stop<0?undefined:stop+1);\n    return sorted.map(([m])=>m);\n  }\n  zcount(key, min, max) { return this._getSorted(key).filter(([,s])=>s>=min&&s<=max).length; }\n  zincrby(key, increment, member) {\n    const set = this._getSet(key);\n    const current = set.get(member) || 0;\n    set.set(member, current + increment);\n    return current + increment;\n  }\n}",hints:"Internal: Map<member,score>. Sort on demand for range queries. zrank = index in sorted array. stop=-1 means end (slice undefined).",solutionExplanation:"Sorted set: unique members with float scores. Internal Map for O(1) score lookup. Sort for range queries (could use skip list for O(log n))."},

  {lessonId:52,difficulty:"Hard",title:"Schema Evolution Strategy",problemStatement:"Demonstrate database schema evolution with backward-compatible migrations. Show how to add columns, rename columns, and change types safely.",examples:"Add nullable column first. Backfill data. Add NOT NULL constraint. Each step is backward compatible.",starterCodeJs:"// Schema evolution strategies\nconst migrations = [\n  // Step 1: Add nullable column (backward compatible)\n  `ALTER TABLE users ADD COLUMN full_name TEXT`,\n  // Step 2: Backfill existing data\n  `UPDATE users SET full_name = name WHERE full_name IS NULL`,\n  // Step 3: In production, validate no nulls remain before making required\n  // Don't run until all code uses full_name instead of name\n  // `ALTER TABLE users ALTER COLUMN full_name TEXT NOT NULL`, -- SQLite doesn't support this\n\n  // Rename strategy: add new, keep old, copy data, deprecate old\n  `ALTER TABLE users ADD COLUMN email_address TEXT`,\n  `UPDATE users SET email_address = email WHERE email_address IS NULL`,\n  `CREATE INDEX idx_users_email_address ON users(email_address)`,\n  // Then remove old column after all code migrated\n\n  // Type change: create new column, copy converted data, swap\n  `ALTER TABLE orders ADD COLUMN total_cents INTEGER`,\n  `UPDATE orders SET total_cents = CAST(total_float * 100 AS INTEGER)`,\n  // Deploy code using total_cents, then drop total_float\n];\nconsole.log('Migration count:', migrations.length);",hints:"Never rename or change type in one step in production. Always: add new -> backfill -> deploy code -> remove old. Two-phase deployment.",solutionExplanation:"Zero-downtime schema changes: add nullable first (old code works), backfill, deploy new code, make required. Rename: parallel columns, copy, swap."},

  {lessonId:53,difficulty:"Medium",title:"Index Scan vs Full Scan Demo",problemStatement:"Write queries demonstrating the performance difference between indexed and non-indexed lookups. Create test data and benchmark.",examples:"Without index on email: SCAN TABLE. With index: SEARCH TABLE USING INDEX. Show timing difference.",starterCodeJs:"const Database = require('better-sqlite3');\nconst db = new Database(':memory:');\nasync function demo() {\n  // Setup\n  db.exec(`CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, email TEXT, age INTEGER)`);\n  const insert = db.prepare('INSERT INTO users (name,email,age) VALUES (?,?,?)');\n  db.transaction(() => {\n    for (let i=0; i<100000; i++) insert.run(`User${i}`, `user${i}@test.com`, 18+i%60);\n  })();\n  // Without index\n  const plan1 = db.prepare('EXPLAIN QUERY PLAN SELECT * FROM users WHERE email=?').all('user50000@test.com');\n  const t1 = Date.now();\n  for (let i=0; i<100; i++) db.prepare('SELECT * FROM users WHERE email=?').get('user50000@test.com');\n  const noIndexMs = (Date.now()-t1)/100;\n  // Add index\n  db.exec('CREATE INDEX idx_email ON users(email)');\n  const plan2 = db.prepare('EXPLAIN QUERY PLAN SELECT * FROM users WHERE email=?').all('user50000@test.com');\n  const t2 = Date.now();\n  for (let i=0; i<100; i++) db.prepare('SELECT * FROM users WHERE email=?').get('user50000@test.com');\n  const indexMs = (Date.now()-t2)/100;\n  console.log('Without index:', plan1[0].detail, `${noIndexMs.toFixed(2)}ms`);\n  console.log('With index:', plan2[0].detail, `${indexMs.toFixed(2)}ms`);\n  console.log(`Speedup: ${(noIndexMs/indexMs).toFixed(0)}x`);\n}",hints:"better-sqlite3 is synchronous. Use transaction for bulk insert (100x faster). EXPLAIN QUERY PLAN shows access method. 100 iterations for stable timing.",solutionExplanation:"100,000 rows: full scan reads all rows (O(n)). Index: B-tree lookup O(log n). Typically 100-1000x faster for point lookups. Insert uses transaction for speed."},
  {lessonId:53,difficulty:"Easy",title:"Database Connection Pool Basic",problemStatement:"Implement a simple database connection pool with acquire/release. Show how pooling reduces connection overhead.",examples:"pool.withConnection(async conn => { return conn.query(sql); }). Auto-release after function.",starterCodeJs:"class SimplePool {\n  constructor(createConn, { max=5, min=1 } = {}) {\n    this._create = createConn;\n    this._max = max;\n    this._idle = [];\n    this._count = 0;\n    this._waiting = [];\n    // Pre-create min connections\n    for (let i=0; i<min; i++) this._create().then(c => { this._count++; this._idle.push(c); });\n  }\n  async acquire() {\n    if (this._idle.length) return this._idle.pop();\n    if (this._count < this._max) { this._count++; return this._create(); }\n    return new Promise((res,rej) => this._waiting.push({res,rej}));\n  }\n  release(conn) {\n    if (this._waiting.length) { const {res} = this._waiting.shift(); res(conn); return; }\n    this._idle.push(conn);\n  }\n  async withConnection(fn) {\n    const conn = await this.acquire();\n    try { return await fn(conn); } finally { this.release(conn); }\n  }\n  get stats() { return { idle: this._idle.length, total: this._count, waiting: this._waiting.length }; }\n}\nmodule.exports = SimplePool;",hints:"withConnection uses try/finally to always release. Waiters get connection immediately on release. LIFO (pop) keeps recently used connections warm.",solutionExplanation:"Connection pool: reuse expensive DB connections. withConnection pattern ensures release even on error. Pre-create min connections to reduce first-request latency."}
];

async function main() {
  let qi=0,qs=0,ci=0,cs=0;
  for (const q of quizQuestions) {
    const exists = await p.quizQuestion.findFirst({where:{lessonId:q.lessonId,question:q.question}});
    if (!exists) { await p.quizQuestion.create({data:q}); qi++; } else qs++;
  }
  for (const q of codingQuestions) {
    const exists = await p.practiceQuestion.findFirst({where:{lessonId:q.lessonId,title:q.title}});
    if (!exists) { await p.practiceQuestion.create({data:q}); ci++; } else cs++;
  }
  console.log(`Quiz: ${qi} inserted, ${qs} skipped. Coding: ${ci} inserted, ${cs} skipped.`);
}
main().catch(console.error).finally(()=>p.$disconnect());
