// Seed: Quiz + Coding questions for lessons 6-10 (HTML module, second half)
const { PrismaClient } = require('@prisma/client')
const p = new PrismaClient()

const quiz = [
  // Lesson 6: Media Elements
  { lessonId:6, sortOrder:1, difficulty:'Easy', question:'Which attribute on <video> shows playback controls?', options:['showcontrols','controls','display','ui'], correctAnswer:1, explanation:'The boolean controls attribute renders the browser\'s built-in play/pause/volume controls on the video.' },
  { lessonId:6, sortOrder:2, difficulty:'Easy', question:'What does the autoplay attribute do?', options:['Loops the video','Starts playing when loaded','Mutes the audio','Preloads the video'], correctAnswer:1, explanation:'autoplay starts the video as soon as enough data is loaded. Most browsers require muted to also be present.' },
  { lessonId:6, sortOrder:3, difficulty:'Medium', question:'What is the purpose of multiple <source> elements inside <video>?', options:['Play multiple videos','Provide fallback formats for different browser support','Add captions','Set quality levels'], correctAnswer:1, explanation:'Different browsers support different codecs. Multiple <source> elements let the browser pick the first format it supports.' },
  { lessonId:6, sortOrder:4, difficulty:'Medium', question:'Which element adds closed captions to a video?', options:['<caption>','<subtitle>','<track>','<cc>'], correctAnswer:2, explanation:'<track kind="subtitles"> or <track kind="captions"> adds WebVTT caption tracks to <video> or <audio>.' },
  { lessonId:6, sortOrder:5, difficulty:'Medium', question:'What does preload="none" tell the browser?', options:['Do not preload any video data until play is clicked','Preload the entire video','Preload just metadata','Remove preloading entirely'], correctAnswer:0, explanation:'preload="none" conserves bandwidth by not downloading video data until the user explicitly plays it.' },
  { lessonId:6, sortOrder:6, difficulty:'Medium', question:'Which image format is best for photos on the web?', options:['PNG','BMP','WebP or JPEG','GIF'], correctAnswer:2, explanation:'WebP provides superior compression to JPEG. Use WebP with a JPEG fallback via <picture> for broad compatibility.' },
  { lessonId:6, sortOrder:7, difficulty:'Hard', question:'What is the purpose of the <picture> element?', options:['Displays a gallery','Provides art direction and format fallbacks for images','Replaces <img>','Adds captions to images'], correctAnswer:1, explanation:'<picture> wraps <source> elements for art direction (different crops per viewport) and format selection (WebP vs JPEG).' },
  { lessonId:6, sortOrder:8, difficulty:'Hard', question:'What is the srcset attribute used for?', options:['Multiple image sources for different formats','Responsive images — different resolutions for different screen densities','Lazy loading','SEO alternate images'], correctAnswer:1, explanation:'srcset provides multiple image files at different widths/densities so the browser picks the most appropriate one.' },
  { lessonId:6, sortOrder:9, difficulty:'Hard', question:'What does the sizes attribute on <img> specify?', options:['The displayed image dimensions','How wide the image will be at each breakpoint, helping the browser pick from srcset','The file size limit','The minimum image width'], correctAnswer:1, explanation:'sizes tells the browser the image\'s display width at each media condition, which guides srcset selection before layout.' },
  { lessonId:6, sortOrder:10, difficulty:'Hard', question:'What does loading="lazy" do on an <img>?', options:['Caches the image','Defers loading until image is near the viewport','Loads a low-res placeholder first','Prevents the image from loading'], correctAnswer:1, explanation:'loading="lazy" is a native browser hint to defer loading off-screen images, improving initial page load.' },

  // Lesson 7: SEO Basics
  { lessonId:7, sortOrder:1, difficulty:'Easy', question:'What is the ideal length for an HTML <title> tag for SEO?', options:['Under 30 characters','50-60 characters','100+ characters','Exactly 80 characters'], correctAnswer:1, explanation:'Search engines typically display 50-60 characters of the title. Longer titles get truncated in SERPs.' },
  { lessonId:7, sortOrder:2, difficulty:'Easy', question:'What does the meta description tag do for SEO?', options:['Directly improves rankings','Appears as the snippet below the title in search results','Sets page keywords','Prevents indexing'], correctAnswer:1, explanation:'Meta description does not directly affect rankings but influences click-through rate as the SERP snippet.' },
  { lessonId:7, sortOrder:3, difficulty:'Easy', question:'What does robots meta content="noindex" do?', options:['Blocks crawlers from all pages','Tells search engines not to index this specific page','Disables JavaScript','Hides page from users'], correctAnswer:1, explanation:'noindex instructs search engine crawlers to exclude this page from their search index.' },
  { lessonId:7, sortOrder:4, difficulty:'Medium', question:'What is a canonical URL?', options:['The homepage URL','The preferred URL for duplicate or similar content','The sitemap URL','The robots.txt URL'], correctAnswer:1, explanation:'<link rel="canonical" href="..."> tells search engines which URL is the authoritative version when duplicate content exists.' },
  { lessonId:7, sortOrder:5, difficulty:'Medium', question:'What does structured data (Schema.org) help with?', options:['Page styling','Enabling rich results (star ratings, FAQs) in search results','Faster page loading','Security'], correctAnswer:1, explanation:'Schema.org JSON-LD structured data helps search engines understand your content and display rich results.' },
  { lessonId:7, sortOrder:6, difficulty:'Medium', question:'What is the hreflang attribute used for?', options:['Language declaration for accessibility','Telling search engines which language/region version to show to which users','CSS localization','Font language support'], correctAnswer:1, explanation:'hreflang="en-US" on <link> elements tells Google which page version to show users based on their language and location.' },
  { lessonId:7, sortOrder:7, difficulty:'Medium', question:'Why is page load speed important for SEO?', options:['It is not a ranking factor','It is a direct Google ranking factor and affects bounce rate','It only affects mobile rankings','It only matters for paid search'], correctAnswer:1, explanation:'Core Web Vitals (LCP, CLS, FID) are ranking signals. Slow pages also increase bounce rate, further hurting rankings.' },
  { lessonId:7, sortOrder:8, difficulty:'Hard', question:'What does Open Graph (og:) meta do?', options:['Improves Google rankings','Controls how content appears when shared on social media','Adds structured data','Speeds up page loading'], correctAnswer:1, explanation:'Open Graph tags control the title, description, and image shown when a URL is shared on Facebook, LinkedIn, Twitter, etc.' },
  { lessonId:7, sortOrder:9, difficulty:'Hard', question:'What is the purpose of a sitemap.xml file?', options:['Styles the site','Lists all page URLs to help crawlers discover and index content','Blocks pages from indexing','Caches pages for performance'], correctAnswer:1, explanation:'An XML sitemap lists URLs with optional metadata (last modified, priority) to help search engine crawlers discover all pages.' },
  { lessonId:7, sortOrder:10, difficulty:'Hard', question:'What is a Core Web Vital?', options:['A browser performance API','User-centric metrics (LCP, FID/INP, CLS) used by Google as ranking signals','A CSS performance property','A JavaScript memory metric'], correctAnswer:1, explanation:'Core Web Vitals are: LCP (load), FID/INP (interactivity), and CLS (visual stability) — real-world user experience signals.' },

  // Lesson 8: HTML5 APIs
  { lessonId:8, sortOrder:1, difficulty:'Easy', question:'Which HTML5 API stores data persistently across browser sessions?', options:['sessionStorage','cookies only','localStorage','indexedDB only'], correctAnswer:2, explanation:'localStorage persists data across browser sessions until explicitly cleared. sessionStorage is cleared when the tab closes.' },
  { lessonId:8, sortOrder:2, difficulty:'Easy', question:'What does the Geolocation API return?', options:['IP address location','GPS coordinates (latitude/longitude)','City name','Postal code'], correctAnswer:1, explanation:'navigator.geolocation.getCurrentPosition() returns latitude, longitude, accuracy, and optionally altitude.' },
  { lessonId:8, sortOrder:3, difficulty:'Medium', question:'What is the Canvas API used for?', options:['3D rendering only','Drawing 2D (and 3D via WebGL) graphics programmatically','Displaying SVG','Animating CSS'], correctAnswer:1, explanation:'The <canvas> element provides a 2D drawing API (getContext("2d")) for graphics, charts, games, and image manipulation.' },
  { lessonId:8, sortOrder:4, difficulty:'Medium', question:'Which API enables offline web applications?', options:['Cache API + Service Workers','AppCache (deprecated)','localStorage','WebSQL'], correctAnswer:0, explanation:'Service Workers intercept network requests and Cache API stores responses, enabling reliable offline functionality.' },
  { lessonId:8, sortOrder:5, difficulty:'Medium', question:'What does the Drag and Drop API provide?', options:['Touch support','Events (dragstart, dragover, drop) and DataTransfer for dragging elements','Scroll snapping','CSS animations'], correctAnswer:1, explanation:'The HTML5 DnD API fires events on draggable elements and drop targets, with DataTransfer for passing data between them.' },
  { lessonId:8, sortOrder:6, difficulty:'Medium', question:'What is the purpose of the History API?', options:['Stores browsing history','Allows JS to manipulate the browser URL and history without full page reloads','Tracks user navigation','Provides undo/redo functionality'], correctAnswer:1, explanation:'history.pushState() / replaceState() update the URL and history stack without triggering a page reload — core to SPAs.' },
  { lessonId:8, sortOrder:7, difficulty:'Hard', question:'What is the difference between localStorage and sessionStorage?', options:['No difference','localStorage persists across sessions; sessionStorage is cleared when the tab closes','sessionStorage is larger','localStorage requires HTTPS'], correctAnswer:1, explanation:'Both are ~5MB synchronous key-value stores. localStorage persists indefinitely; sessionStorage is tab-scoped and clears on close.' },
  { lessonId:8, sortOrder:8, difficulty:'Hard', question:'What does the Intersection Observer API do?', options:['Observes CSS changes','Asynchronously watches when elements enter/leave the viewport — used for lazy loading and infinite scroll','Monitors network requests','Tracks mouse position'], correctAnswer:1, explanation:'IntersectionObserver fires a callback when an observed element enters or exits a root element (usually the viewport) without polling.' },
  { lessonId:8, sortOrder:9, difficulty:'Hard', question:'What is the Web Storage limit per origin?', options:['1 KB','100 KB','~5 MB for localStorage','Unlimited'], correctAnswer:2, explanation:'localStorage and sessionStorage are typically limited to ~5 MB per origin. Exceeding it throws a QuotaExceededError.' },
  { lessonId:8, sortOrder:10, difficulty:'Hard', question:'Which API enables real-time bidirectional communication without polling?', options:['XMLHttpRequest','Fetch API','WebSockets','Server-Sent Events'], correctAnswer:2, explanation:'WebSockets provide a full-duplex persistent connection (ws:// or wss://) for real-time apps like chat and live dashboards.' },

  // Lesson 9: Browser Parsing & Critical Rendering Path
  { lessonId:9, sortOrder:1, difficulty:'Easy', question:'What does the browser build from parsing HTML?', options:['CSSOM','DOM','Render Tree','Layout Tree'], correctAnswer:1, explanation:'The browser parses HTML into the Document Object Model (DOM) — a tree of nodes representing page elements.' },
  { lessonId:9, sortOrder:2, difficulty:'Easy', question:'What blocks HTML parsing?', options:['Images','External CSS and synchronous scripts','Async scripts','Fonts'], correctAnswer:1, explanation:'External stylesheets and synchronous <script> tags without defer/async block the HTML parser from continuing.' },
  { lessonId:9, sortOrder:3, difficulty:'Medium', question:'What is the Critical Rendering Path?', options:['The CSS paint process','The sequence: Parse HTML → Build DOM + CSSOM → Render Tree → Layout → Paint → Composite','The JavaScript execution order','The network request chain'], correctAnswer:1, explanation:'The CRP is the series of steps a browser takes to convert HTML/CSS/JS into pixels on screen.' },
  { lessonId:9, sortOrder:4, difficulty:'Medium', question:'What is the difference between defer and async on script tags?', options:['No difference','defer: executes after HTML parsing in order; async: executes immediately when downloaded, out of order','async: executes after parsing; defer: immediately','Both block parsing'], correctAnswer:1, explanation:'defer maintains script order and executes after DOM is ready. async executes as soon as downloaded, blocking parser briefly.' },
  { lessonId:9, sortOrder:5, difficulty:'Medium', question:'What triggers a reflow (layout recalculation)?', options:['Changing color','Changing width, height, margin, or reading offsetHeight/scrollTop','Adding event listeners','Changing opacity'], correctAnswer:1, explanation:'Reflow recalculates positions and dimensions. Reading layout properties (offsetWidth) forces synchronous reflow.' },
  { lessonId:9, sortOrder:6, difficulty:'Medium', question:'What is LCP (Largest Contentful Paint)?', options:['When JS loads','Time until the largest image or text block in the viewport is rendered','First byte received','When DOM is ready'], correctAnswer:1, explanation:'LCP measures when the largest visible content element (hero image, heading) is painted. Good LCP is under 2.5s.' },
  { lessonId:9, sortOrder:7, difficulty:'Hard', question:'What is the CSSOM?', options:['A JavaScript framework','CSS Object Model — the CSS equivalent of the DOM, built from parsed stylesheets','A browser extension API','The cascade algorithm'], correctAnswer:1, explanation:'CSSOM maps CSS rules to nodes. The Render Tree is created by combining DOM + CSSOM, only including visible nodes.' },
  { lessonId:9, sortOrder:8, difficulty:'Hard', question:'What does CSS being render-blocking mean?', options:['CSS is slower than JS','Browser will not paint until CSSOM is built — no HTML renders until CSS loads','CSS blocks JavaScript','CSS prevents HTML parsing'], correctAnswer:1, explanation:'Browsers wait for CSSOM before painting to avoid showing unstyled content (FOUC). This is why CSS should be in <head>.' },
  { lessonId:9, sortOrder:9, difficulty:'Hard', question:'What does will-change: transform do?', options:['Applies a transform','Hints to the browser to promote element to its own compositor layer, avoiding repaints','Enables GPU rendering globally','Prevents layout shifts'], correctAnswer:1, explanation:'will-change promotes the element to a separate GPU layer, so animating it does not trigger repaints of other elements.' },
  { lessonId:9, sortOrder:10, difficulty:'Hard', question:'What is CLS (Cumulative Layout Shift)?', options:['Content Loading Speed','Cumulative Layout Shift — measures unexpected layout movement during page load','Content Layout Style','A CSS animation metric'], correctAnswer:1, explanation:'CLS measures visual stability. Images without dimensions, late-injected ads, and web fonts cause layout shifts. Good CLS < 0.1.' },

  // Lesson 10: DOM Fundamentals
  { lessonId:10, sortOrder:1, difficulty:'Easy', question:'What does document.querySelector() return?', options:['All matching elements as NodeList','The first matching element','The last matching element','An array of elements'], correctAnswer:1, explanation:'querySelector returns the first element that matches the CSS selector, or null if none found.' },
  { lessonId:10, sortOrder:2, difficulty:'Easy', question:'Which method creates a new DOM element?', options:['document.newElement()','document.buildElement()','document.createElement()','document.makeElement()'], correctAnswer:2, explanation:'document.createElement("div") creates a new div element in memory. It must then be appended to the document to be visible.' },
  { lessonId:10, sortOrder:3, difficulty:'Medium', question:'What is the difference between innerHTML and textContent?', options:['No difference','innerHTML parses HTML and can cause XSS; textContent sets plain text safely','textContent is slower','innerHTML removes child elements'], correctAnswer:1, explanation:'innerHTML parses the string as HTML (XSS risk). textContent sets raw text, escaping any HTML characters — always prefer textContent for user data.' },
  { lessonId:10, sortOrder:4, difficulty:'Medium', question:'What does addEventListener\'s third parameter (true/false) control?', options:['Event priority','useCapture — true fires during capture phase (top-down), false fires during bubble phase (bottom-up)','Preventing defaults','Event throttling'], correctAnswer:1, explanation:'Event propagation has capture (document → target) and bubble (target → document) phases. useCapture=true handles during capture.' },
  { lessonId:10, sortOrder:5, difficulty:'Medium', question:'What is event bubbling?', options:['Events firing on load','When an event fires on a target and then propagates up through ancestor elements','When multiple events fire at once','CSS animation events'], correctAnswer:1, explanation:'Events bubble up the DOM tree by default. A click on a <button> also fires click events on its parent, grandparent, etc.' },
  { lessonId:10, sortOrder:6, difficulty:'Medium', question:'What does event.stopPropagation() do?', options:['Prevents default browser behaviour','Stops the event from bubbling/capturing further up or down the DOM','Removes the event listener','Prevents the element from being clicked'], correctAnswer:1, explanation:'stopPropagation() stops the event from propagating to parent elements — it does not prevent the default action.' },
  { lessonId:10, sortOrder:7, difficulty:'Hard', question:'What is the difference between event.target and event.currentTarget?', options:['They are the same','target is the element that triggered the event; currentTarget is the element the listener is attached to','target is the parent element','currentTarget is always document'], correctAnswer:1, explanation:'When using event delegation, currentTarget is the element with the listener, while target is the actual clicked element.' },
  { lessonId:10, sortOrder:8, difficulty:'Hard', question:'What does DocumentFragment do?', options:['Fragments the DOM','A lightweight container for building DOM nodes off-screen before inserting, avoiding multiple reflows','Creates shadow DOM','Clones the document'], correctAnswer:1, explanation:'DocumentFragment lets you build a subtree off-screen and insert it with one DOM operation, triggering only one reflow.' },
  { lessonId:10, sortOrder:9, difficulty:'Hard', question:'What is MutationObserver used for?', options:['Animating DOM changes','Asynchronously watching for DOM mutations (added/removed nodes, attribute changes)','Synchronous DOM events','Observing CSS changes'], correctAnswer:1, explanation:'MutationObserver fires a callback whenever specified DOM changes occur, without the performance cost of polling.' },
  { lessonId:10, sortOrder:10, difficulty:'Hard', question:'What is the difference between cloneNode(true) and cloneNode(false)?', options:['No difference','true clones the element and all its descendants; false clones only the element itself','false clones children','true clones event listeners'], correctAnswer:1, explanation:'cloneNode(true) does a deep clone including child elements. cloneNode(false) creates only a shallow copy of the element.' },
]

const coding = [
  // Lesson 6: Media Elements
  { lessonId:6, difficulty:'Easy', topic:'HTML Media', title:'Responsive Video Player', problemStatement:'Build an HTML video player that: has controls, is muted by default, loops, provides WebM and MP4 sources, and shows a text fallback for unsupported browsers. Wrap in a 16:9 responsive container.', examples:'<video controls muted loop>', starterCodeJs:'function buildVideoPlayer(webmUrl, mp4Url, poster) {\n  return "";\n}', hints:'["<source> order: preferred format first", "poster attribute shows a thumbnail", "padding-top:56.25% for 16:9 ratio"]', solutionExplanation:'Order sources with preferred format first. The browser uses the first it supports and ignores the rest.' },
  { lessonId:6, difficulty:'Easy', topic:'HTML Media', title:'Audio Player with Track', problemStatement:'Create an <audio> element with controls, two source formats (MP3 and OGG), and a <track> element for an English transcript. Show a fallback message for unsupported browsers.', examples:'<track kind="subtitles" src="track.vtt" srclang="en" label="English">', starterCodeJs:'function buildAudioPlayer(mp3, ogg, trackVtt) {\n  return "";\n}', hints:'["kind=captions or subtitles or descriptions", "srclang=en for English", "default attribute makes it active by default"]', solutionExplanation:'The default attribute on <track> enables it automatically. Without it, the user must manually turn on captions.' },
  { lessonId:6, difficulty:'Medium', topic:'HTML Media', title:'Responsive Image with srcset', problemStatement:'Write an <img> with srcset providing 3 widths (400w, 800w, 1200w) and a sizes attribute that serves the right image at different breakpoints.', examples:'sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw"', starterCodeJs:'function buildResponsiveImage(base, alt) {\n  return "";\n}', hints:'["srcset: url width descriptor", "sizes: media condition display width", "Browser picks smallest sufficient image"]', solutionExplanation:'sizes describes how wide the image will be displayed. The browser uses this + device pixel ratio to select from srcset.' },
  { lessonId:6, difficulty:'Medium', topic:'HTML Media', title:'Picture Element Art Direction', problemStatement:'Use <picture> to serve: a portrait crop (400x600) on mobile (max-width:640px), a landscape crop (1200x400) on desktop. Include a WebP version for each and a JPEG fallback <img>.', examples:'<source media="(max-width:640px)" srcset="portrait.webp" type="image/webp">', starterCodeJs:'function buildPicture(images) {\n  // images = {mobileWebp, mobileFallback, desktopWebp, desktopFallback, alt}\n  return "";\n}', hints:'["Source order matters: browser uses first matching source", "Include type for format negotiation", "<img> as last child is the universal fallback"]', solutionExplanation:'Art direction uses <picture> to serve completely different image compositions based on viewport, not just resolution.' },
  { lessonId:6, difficulty:'Medium', topic:'HTML Media', title:'Lazy Image Gallery', problemStatement:'Build a 9-image gallery where all images use loading="lazy", have descriptive alt text, and show a low-quality placeholder blur while loading. Use aspect-ratio to prevent layout shift.', examples:'<img loading="lazy" style="aspect-ratio:1" ...>', starterCodeJs:'function buildGallery(images) {\n  // images = [{src, alt, blurDataUrl}]\n  return "";\n}', hints:'["loading=lazy on all but first image", "aspect-ratio prevents CLS", "Blur placeholder via background-image on wrapper"]', solutionExplanation:'Setting aspect-ratio reserves space before the image loads, preventing layout shifts (improving CLS score).' },
  { lessonId:6, difficulty:'Hard', topic:'HTML Media', title:'Custom Video Controls', problemStatement:'Build a custom video player UI replacing default controls: play/pause button, progress bar (input[type=range]), current time / duration display, mute button, and fullscreen button. Wire all to the HTMLMediaElement API.', examples:'video.play() / video.pause() / video.currentTime', starterCodeJs:'function buildCustomPlayer(src) {\n  return "";\n}\nfunction initPlayer(container) {\n  const video = container.querySelector("video");\n  // Wire up controls\n}', hints:'["video.duration, video.currentTime", "video.timeupdate event for progress", "document.fullscreenElement for fullscreen state"]', solutionExplanation:'Custom controls must handle all states: loading, playing, paused, ended. Always provide keyboard equivalents for each button.' },
  { lessonId:6, difficulty:'Hard', topic:'HTML Media', title:'WebP with JPEG Fallback', problemStatement:'Write a buildImage() function that generates a <picture> element with a WebP source and JPEG fallback for any given image filename (without extension). Add srcset for 1x and 2x densities.', examples:'<picture><source srcset="hero.webp 1x, hero@2x.webp 2x" type="image/webp"><img src="hero.jpg"></picture>', starterCodeJs:'function buildImage(filename, alt, width, height) {\n  return "";\n}', hints:'["type=image/webp triggers format negotiation", "1x and 2x density descriptors", "width/height on img prevents CLS"]', solutionExplanation:'type="image/webp" means browsers that understand WebP will use the source; others fall through to the <img> JPEG.' },
  { lessonId:6, difficulty:'Hard', topic:'HTML Media', title:'Background Video Hero', problemStatement:'Create a hero section with a looping background video (no controls, muted, autoplay), a poster image shown before video loads, and centered text overlay. The video must not autoplay on prefers-reduced-motion.', examples:'matchMedia("(prefers-reduced-motion: reduce)")', starterCodeJs:'function buildHeroSection(videoSrc, poster, title) {\n  return "";\n}\nfunction initVideoAutoplay(video) {\n  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {\n    video.pause();\n  }\n}', hints:'["autoplay muted loop on video", "position:absolute video, relative container", "Check prefers-reduced-motion on load"]', solutionExplanation:'autoplay only works cross-browser when muted. Respecting prefers-reduced-motion is a WCAG 2.3.3 requirement.' },
  { lessonId:6, difficulty:'Easy', topic:'HTML Media', title:'SVG Inline Icon System', problemStatement:'Create a reusable SVG icon system: a hidden <svg> defs block with 3 symbols (menu, close, search), and a function that renders an icon by symbol id with customizable size and color.', examples:'<use href="#icon-menu">', starterCodeJs:'function buildIconSprite() {\n  return `<svg style="display:none">...</svg>`;\n}\nfunction renderIcon(id, size = 24, color = "currentColor") {\n  return "";\n}', hints:'["<symbol> has viewBox but no display", "<use href=#id> reuses the symbol", "fill=currentColor inherits text color"]', solutionExplanation:'SVG sprites with <symbol> and <use> are more efficient than inline SVGs — the sprite is parsed once, icons referenced many times.' },
  { lessonId:6, difficulty:'Medium', topic:'HTML Media', title:'Accessible Image Caption Toggle', problemStatement:'Build an image with a "Show Caption" button. Clicking it reveals/hides the caption text. Use aria-expanded and aria-controls on the button, and aria-hidden on the caption when hidden.', examples:'<button aria-expanded="false" aria-controls="caption-1">Show Caption</button>', starterCodeJs:'function buildImageWithCaption(src, alt, caption) {\n  return "";\n}\nfunction toggleCaption(btn) {\n  const id = btn.getAttribute("aria-controls");\n  const panel = document.getElementById(id);\n  // Toggle visibility and ARIA\n}', hints:'["aria-expanded=true/false on button", "aria-hidden=true/false on panel", "hidden attribute or display:none"]', solutionExplanation:'aria-expanded communicates the widget state to screen readers. aria-controls identifies which element it controls.' },

  // Lesson 7: SEO Basics
  { lessonId:7, difficulty:'Easy', topic:'SEO', title:'Complete Head Tags', problemStatement:'Write a <head> section with all essential SEO tags: charset, viewport, title (55 chars max), meta description (155 chars max), canonical URL, Open Graph tags (title, description, image, type), and Twitter Card tags.', examples:'<meta name="twitter:card" content="summary_large_image">', starterCodeJs:'function buildSEOHead({ url, title, description, image }) {\n  return "";\n}', hints:'["og: use property attribute", "twitter: use name attribute", "canonical href is the absolute URL", "og:type=website for homepage"]', solutionExplanation:'Canonical prevents duplicate content penalties when the same content is accessible at multiple URLs.' },
  { lessonId:7, difficulty:'Easy', topic:'SEO', title:'Structured Data JSON-LD', problemStatement:'Add Schema.org Article structured data as a JSON-LD <script> tag for a blog post. Include: @type, headline, author (Person), datePublished, and image properties.', examples:'<script type="application/ld+json">{...}</script>', starterCodeJs:'function buildArticleStructuredData({ title, author, date, image, url }) {\n  const schema = {\n    "@context": "https://schema.org",\n    "@type": "Article",\n    // Complete this\n  };\n  return `<script type="application/ld+json">${JSON.stringify(schema)}<\\/script>`;\n}', hints:'["@context is always https://schema.org", "author is a nested Person object", "datePublished in ISO 8601 format"]', solutionExplanation:'JSON-LD structured data is the recommended format — it can be placed anywhere in the document without affecting presentation.' },
  { lessonId:7, difficulty:'Medium', topic:'SEO', title:'Breadcrumb Structured Data', problemStatement:'Add Schema.org BreadcrumbList structured data for: Home > Blog > JavaScript > Closures. Each item needs id, name, and item (URL) properties in order.', examples:'BreadcrumbList with 4 ListItem elements', starterCodeJs:'function buildBreadcrumbSchema(crumbs) {\n  // crumbs = [{name, url}]\n  const schema = {\n    "@context": "https://schema.org",\n    "@type": "BreadcrumbList",\n    // itemListElement array\n  };\n  return JSON.stringify(schema, null, 2);\n}', hints:'["itemListElement is an array of ListItem", "position starts at 1", "item is the full URL", "name is the display text"]', solutionExplanation:'BreadcrumbList structured data enables breadcrumb display in SERPs below the page title.' },
  { lessonId:7, difficulty:'Medium', topic:'SEO', title:'Robots Meta and X-Robots', problemStatement:'Write a function that generates the correct robots meta tag for 4 scenarios: (1) fully indexable, (2) noindex, (3) nofollow, (4) noindex+noarchive. Also show the equivalent HTTP header.', examples:'<meta name="robots" content="noindex, nofollow">', starterCodeJs:'function buildRobotsMeta(index, follow, archive) {\n  const directives = [];\n  if (!index) directives.push("noindex");\n  if (!follow) directives.push("nofollow");\n  if (!archive) directives.push("noarchive");\n  // Return the meta tag\n  return "";\n}', hints:'["Comma-separate multiple directives", "HTTP: X-Robots-Tag: noindex", "Empty content or content=all means fully indexable"]', solutionExplanation:'X-Robots-Tag HTTP header works on non-HTML files (PDFs). Meta robots only work on HTML pages.' },
  { lessonId:7, difficulty:'Medium', topic:'SEO', title:'Hreflang for Multilingual', problemStatement:'Build a <head> section with hreflang alternate links for an article available in 3 languages: en-US (/en/article), fr-FR (/fr/article), de-DE (/de/article). Include an x-default fallback.', examples:'<link rel="alternate" hreflang="en-US" href="...">', starterCodeJs:'function buildHreflangLinks(baseUrl, locales) {\n  // locales = [{lang, path}]\n  return "";\n}', hints:'["Each page must link to ALL its translations", "x-default is shown when no locale matches", "hreflang value must be BCP 47 language code"]', solutionExplanation:'All language versions must link to each other with hreflang. Missing reciprocal links causes Google to ignore them.' },
  { lessonId:7, difficulty:'Hard', topic:'SEO', title:'Core Web Vitals Fixes', problemStatement:'Given problematic HTML with: (1) an image without dimensions, (2) a late-loading webfont causing FOUT, (3) a large synchronous script — rewrite each element to fix CLS, CLS, and TBT respectively.', examples:'Add width+height, font-display:swap, defer attribute', starterCodeJs:'// Fix 1: Image causing CLS\nconst badImg = `<img src="hero.jpg" alt="Hero">`;\nfunction fixImg(src, alt, w, h) { return ""; }\n\n// Fix 2: Font causing FOUT\nconst badFont = `<link rel="stylesheet" href="fonts.css">`;\nfunction fixFont(fontUrl) { return ""; }\n\n// Fix 3: Blocking script\nconst badScript = `<script src="analytics.js"></script>`;\nfunction fixScript(src) { return ""; }', hints:'["width+height on img prevents CLS", "font-display:swap prevents invisible text", "defer or async on scripts"]', solutionExplanation:'Three most impactful CWV fixes: width/height on images (CLS), font-display:swap (CLS), and defer on non-critical scripts (TBT).' },
  { lessonId:7, difficulty:'Hard', topic:'SEO', title:'FAQ Structured Data', problemStatement:'Generate Schema.org FAQPage JSON-LD for 5 FAQ items. Each question needs acceptedAnswer with a text field. Validate the structure matches Google\'s requirements.', examples:'{"@type":"FAQPage","mainEntity":[{"@type":"Question"...}]}', starterCodeJs:'function buildFAQSchema(faqs) {\n  // faqs = [{question, answer}]\n  return "";\n}', hints:'["@type: FAQPage", "mainEntity array of Question objects", "acceptedAnswer has @type: Answer and text property", "Escape HTML in answers"]', solutionExplanation:'FAQ structured data can generate an expandable FAQ section directly in SERPs, significantly increasing SERP real estate.' },
  { lessonId:7, difficulty:'Hard', topic:'SEO', title:'Performance Budget Checker', problemStatement:'Write a JS function that analyzes a page\'s <head> and reports SEO issues: missing title, description too long/short, missing canonical, missing og:image, and missing viewport meta. Return an array of issues.', examples:'[{severity:"error", issue:"Missing title tag"}]', starterCodeJs:'function auditSEO(headHtml) {\n  const parser = new DOMParser();\n  const doc = parser.parseFromString(`<html><head>${headHtml}</head></html>`, "text/html");\n  const issues = [];\n  // Check each SEO requirement\n  return issues;\n}', hints:'["DOMParser for parsing HTML string", "doc.title for title", "doc.querySelector(\'meta[name=description]\')", "Check content attribute length"]', solutionExplanation:'Programmatic SEO auditing enables automated checks in CI/CD pipelines to prevent regressions.' },
  { lessonId:7, difficulty:'Easy', topic:'SEO', title:'XML Sitemap', problemStatement:'Write a function that generates a valid XML sitemap string for an array of pages. Each page has url, lastmod, changefreq, and priority.', examples:'<?xml version="1.0" encoding="UTF-8"?><urlset ...>', starterCodeJs:'function buildSitemap(pages) {\n  // pages = [{url, lastmod, changefreq, priority}]\n  return "";\n}', hints:'["xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"", "Escape special chars in URLs", "lastmod in YYYY-MM-DD format"]', solutionExplanation:'Sitemaps accelerate discovery of new or updated pages. Submit to Google Search Console for priority crawling.' },
  { lessonId:7, difficulty:'Medium', topic:'SEO', title:'Social Preview Card', problemStatement:'Build a complete social media preview component that shows how a URL will look when shared on Twitter and Facebook. Include the og:image, og:title, og:description using the provided meta values.', examples:'Mock card showing image + title + description + domain', starterCodeJs:'function buildSocialPreview({ title, description, image, domain }) {\n  return "";\n}', hints:'["Twitter card: image (2:1 ratio), title, description, domain", "Facebook: image (1.91:1 ratio)", "Both truncate long descriptions"]', solutionExplanation:'Social previews are your content\'s first impression in feeds. Testing with og:image at 1200×630px ensures crisp display.' },

  // Lesson 8: HTML5 APIs
  { lessonId:8, difficulty:'Easy', topic:'HTML5 APIs', title:'localStorage Todo List', problemStatement:'Build a todo list that persists to localStorage. On load, restore saved todos. On add/remove, update storage. Show the count of completed vs total todos.', examples:'localStorage key: "todos", value: JSON array', starterCodeJs:'let todos = JSON.parse(localStorage.getItem("todos") || "[]");\n\nfunction addTodo(text) {}\nfunction removeTodo(id) {}\nfunction toggleTodo(id) {}\nfunction render() {}\nfunction save() { localStorage.setItem("todos", JSON.stringify(todos)); }', hints:'["Generate id: Date.now()", "Save after every mutation", "Restore on DOMContentLoaded"]', solutionExplanation:'JSON.parse with || "[]" safely handles missing localStorage keys. Always call save() after every mutation.' },
  { lessonId:8, difficulty:'Easy', topic:'HTML5 APIs', title:'Geolocation Distance Calculator', problemStatement:'Use the Geolocation API to get the user\'s location and calculate the distance to a fixed target point (e.g., Taj Mahal: 27.1751, 78.0421). Display coordinates, accuracy, and distance in km using the Haversine formula.', examples:'navigator.geolocation.getCurrentPosition(success, error)', starterCodeJs:'function getLocation() {\n  navigator.geolocation.getCurrentPosition(success, error);\n}\nfunction haversine(lat1, lon1, lat2, lon2) {\n  // Return distance in km\n}\nfunction success(pos) {}\nfunction error(err) {}', hints:'["pos.coords.latitude/longitude/accuracy", "Haversine uses Earth radius 6371 km", "Handle permission denied error"]', solutionExplanation:'The Haversine formula calculates great-circle distance between two lat/lng points on a sphere.' },
  { lessonId:8, difficulty:'Medium', topic:'HTML5 APIs', title:'Canvas Drawing App', problemStatement:'Build a simple canvas drawing app: click-and-drag to draw, color picker, brush size slider, clear button, and download button. Track mouse events to draw continuous lines.', examples:'ctx.beginPath(); ctx.moveTo(); ctx.lineTo(); ctx.stroke()', starterCodeJs:'function initDrawingApp(canvas) {\n  const ctx = canvas.getContext("2d");\n  let drawing = false;\n  canvas.addEventListener("mousedown", () => drawing = true);\n  canvas.addEventListener("mouseup", () => drawing = false);\n  canvas.addEventListener("mousemove", (e) => {\n    if (!drawing) return;\n    // Draw here\n  });\n}', hints:'["e.offsetX/Y for position relative to canvas", "ctx.strokeStyle for color", "ctx.lineWidth for size", "canvas.toDataURL() for download"]', solutionExplanation:'beginPath() starts a new path. Each mousemove segment connects moveTo (last position) to lineTo (current position).' },
  { lessonId:8, difficulty:'Medium', topic:'HTML5 APIs', title:'Intersection Observer Lazy Load', problemStatement:'Implement lazy loading for 10 images using IntersectionObserver. Images start with data-src instead of src. When they enter the viewport, swap data-src to src and unobserve.', examples:'observer.observe(img); // when visible: img.src = img.dataset.src', starterCodeJs:'function initLazyLoad() {\n  const images = document.querySelectorAll("img[data-src]");\n  const observer = new IntersectionObserver((entries) => {\n    entries.forEach(entry => {\n      if (entry.isIntersecting) {\n        // Load image\n      }\n    });\n  }, { rootMargin: "200px" });\n  images.forEach(img => observer.observe(img));\n}', hints:'["rootMargin:200px loads 200px before viewport", "entry.target is the image", "unobserve after loading", "img.classList.add(loaded) for fade-in"]', solutionExplanation:'rootMargin extends the intersection zone — 200px starts loading before the image enters the visible viewport.' },
  { lessonId:8, difficulty:'Medium', topic:'HTML5 APIs', title:'History API SPA Router', problemStatement:'Build a minimal SPA router using the History API. Intercept link clicks, update the URL with pushState, and render the correct "page" content. Handle the popstate event for back/forward navigation.', examples:'history.pushState({page}, "", "/about")', starterCodeJs:'const routes = {\n  "/": () => "<h1>Home</h1>",\n  "/about": () => "<h1>About</h1>",\n  "/contact": () => "<h1>Contact</h1>"\n};\n\nfunction navigate(path) {}\nfunction render(path) {}\n\ndocument.addEventListener("click", (e) => {\n  if (e.target.tagName === "A" && e.target.href.startsWith(location.origin)) {\n    e.preventDefault();\n    navigate(e.target.pathname);\n  }\n});\n\nwindow.addEventListener("popstate", () => render(location.pathname));', hints:'["pushState(state, title, url)", "popstate fires on back/forward", "preventDefault on <a> clicks", "Render based on location.pathname"]', solutionExplanation:'popstate fires when the user navigates history. You must also handle the initial render on page load.' },
  { lessonId:8, difficulty:'Hard', topic:'HTML5 APIs', title:'Service Worker Offline Cache', problemStatement:'Write a service worker that caches a list of static assets on install and serves them from cache on fetch. If not in cache, fetch from network and cache the response. Handle cache versioning.', examples:'self.addEventListener("install", ...) + "fetch" event', starterCodeJs:'const CACHE_NAME = "v1";\nconst STATIC_ASSETS = ["/", "/styles.css", "/app.js"];\n\nself.addEventListener("install", (e) => {\n  e.waitUntil(\n    // Cache static assets\n  );\n});\n\nself.addEventListener("fetch", (e) => {\n  e.respondWith(\n    // Cache-first strategy\n  );\n});', hints:'["caches.open(name).then(cache => cache.addAll(urls))", "Cache-first: check cache, fallback to network", "self.skipWaiting() for immediate activation"]', solutionExplanation:'cache.addAll() is atomic — if any asset fails to cache, the whole install fails, preventing partial offline support.' },
  { lessonId:8, difficulty:'Hard', topic:'HTML5 APIs', title:'WebSocket Live Chat', problemStatement:'Build the client-side of a live chat: connect to ws://localhost:8080, send messages on form submit, display received messages in a list, show connection status, and reconnect on disconnect.', examples:'new WebSocket("ws://localhost:8080")', starterCodeJs:'let ws;\nfunction connect() {\n  ws = new WebSocket("ws://localhost:8080");\n  ws.onopen = () => {};\n  ws.onmessage = (e) => {};\n  ws.onclose = () => { setTimeout(connect, 3000); }; // reconnect\n  ws.onerror = (e) => {};\n}\nfunction sendMessage(text) {\n  if (ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ text }));\n}', hints:'["ws.readyState: CONNECTING=0, OPEN=1, CLOSING=2, CLOSED=3", "Reconnect on close with setTimeout", "Parse JSON messages with JSON.parse(e.data)"]', solutionExplanation:'Always check readyState before sending — the connection may have dropped. Exponential backoff on reconnect prevents hammering.' },
  { lessonId:8, difficulty:'Hard', topic:'HTML5 APIs', title:'Drag and Drop File Upload', problemStatement:'Implement a drag-and-drop upload zone: style it differently on dragover, handle drop to get files, validate type/size, show a preview list of accepted files, and simulate upload progress.', examples:'e.dataTransfer.files on drop event', starterCodeJs:'function buildDropzone() {\n  return "";\n}\nfunction initDropzone(zone) {\n  zone.addEventListener("dragover", (e) => { e.preventDefault(); });\n  zone.addEventListener("drop", (e) => {\n    e.preventDefault();\n    const files = e.dataTransfer.files;\n    // Process files\n  });\n}', hints:'["dragover preventDefault is REQUIRED to allow drop", "dataTransfer.files is a FileList", "FileReader.readAsDataURL for image preview", "Simulate progress with setInterval"]', solutionExplanation:'preventDefault on dragover is essential — without it, the browser opens the file instead of triggering your drop handler.' },
  { lessonId:8, difficulty:'Easy', topic:'HTML5 APIs', title:'Dark Mode Toggle with localStorage', problemStatement:'Build a dark/light mode toggle that: reads from localStorage on page load, applies the theme to the <html> element, updates a toggle button label, and saves preference on change.', examples:'document.documentElement.classList.toggle("dark")', starterCodeJs:'function initTheme() {\n  const saved = localStorage.getItem("theme") || "light";\n  // Apply saved theme\n}\nfunction toggleTheme(btn) {\n  // Toggle and save\n}', hints:'["html.classList.toggle(dark)", "Update button text: Dark Mode/Light Mode", "localStorage.setItem(theme, value)", "Check system preference with matchMedia if no saved preference"]', solutionExplanation:'Apply theme to <html> (not body) so CSS custom properties cascade to all elements including body.' },
  { lessonId:8, difficulty:'Medium', topic:'HTML5 APIs', title:'MutationObserver Form Monitor', problemStatement:'Use MutationObserver to watch a dynamic form that has fields added by a third-party script. When new input elements are added, automatically add your custom validation logic to them.', examples:'observer.observe(form, { childList: true, subtree: true })', starterCodeJs:'function watchForm(formEl) {\n  const observer = new MutationObserver((mutations) => {\n    mutations.forEach(mutation => {\n      mutation.addedNodes.forEach(node => {\n        if (node.nodeType === 1 && node.tagName === "INPUT") {\n          // Attach validation\n        }\n      });\n    });\n  });\n  observer.observe(formEl, { childList: true, subtree: true });\n}', hints:'["childList:true watches for added/removed nodes", "subtree:true includes descendants", "node.nodeType===1 is ELEMENT_NODE", "Also check subtree for inputs in wrappers"]', solutionExplanation:'MutationObserver is the performant alternative to polling for DOM changes — fires asynchronously after a batch of mutations.' },

  // Lesson 9: Critical Rendering Path
  { lessonId:9, difficulty:'Easy', topic:'Performance', title:'Script Loading Strategies', problemStatement:'Write 4 versions of loading analytics.js: (1) blocking, (2) with defer, (3) with async, (4) dynamic injection. Add a comment explaining when each is appropriate.', examples:'// Defer: DOMContentLoaded order. Async: ASAP, any order.', starterCodeJs:'// 1. Blocking (avoid!)\nconst blocking = `<script src="analytics.js"></script>`;\n\n// 2. Defer\nconst deferred = "";\n\n// 3. Async\nconst asyncScript = "";\n\n// 4. Dynamic injection\nfunction loadDynamic(src) {}\n', hints:'["defer: run after HTML parsed, in order", "async: run ASAP when downloaded", "Dynamic: createElement script, set src, append to body"]', solutionExplanation:'Defer is best for scripts needing DOM access. Async is best for independent scripts (analytics). Dynamic for conditionally loaded scripts.' },
  { lessonId:9, difficulty:'Medium', topic:'Performance', title:'Critical CSS Inliner', problemStatement:'Write a function that takes above-the-fold CSS and returns it inline in a <style> tag, with the rest of the CSS loaded asynchronously using rel="preload" + onload trick.', examples:'<link rel="preload" as="style" onload="this.rel=\'stylesheet\'">', starterCodeJs:'function buildCriticalCSS(criticalCSS, fullCssUrl) {\n  return "";\n}', hints:'["Critical CSS: <style>...</style> in <head>", "Non-critical: <link rel=preload as=style onload=this.rel=stylesheet>", "Add <noscript> fallback"]', solutionExplanation:'Inlining critical CSS eliminates one render-blocking request. The preload trick loads full CSS without blocking rendering.' },
  { lessonId:9, difficulty:'Medium', topic:'Performance', title:'Resource Hints', problemStatement:'Write a <head> section using all 4 resource hints: dns-prefetch, preconnect, prefetch (next page), and preload (current page hero image). Add appropriate comments.', examples:'<link rel="preconnect" href="https://fonts.googleapis.com">', starterCodeJs:'function buildResourceHints({ apiDomain, fontsDomain, nextPage, heroImage }) {\n  return "";\n}', hints:'["dns-prefetch: resolves DNS only", "preconnect: DNS + TCP + TLS (use sparingly)", "prefetch: next-nav resources", "preload: current-page critical resources with as attribute"]', solutionExplanation:'preload with as="image" tells the browser this is a high-priority image for the current page, triggering early fetch.' },
  { lessonId:9, difficulty:'Hard', topic:'Performance', title:'Layout Thrashing Fix', problemStatement:'The function below causes layout thrashing by reading and writing layout properties alternately. Refactor it to batch reads first, then writes, eliminating repeated reflows.', examples:'Read all, then write all — avoids interleaved reflow', starterCodeJs:'// BAD: causes layout thrashing\nfunction badLayout(elements) {\n  elements.forEach(el => {\n    const w = el.offsetWidth; // READ forces reflow\n    el.style.width = w * 2 + "px"; // WRITE\n    const h = el.offsetHeight; // READ forces reflow again!\n    el.style.height = h * 2 + "px"; // WRITE\n  });\n}\n\n// GOOD: fix layout thrashing\nfunction goodLayout(elements) {\n  // 1. Read all values first\n  // 2. Then write all values\n}', hints:'["Collect all offsetWidth/offsetHeight first", "Then loop again to set widths/heights", "Or use requestAnimationFrame to batch writes"]', solutionExplanation:'Reading offsetWidth forces the browser to flush pending style changes and recalculate layout synchronously — interleaving reads/writes causes this for every element.' },
  { lessonId:9, difficulty:'Hard', topic:'Performance', title:'Performance Mark and Measure', problemStatement:'Instrument a page load with the User Timing API: mark "app-start" before JS init, mark "app-ready" after, measure "app-init-time" between them, and log all performance entries.', examples:'performance.mark("app-start"); performance.measure("app-init-time", "app-start", "app-ready")', starterCodeJs:'performance.mark("app-start");\n\nfunction initApp() {\n  // Your app init code\n  performance.mark("app-ready");\n  performance.measure("app-init-time", "app-start", "app-ready");\n  logMetrics();\n}\n\nfunction logMetrics() {\n  const entries = performance.getEntriesByType("measure");\n  // Log name and duration\n}', hints:'["performance.getEntriesByType(measure)", "entry.duration is in milliseconds", "Also log LCP with PerformanceObserver"]', solutionExplanation:'User Timing marks and measures appear in DevTools Performance panel, making it easy to identify slow initialization paths.' },
  { lessonId:9, difficulty:'Easy', topic:'Performance', title:'Image Dimension Fix for CLS', problemStatement:'Write a function that takes an array of {src, alt, naturalWidth, naturalHeight} and generates <img> tags with explicit width, height, and aspect-ratio style — preventing layout shift.', examples:'<img width="1200" height="630" style="aspect-ratio:1200/630">', starterCodeJs:'function buildStableImages(images) {\n  return images.map(({ src, alt, naturalWidth, naturalHeight }) => {\n    return "";\n  }).join("");\n}', hints:'["width and height attributes on img", "aspect-ratio: w/h in style", "loading=lazy for below-fold images"]', solutionExplanation:'Width and height attributes let browsers reserve exact space before the image loads, preventing content from jumping.' },
  { lessonId:9, difficulty:'Medium', topic:'Performance', title:'Font Loading Optimisation', problemStatement:'Optimise web font loading: use preconnect to Google Fonts, add font-display:swap to prevent invisible text, and use font-face with a system font fallback to minimize FOIT.', examples:'preconnect + @font-face with font-display:swap', starterCodeJs:'function buildFontStrategy(fontName, fontUrl) {\n  const head = "";\n  const css = `\n    @font-face {\n      font-family: "${fontName}";\n      /* Your CSS here */\n    }\n  `;\n  return { head, css };\n}', hints:'["preconnect to fonts.googleapis.com and fonts.gstatic.com", "font-display:swap shows fallback while loading", "src: local() first (if user has it), then url()"]', solutionExplanation:'local() in @font-face checks if the user already has the font installed — avoiding a network request entirely.' },
  { lessonId:9, difficulty:'Hard', topic:'Performance', title:'PerformanceObserver for LCP', problemStatement:'Use PerformanceObserver to capture LCP, CLS, and FID metrics. Report them as an object when the page is about to unload. Log a warning if any metric exceeds the "Good" threshold.', examples:'LCP < 2500ms, CLS < 0.1, FID < 100ms', starterCodeJs:'const metrics = { lcp: null, cls: 0, fid: null };\n\nnew PerformanceObserver((list) => {\n  // Handle LCP\n}).observe({ type: "largest-contentful-paint", buffered: true });\n\nnew PerformanceObserver((list) => {\n  // Handle CLS\n}).observe({ type: "layout-shift", buffered: true });\n\nwindow.addEventListener("visibilitychange", () => {\n  if (document.visibilityState === "hidden") reportMetrics();\n});\n\nfunction reportMetrics() { console.log(metrics); }', hints:'["LCP: entry.startTime", "CLS: accumulate entry.value if !entry.hadRecentInput", "FID: entry.processingStart - entry.startTime"]', solutionExplanation:'visibilitychange is more reliable than unload for metric reporting — it fires before tab close/switch.' },
  { lessonId:9, difficulty:'Easy', topic:'Performance', title:'Preload Critical Resources', problemStatement:'Write a <head> snippet that preloads: a hero image (JPEG), the main CSS file, the app JS file, and a font file. Use correct rel="preload" with appropriate as and crossorigin attributes.', examples:'<link rel="preload" href="hero.jpg" as="image">', starterCodeJs:'function buildPreloads({ image, css, js, font }) {\n  return "";\n}', hints:'["as=image, as=style, as=script, as=font", "Fonts require crossorigin attribute", "type attribute is optional but helpful"]', solutionExplanation:'crossorigin on font preloads is required even for same-origin fonts because fonts are fetched with CORS anonymous mode.' },

  // Lesson 10: DOM Fundamentals
  { lessonId:10, difficulty:'Easy', topic:'DOM', title:'DOM Query Methods Comparison', problemStatement:'Write functions demonstrating all 5 query methods: getElementById, getElementsByClassName, getElementsByTagName, querySelector, querySelectorAll. Test each on a sample DOM structure.', examples:'All 5 methods with sample selectors', starterCodeJs:'// Given: <div id="app"><p class="text" data-id="1">Hello</p><p class="text">World</p></div>\n\nfunction queryById() { return document.getElementById("app"); }\nfunction queryByClass() { return document.getElementsByClassName("text"); }\nfunction queryByTag() { }\nfunction queryFirst() { }\nfunction queryAll() { }', hints:'["getElementsBy returns live HTMLCollection", "querySelectorAll returns static NodeList", "querySelector returns null if not found"]', solutionExplanation:'getElementsByClassName and getElementsByTagName return live HTMLCollections — they update as the DOM changes. querySelectorAll is static.' },
  { lessonId:10, difficulty:'Easy', topic:'DOM', title:'Create and Append Elements', problemStatement:'Write a function buildCard({title, description, tags}) that creates a DOM card element programmatically using createElement, textContent, className, and appendChild — returning the element.', examples:'Returns a div.card with h3, p, and tag spans inside', starterCodeJs:'function buildCard({ title, description, tags }) {\n  const card = document.createElement("div");\n  card.className = "card";\n  // Add title, description, and tags\n  return card;\n}', hints:'["createElement + textContent for safe text", "appendChild attaches child", "tags.forEach to create multiple spans"]', solutionExplanation:'Using textContent (not innerHTML) for user data prevents XSS. Build the element tree off-screen, then insert once.' },
  { lessonId:10, difficulty:'Medium', topic:'DOM', title:'Event Delegation', problemStatement:'Given a <ul> with 100 items that can be dynamically added, implement event delegation: attach ONE click listener to the <ul>, detect which <li> was clicked via event.target, and toggle a "selected" class on it.', examples:'One listener on <ul>, handles all <li> clicks', starterCodeJs:'function initList(ul) {\n  ul.addEventListener("click", (e) => {\n    const li = e.target.closest("li");\n    if (!li) return;\n    // Toggle selected class\n  });\n}\nfunction addItem(ul, text) {\n  const li = document.createElement("li");\n  li.textContent = text;\n  ul.appendChild(li);\n  // No new listener needed!\n}', hints:'["closest() traverses up to find the li", "Works for dynamically added items", "classList.toggle() for the class"]', solutionExplanation:'Delegation attaches one listener to a stable ancestor instead of N listeners on N children, and automatically handles dynamically added elements.' },
  { lessonId:10, difficulty:'Medium', topic:'DOM', title:'Custom Event System', problemStatement:'Implement a pub/sub event bus using the EventTarget API: subscribe(), publish(), and unsubscribe() methods. Demonstrate by wiring a form input to update a preview element.', examples:'bus.subscribe("input-change", handler); bus.publish("input-change", {value})', starterCodeJs:'const bus = new EventTarget();\n\nfunction subscribe(event, handler) {\n  bus.addEventListener(event, (e) => handler(e.detail));\n  return handler; // return for unsubscribe\n}\nfunction publish(event, data) {\n  bus.dispatchEvent(new CustomEvent(event, { detail: data }));\n}\nfunction unsubscribe(event, handler) {\n  bus.removeEventListener(event, handler);\n}', hints:'["CustomEvent passes data via detail property", "EventTarget works without DOM elements", "Store handler reference for removeEventListener"]', solutionExplanation:'EventTarget can be used standalone (not just on DOM elements) as a lightweight event bus — no external library needed.' },
  { lessonId:10, difficulty:'Medium', topic:'DOM', title:'DOM Diff and Update', problemStatement:'Write a function updateList(ul, newItems) that updates a <ul> to show newItems — adding missing items, removing stale ones, and updating changed text — without re-rendering the whole list.', examples:'Only modify what changed, not innerHTML = "..."', starterCodeJs:'function updateList(ul, newItems) {\n  const existing = new Map(\n    [...ul.querySelectorAll("li")].map(li => [li.dataset.id, li])\n  );\n  const newIds = new Set(newItems.map(i => i.id));\n  \n  // Remove items not in newItems\n  // Add items not in existing\n  // Update changed text\n}', hints:'["Use data-id attributes as keys", "Map.has() for O(1) lookup", "Avoid innerHTML = on the whole list"]', solutionExplanation:'Minimal DOM updates are faster than re-rendering — this is the core principle behind virtual DOM diffing in frameworks.' },
  { lessonId:10, difficulty:'Hard', topic:'DOM', title:'Infinite Scroll with IntersectionObserver', problemStatement:'Implement infinite scroll: show 10 items, place a sentinel element at the bottom, observe it with IntersectionObserver, and load 10 more items when it enters the viewport. Show a loading spinner during fetch.', examples:'Sentinel: a div at the bottom of the list', starterCodeJs:'let page = 1;\nconst sentinel = document.getElementById("sentinel");\n\nasync function loadMore() {\n  // Show spinner\n  // Fake fetch: await new Promise(r => setTimeout(r, 500))\n  // Append items\n  // Hide spinner\n}\n\nconst observer = new IntersectionObserver(async ([entry]) => {\n  if (entry.isIntersecting) await loadMore();\n});\nobserver.observe(sentinel);', hints:'["Disconnect observer during load to prevent double-fetch", "Move sentinel after appending new items", "Show/hide spinner div"]', solutionExplanation:'Disconnect the observer before loading and re-observe after to prevent multiple simultaneous fetches when the sentinel is visible.' },
  { lessonId:10, difficulty:'Hard', topic:'DOM', title:'Virtual List (Windowing)', problemStatement:'Implement a virtual list that renders only the visible rows of a 10,000-item list. Calculate which items are visible based on scrollTop, itemHeight, and containerHeight. Update on scroll.', examples:'Only 20 items in DOM at a time out of 10,000', starterCodeJs:'function initVirtualList(container, items, itemHeight) {\n  const total = items.length;\n  container.style.position = "relative";\n  container.style.height = total * itemHeight + "px";\n  \n  const viewport = document.createElement("div");\n  viewport.style.position = "absolute";\n  container.appendChild(viewport);\n  \n  function render() {\n    const scrollTop = container.scrollTop;\n    const startIdx = Math.floor(scrollTop / itemHeight);\n    const visibleCount = Math.ceil(container.clientHeight / itemHeight) + 2;\n    // Render items from startIdx to startIdx + visibleCount\n  }\n  container.addEventListener("scroll", render);\n  render();\n}', hints:'["Set total height on outer container for correct scrollbar", "Translate visible rows: transform: translateY(startIdx * itemHeight)", "Buffer 2 rows above/below viewport"]', solutionExplanation:'Windowing maintains a fixed-size DOM regardless of data size, enabling smooth scrolling through millions of rows.' },
  { lessonId:10, difficulty:'Hard', topic:'DOM', title:'Undo/Redo with Command Pattern', problemStatement:'Implement undo/redo for a text editor using the Command pattern. Each edit creates a Command object with execute() and undo() methods. Maintain undo/redo stacks limited to 50 steps.', examples:'undoStack.push(cmd); cmd.execute(); redoStack.clear()', starterCodeJs:'const undoStack = [];\nconst redoStack = [];\n\nfunction execute(command) {\n  command.execute();\n  undoStack.push(command);\n  if (undoStack.length > 50) undoStack.shift();\n  redoStack.length = 0;\n}\n\nfunction undo() {\n  const cmd = undoStack.pop();\n  if (!cmd) return;\n  cmd.undo();\n  redoStack.push(cmd);\n}\n\nfunction redo() {\n  const cmd = redoStack.pop();\n  if (!cmd) return;\n  cmd.execute();\n  undoStack.push(cmd);\n}\n\n// Example Command:\nfunction TextInsertCommand(input, text, pos) {\n  return {\n    execute() { /* insert text at pos */ },\n    undo() { /* remove text */ }\n  };\n}', hints:'["Commands are objects with execute/undo", "Executing clears redoStack", "Shift oldest item when stack exceeds 50"]', solutionExplanation:'Clearing redoStack on new command prevents a branching undo history — a design decision made by most editors.' },
  { lessonId:10, difficulty:'Easy', topic:'DOM', title:'Form Serializer', problemStatement:'Write serializeForm(form) that returns a plain object of all named form field values. Handle text inputs, checkboxes (boolean), radio groups, select dropdowns, and multiple-select (array).', examples:'{username:"alice", agree:true, langs:["js","python"]}', starterCodeJs:'function serializeForm(form) {\n  const data = {};\n  const fd = new FormData(form);\n  for (const [key, value] of fd.entries()) {\n    if (data[key] !== undefined) {\n      data[key] = [].concat(data[key], value);\n    } else {\n      data[key] = value;\n    }\n  }\n  // Convert checkbox values to booleans\n  return data;\n}', hints:'["FormData handles most cases", "fd.getAll(key) for multi-select", "Checkbox: value is on/undefined", "JSON.stringify(new FormData(form)) does not work"]', solutionExplanation:'FormData.getAll() collects all values for a key (multiple selects, checkbox groups). Unchecked checkboxes are absent from FormData entirely.' },
  { lessonId:10, difficulty:'Medium', topic:'DOM', title:'DOM Observer Debugger', problemStatement:'Build a DevTools-like DOM change logger: use MutationObserver to watch the body, log every added/removed node, changed attribute, and text content change with a timestamp and path to the node.', examples:'"[12:34:05] Added: div.card → body > main > .list"', starterCodeJs:'function getNodePath(node) {\n  const path = [];\n  while (node && node !== document.body) {\n    let selector = node.tagName?.toLowerCase() || "";\n    if (node.id) selector += "#" + node.id;\n    else if (node.className) selector += "." + node.className.split(" ")[0];\n    path.unshift(selector);\n    node = node.parentNode;\n  }\n  return "body > " + path.join(" > ");\n}\n\nfunction initDOMLogger() {\n  const observer = new MutationObserver((mutations) => {\n    // Log each mutation type\n  });\n  observer.observe(document.body, {\n    childList: true, subtree: true,\n    attributes: true, characterData: true\n  });\n}', hints:'["mutation.type: childList, attributes, characterData", "mutation.addedNodes/removedNodes for childList", "mutation.attributeName for attribute changes"]', solutionExplanation:'characterData=true observes text node changes. subtree=true makes the observer watch all descendants, not just direct children.' },
]

async function main() {
  console.log('Seeding lessons 6-10 quiz + coding questions...')
  for (const q of quiz) {
    const exists = await p.quizQuestion.findFirst({ where: { lessonId: q.lessonId, question: q.question } })
    if (!exists) await p.quizQuestion.create({ data: q })
  }
  console.log(`✓ ${quiz.length} quiz questions inserted`)
  for (const q of coding) {
    const exists = await p.practiceQuestion.findFirst({ where: { lessonId: q.lessonId, title: q.title } })
    if (!exists) await p.practiceQuestion.create({ data: q })
  }
  console.log(`✓ ${coding.length} coding questions inserted`)
}
main().catch(console.error).finally(() => p.$disconnect())
