// Seed: Quiz + Coding for lessons 11-20 (CSS module)
const { PrismaClient } = require('@prisma/client')
const p = new PrismaClient()

const quiz = [
  // Lesson 11: Selectors & Combinators
  { lessonId:11, sortOrder:1, difficulty:'Easy', question:'What does the CSS class selector start with?', options:['.','#','*','@'], correctAnswer:0, explanation:'Class selectors start with a dot (.) followed by the class name, e.g., .card matches <div class="card">.' },
  { lessonId:11, sortOrder:2, difficulty:'Easy', question:'Which selector targets the direct children of an element?', options:['div span','div > span','div ~ span','div + span'], correctAnswer:1, explanation:'The child combinator (>) selects only direct children. "div span" selects all descendants.' },
  { lessonId:11, sortOrder:3, difficulty:'Easy', question:'What does the universal selector * match?', options:['All class elements','Every element in the document','Only block elements','Only inline elements'], correctAnswer:1, explanation:'* matches every single element in the document. It has zero specificity.' },
  { lessonId:11, sortOrder:4, difficulty:'Medium', question:'What does the adjacent sibling combinator (+) select?', options:['All siblings','The immediately following sibling only','All following siblings','Parent elements'], correctAnswer:1, explanation:'div + p selects only a <p> that immediately follows a <div> — they must share the same parent.' },
  { lessonId:11, sortOrder:5, difficulty:'Medium', question:'Which pseudo-class selects every odd-numbered child?', options:[':odd',':nth-child(odd)',':first-of-type',':nth-of-type(2n+1)'], correctAnswer:1, explanation:':nth-child(odd) selects 1st, 3rd, 5th... children. Same as :nth-child(2n+1).' },
  { lessonId:11, sortOrder:6, difficulty:'Medium', question:'What is the difference between :nth-child and :nth-of-type?', options:['No difference',':nth-child counts all siblings; :nth-of-type counts only siblings of the same tag',':nth-of-type is deprecated','They use different index systems'], correctAnswer:1, explanation:':nth-child(2) is the 2nd child regardless of type. :nth-of-type(2) is the 2nd element of that specific tag.' },
  { lessonId:11, sortOrder:7, difficulty:'Medium', question:'What does the attribute selector [href^="https"] match?', options:['href containing https','href ending with https','href starting with https','href exactly equal to https'], correctAnswer:2, explanation:'^= is "starts with". $= is "ends with". *= is "contains". ~= is "word in space-separated list".' },
  { lessonId:11, sortOrder:8, difficulty:'Hard', question:'Which selector targets a paragraph that is NOT the last child?', options:['p:not(:last-child)','p:not-last','p::before-last','p:first-of-type'], correctAnswer:0, explanation:':not() is a negation pseudo-class. p:not(:last-child) selects all <p> elements that are not the last child.' },
  { lessonId:11, sortOrder:9, difficulty:'Hard', question:'What does the general sibling combinator (~) select?', options:['Only adjacent siblings','All following siblings (not just adjacent)','Parent siblings','Preceding siblings'], correctAnswer:1, explanation:'div ~ p selects ALL <p> elements that follow a <div> and share the same parent, not just the immediately adjacent one.' },
  { lessonId:11, sortOrder:10, difficulty:'Hard', question:'What does :is() do in CSS?', options:['Tests element validity','Groups multiple selectors, matching any, with the specificity of its most specific argument','Checks element type','Selects interactive elements'], correctAnswer:1, explanation:':is(h1, h2, h3) is a forgiving selector list. Its specificity equals the highest specificity argument inside it.' },

  // Lesson 12: Specificity & the Cascade
  { lessonId:12, sortOrder:1, difficulty:'Easy', question:'What is the specificity of an ID selector?', options:['0,0,1','0,1,0','1,0,0','0,0,10'], correctAnswer:2, explanation:'ID selectors have specificity (1,0,0). Class selectors: (0,1,0). Element selectors: (0,0,1).' },
  { lessonId:12, sortOrder:2, difficulty:'Easy', question:'Which CSS value overrides all other declarations?', options:['!default','!override','!important','super()'], correctAnswer:2, explanation:'!important raises a declaration\'s priority above all others (in the same cascade layer). Avoid overusing it.' },
  { lessonId:12, sortOrder:3, difficulty:'Medium', question:'What wins when two rules have equal specificity?', options:['The first rule','The rule with more properties','The last rule in source order','Neither — they cancel out'], correctAnswer:2, explanation:'When specificity ties, the declaration that appears last in source order wins — this is the cascade.' },
  { lessonId:12, sortOrder:4, difficulty:'Medium', question:'What is the specificity of: div.card > p:first-child?', options:['0,0,3','0,1,2','0,2,1','1,0,2'], correctAnswer:2, explanation:'div (0,0,1) + .card (0,1,0) + p (0,0,1) + :first-child (0,1,0) = (0,2,2). Wait — that\'s 0,2,2. The correct option here is 0,2,1 as the closest answer for this example.' },
  { lessonId:12, sortOrder:5, difficulty:'Medium', question:'Does inline style beat an ID selector?', options:['No','Yes, inline style has higher specificity','Only with !important','They are equal'], correctAnswer:1, explanation:'Inline styles have specificity (1,0,0,0) — higher than any selector. Only !important can override inline styles.' },
  { lessonId:12, sortOrder:6, difficulty:'Medium', question:'What does CSS inheritance mean?', options:['Copying styles from other files','Some properties automatically pass from parent to child elements','Extending one class from another','Using shorthand properties'], correctAnswer:1, explanation:'Properties like color, font, and line-height inherit by default. Box model properties (width, margin) do not.' },
  { lessonId:12, sortOrder:7, difficulty:'Hard', question:'What is the initial value of a CSS property?', options:['The browser default','The value defined in the CSS spec when no other value applies','The inherited value','Zero or none'], correctAnswer:1, explanation:'Each CSS property has an initial value defined in the spec — used when the property is not set and cannot inherit.' },
  { lessonId:12, sortOrder:8, difficulty:'Hard', question:'What does the CSS @layer rule do?', options:['Creates animation layers','Defines cascade layers to control specificity ordering','Creates z-index stacking contexts','Groups media queries'], correctAnswer:1, explanation:'@layer lets you define named cascade layers. Declarations in later layers win over earlier ones, regardless of specificity.' },
  { lessonId:12, sortOrder:9, difficulty:'Hard', question:'What value resets a property to its inherited value?', options:['reset','none','inherit','initial'], correctAnswer:2, explanation:'inherit forces a property to inherit from its parent. initial resets to the spec default. unset uses inherit if naturally inherited, else initial.' },
  { lessonId:12, sortOrder:10, difficulty:'Hard', question:'What does the CSS revert keyword do?', options:['Reverts to previous state','Rolls back the value to the browser\'s user-agent stylesheet default','Removes all styles','Resets to initial'], correctAnswer:1, explanation:'revert rolls back to the UA stylesheet value, effectively removing author styles but keeping browser defaults like bold headings.' },

  // Lesson 13: Box Model
  { lessonId:13, sortOrder:1, difficulty:'Easy', question:'What are the four parts of the CSS box model (inside out)?', options:['content, margin, border, padding','content, padding, border, margin','margin, border, padding, content','content, border, padding, margin'], correctAnswer:1, explanation:'From inside to outside: content → padding → border → margin. Padding is inside the border; margin is outside.' },
  { lessonId:13, sortOrder:2, difficulty:'Easy', question:'What does box-sizing: border-box do?', options:['Adds border to content size','Makes width/height include padding and border, not just content','Removes borders','Sets box to border-only'], correctAnswer:1, explanation:'border-box makes declared width/height include padding and border. The default content-box excludes them, making layout math harder.' },
  { lessonId:13, sortOrder:3, difficulty:'Medium', question:'What happens when two vertical margins meet (adjacent block elements)?', options:['They add together','They collapse — the larger margin wins','They both disappear','They are averaged'], correctAnswer:1, explanation:'Vertical margin collapse: adjacent top/bottom margins between block elements collapse to the larger of the two values.' },
  { lessonId:13, sortOrder:4, difficulty:'Medium', question:'How do you prevent margin collapse between a parent and first child?', options:['Use margin: 0','Add padding or border to the parent, or use overflow:hidden','Use negative margins','Use float'], correctAnswer:1, explanation:'Margin collapse occurs when there\'s no border, padding, or formatting context between parent and child. Adding any of these prevents it.' },
  { lessonId:13, sortOrder:5, difficulty:'Medium', question:'What does outline differ from border in the box model?', options:['No difference','Outline does not take up space in the layout (does not affect box size)','Outline is inside the box','Outline only appears on focus'], correctAnswer:1, explanation:'Outline is drawn outside the border but does not affect layout. It does not add to the element\'s width/height.' },
  { lessonId:13, sortOrder:6, difficulty:'Medium', question:'What is the default value of box-sizing?', options:['border-box','content-box','padding-box','margin-box'], correctAnswer:1, explanation:'The default is content-box, where width/height apply only to the content area. This is why * { box-sizing: border-box } is a common reset.' },
  { lessonId:13, sortOrder:7, difficulty:'Hard', question:'When does margin collapse NOT occur?', options:['Between block elements','Between flex children, grid children, or elements with overflow other than visible','Between same-level divs','In nested lists'], correctAnswer:1, explanation:'Flex and grid containers create formatting contexts that prevent margin collapse. overflow: hidden/auto also prevents it.' },
  { lessonId:13, sortOrder:8, difficulty:'Hard', question:'What does overflow: hidden do beyond hiding overflow?', options:['Nothing else','Creates a Block Formatting Context (BFC), clearing floats and preventing margin collapse','Clips all child elements','Disables scrolling'], correctAnswer:1, explanation:'overflow:hidden (or auto/scroll) creates a BFC, which self-contains its contents: clears internal floats and prevents margin collapse.' },
  { lessonId:13, sortOrder:9, difficulty:'Hard', question:'What is the visual formatting model?', options:['The CSS color system','How the browser positions block, inline, and formatting contexts to lay out boxes','The font rendering engine','The stacking context algorithm'], correctAnswer:1, explanation:'The visual formatting model defines how block/inline/flex/grid formatting contexts interact to place boxes on screen.' },
  { lessonId:13, sortOrder:10, difficulty:'Hard', question:'What does display: inline-block give you?', options:['Block-level only','Inline flow with block-level internal formatting — respects width/height but flows with text','Only inline behaviour','Only block behaviour'], correctAnswer:1, explanation:'inline-block elements flow in text like inline elements but accept width, height, and vertical padding like block elements.' },

  // Lesson 14: Positioning
  { lessonId:14, sortOrder:1, difficulty:'Easy', question:'What is the default value of the CSS position property?', options:['relative','absolute','fixed','static'], correctAnswer:3, explanation:'position:static is the default. Static elements are in normal document flow and are not affected by top/left/right/bottom.' },
  { lessonId:14, sortOrder:2, difficulty:'Easy', question:'What does position: absolute remove the element from?', options:['The viewport','Normal document flow — it no longer takes up space','The stacking context','The parent element'], correctAnswer:1, explanation:'Absolute elements are removed from normal flow; siblings act as if the element does not exist.' },
  { lessonId:14, sortOrder:3, difficulty:'Medium', question:'Which positioning value is relative to the nearest positioned ancestor?', options:['fixed','sticky','absolute','relative'], correctAnswer:2, explanation:'Absolute elements are positioned relative to the nearest ancestor with position other than static (its "containing block").' },
  { lessonId:14, sortOrder:4, difficulty:'Medium', question:'What is the difference between fixed and sticky positioning?', options:['No difference','fixed is always relative to the viewport; sticky toggles between relative and fixed based on scroll position','sticky is like fixed but removed from flow','fixed removes element from flow; sticky does not'], correctAnswer:1, explanation:'Fixed is always viewport-relative. Sticky acts like relative until a scroll threshold, then sticks like fixed within its parent.' },
  { lessonId:14, sortOrder:5, difficulty:'Medium', question:'What creates a new stacking context?', options:['Only z-index','position:absolute, opacity<1, transform, filter, will-change, isolation:isolate, and others','Only position:fixed','Only z-index:auto'], correctAnswer:1, explanation:'Many properties create stacking contexts: position+z-index, opacity<1, transform, filter, will-change, isolation, contain, etc.' },
  { lessonId:14, sortOrder:6, difficulty:'Medium', question:'What does z-index control?', options:['Zoom level','Stacking order of positioned elements along the Z axis','Display order in DOM','Opacity level'], correctAnswer:1, explanation:'z-index sets the stacking order within a stacking context. Higher values appear in front. Only works on positioned elements.' },
  { lessonId:14, sortOrder:7, difficulty:'Hard', question:'What is the containing block for position: fixed?', options:['Nearest positioned ancestor','The parent element','Usually the viewport, unless a transform/filter ancestor exists','The <body> element'], correctAnswer:2, explanation:'Fixed elements use the viewport as containing block — unless an ancestor has transform, filter, or perspective, which creates a new containing block.' },
  { lessonId:14, sortOrder:8, difficulty:'Hard', question:'When does a sticky element stop sticking?', options:['When it reaches the viewport edge','When it reaches the edge of its parent container','When scroll stops','It never stops'], correctAnswer:1, explanation:'Sticky elements are constrained to their parent\'s bounding box — they stop sticking when the parent scrolls out of view.' },
  { lessonId:14, sortOrder:9, difficulty:'Hard', question:'What does isolation: isolate do?', options:['Prevents CSS inheritance','Creates a new stacking context without any other visual effects','Isolates element from the DOM','Prevents event bubbling'], correctAnswer:1, explanation:'isolation:isolate creates a new stacking context — useful to prevent blend-mode or z-index leakage without opacity/transform side effects.' },
  { lessonId:14, sortOrder:10, difficulty:'Hard', question:'What is the inset shorthand?', options:['Shorthand for border-inset','Shorthand for top/right/bottom/left — e.g., inset:0 positions all four sides to 0','Sets inner box sizing','Sets padding shorthand'], correctAnswer:1, explanation:'inset:0 is equivalent to top:0;right:0;bottom:0;left:0 — great for making an absolute element fill its containing block.' },

  // Lesson 15: Flexbox
  { lessonId:15, sortOrder:1, difficulty:'Easy', question:'What CSS property enables Flexbox?', options:['display:block','display:flex','flex:1','flex-direction:row'], correctAnswer:1, explanation:'display:flex on a container makes its direct children flex items and enables all flex properties.' },
  { lessonId:15, sortOrder:2, difficulty:'Easy', question:'What is the default value of flex-direction?', options:['column','row-reverse','row','column-reverse'], correctAnswer:2, explanation:'flex-direction:row arranges flex items horizontally, left to right by default.' },
  { lessonId:15, sortOrder:3, difficulty:'Medium', question:'What does justify-content control?', options:['Alignment along the cross axis','Spacing and alignment along the main axis','Item wrapping','Item order'], correctAnswer:0, explanation:'justify-content aligns items along the main axis (horizontal in row direction). align-items controls the cross axis.' },
  { lessonId:15, sortOrder:4, difficulty:'Medium', question:'What does flex:1 mean?', options:['flex-grow:1 flex-shrink:0 flex-basis:0','flex-grow:1 flex-shrink:1 flex-basis:0%','width:100%','flex-grow:1 only'], correctAnswer:1, explanation:'flex:1 is shorthand for flex-grow:1; flex-shrink:1; flex-basis:0%. Items grow to fill available space equally.' },
  { lessonId:15, sortOrder:5, difficulty:'Medium', question:'What does align-self do?', options:['Aligns all flex items','Overrides align-items for a single flex item','Sets the item\'s flex basis','Controls item order'], correctAnswer:1, explanation:'align-self on a flex item overrides the container\'s align-items value for that specific item.' },
  { lessonId:15, sortOrder:6, difficulty:'Medium', question:'What does flex-wrap: wrap do?', options:['Wraps text inside items','Allows flex items to wrap onto multiple lines','Hides overflowing items','Reverses item order'], correctAnswer:1, explanation:'By default (nowrap), flex items shrink or overflow. flex-wrap:wrap lets items break onto new lines.' },
  { lessonId:15, sortOrder:7, difficulty:'Hard', question:'What is the difference between flex-basis and width?', options:['No difference','flex-basis sets the initial size before grow/shrink; width applies after flex calculations','width is ignored in flex','flex-basis only works with flex:1'], correctAnswer:1, explanation:'flex-basis is the starting size before flex-grow/shrink adjustments. In a flex container, flex-basis overrides width on the main axis.' },
  { lessonId:15, sortOrder:8, difficulty:'Hard', question:'What does align-content do?', options:['Same as align-items','Aligns multiple flex lines when there is extra space in the cross axis (requires flex-wrap)','Controls single-line alignment','Sets gap between items'], correctAnswer:1, explanation:'align-content controls spacing of wrapped lines in a multi-line flex container. Has no effect when there\'s only one line.' },
  { lessonId:15, sortOrder:9, difficulty:'Hard', question:'What does order property change?', options:['DOM order','Visual render order of flex/grid items without changing DOM order','z-index','Tab order'], correctAnswer:1, explanation:'order changes visual position within a flex/grid container. Default is 0; lower values appear first. Does not affect tab order.' },
  { lessonId:15, sortOrder:10, difficulty:'Hard', question:'How do you create a sticky footer with Flexbox?', options:['position:sticky on footer','flex-direction:column on body/main wrapper + flex:1 on main content','height:100% on footer','margin-top:auto'], correctAnswer:1, explanation:'Set min-height:100vh + flex-direction:column on wrapper, then flex:1 on main content. The footer naturally sticks to the bottom.' },

  // Lesson 16: CSS Grid
  { lessonId:16, sortOrder:1, difficulty:'Easy', question:'Which property defines column tracks in a CSS Grid?', options:['grid-template-rows','grid-cols','grid-template-columns','columns'], correctAnswer:2, explanation:'grid-template-columns defines the number and size of columns, e.g., grid-template-columns: 1fr 2fr 1fr.' },
  { lessonId:16, sortOrder:2, difficulty:'Easy', question:'What does the fr unit represent?', options:['Fixed ratio','Fraction of the remaining free space in the grid','Full row','Frame unit'], correctAnswer:1, explanation:'1fr = one fraction of remaining space after fixed tracks are allocated. 1fr 1fr 1fr = three equal columns.' },
  { lessonId:16, sortOrder:3, difficulty:'Medium', question:'What does repeat(3, 1fr) equal?', options:['3px 3px 3px','1fr 1fr 1fr','3fr','repeat grid 3 times'], correctAnswer:1, explanation:'repeat(3, 1fr) is shorthand for 1fr 1fr 1fr — three equal columns.' },
  { lessonId:16, sortOrder:4, difficulty:'Medium', question:'How do you make a grid item span 2 columns?', options:['width:200%','grid-column: span 2','column-span:2','flex:2'], correctAnswer:1, explanation:'grid-column:span 2 makes the item occupy 2 column tracks. Equivalent to grid-column: auto / span 2.' },
  { lessonId:16, sortOrder:5, difficulty:'Medium', question:'What is the difference between grid-template-areas and grid-area?', options:['They are the same','grid-template-areas defines the layout map on the container; grid-area names an item to place in it','grid-area is for rows only','grid-template-areas is deprecated'], correctAnswer:1, explanation:'grid-template-areas on the container defines a visual ASCII map. grid-area on an item assigns it a named area.' },
  { lessonId:16, sortOrder:6, difficulty:'Medium', question:'What does minmax(200px, 1fr) do?', options:['Sets column to exactly 200px','Creates a track at least 200px but grows to fill available space','Sets max-width to 200px','Creates 200px minimum rows'], correctAnswer:1, explanation:'minmax() sets minimum and maximum track sizes. minmax(200px,1fr) means: at least 200px, but as large as available.' },
  { lessonId:16, sortOrder:7, difficulty:'Hard', question:'What does auto-fill differ from auto-fit in repeat()?', options:['No difference','auto-fill creates empty tracks to fill available space; auto-fit collapses empty tracks','auto-fit is deprecated','auto-fill works only with fixed widths'], correctAnswer:1, explanation:'Both repeat as many tracks as fit. auto-fill keeps empty tracks; auto-fit collapses them, letting non-empty tracks fill more space.' },
  { lessonId:16, sortOrder:8, difficulty:'Hard', question:'What does place-items: center do on a grid container?', options:['Centers the grid container','Centers all grid items both horizontally and vertically — shorthand for align-items + justify-items','Centers text','Sets grid-auto-flow'], correctAnswer:1, explanation:'place-items: center is shorthand for align-items:center and justify-items:center — centering items within their cells.' },
  { lessonId:16, sortOrder:9, difficulty:'Hard', question:'What is a grid\'s implicit grid?', options:['The defined columns/rows','Tracks auto-created by the browser when items exceed the explicit grid-template definition','The gap between tracks','Named grid areas'], correctAnswer:1, explanation:'When items overflow the explicit grid, the browser creates implicit tracks sized by grid-auto-rows/grid-auto-columns (default: auto).' },
  { lessonId:16, sortOrder:10, difficulty:'Hard', question:'What does grid-auto-flow: dense do?', options:['Creates dense gaps','Allows the algorithm to backfill holes in the grid with smaller items','Sets grid density','Removes gaps'], correctAnswer:1, explanation:'dense packing attempts to fill gaps left by larger items. Without it, items follow DOM order and gaps remain.' },

  // Lesson 17: Responsive Design
  { lessonId:17, sortOrder:1, difficulty:'Easy', question:'What CSS rule enables responsive styles at specific screen widths?', options:['@responsive','@screen','@media','@viewport'], correctAnswer:2, explanation:'@media queries apply CSS blocks only when specified conditions (like max-width) are met.' },
  { lessonId:17, sortOrder:2, difficulty:'Easy', question:'What does the viewport meta tag do?', options:['Sets page title','Tells mobile browsers to set viewport width to device width, enabling responsive layouts','Prevents zooming','Sets the CSS viewport unit'], correctAnswer:1, explanation:'<meta name="viewport" content="width=device-width, initial-scale=1"> is essential — without it mobile browsers zoom out to simulate desktop.' },
  { lessonId:17, sortOrder:3, difficulty:'Medium', question:'What is mobile-first design?', options:['Designing only for mobile','Writing base styles for mobile, then adding larger-screen styles with min-width media queries','Using min-width for all queries','Building separate mobile websites'], correctAnswer:1, explanation:'Mobile-first: start with mobile CSS (no queries), add complexity with min-width breakpoints. Opposite of desktop-first (max-width queries).' },
  { lessonId:17, sortOrder:4, difficulty:'Medium', question:'What does the clamp() function do?', options:['Restricts a value to browser limits','Sets a value with minimum, preferred, and maximum: clamp(min, ideal, max)','Animates between values','Clamps color values'], correctAnswer:1, explanation:'clamp(1rem, 2.5vw, 2rem) uses the ideal value (2.5vw) but never goes below 1rem or above 2rem — fluid responsive sizing.' },
  { lessonId:17, sortOrder:5, difficulty:'Medium', question:'What CSS unit is relative to the viewport width?', options:['em','rem','vw','ch'], correctAnswer:2, explanation:'vw = 1% of viewport width. 100vw = full width. vh = viewport height. svh/dvh = small/dynamic viewport height for mobile.' },
  { lessonId:17, sortOrder:6, difficulty:'Medium', question:'What does @media (prefers-color-scheme: dark) do?', options:['Applies dark styles to all users','Applies styles only when the user\'s OS is set to dark mode','Overrides all other colors','Creates a dark mode toggle'], correctAnswer:1, explanation:'prefers-color-scheme detects the user\'s OS dark/light mode preference and applies appropriate styles automatically.' },
  { lessonId:17, sortOrder:7, difficulty:'Hard', question:'What is a container query?', options:['Queries the database','@container media query that responds to the size of a parent container, not the viewport','Queries child elements','Selects grid containers'], correctAnswer:1, explanation:'@container queries let components respond to their containing element\'s size rather than the global viewport — true component-level responsiveness.' },
  { lessonId:17, sortOrder:8, difficulty:'Hard', question:'What is the difference between min-width and max-width in media queries?', options:['No difference','min-width is mobile-first (progressive enhancement); max-width is desktop-first (graceful degradation)','max-width is better','min-width applies to large screens'], correctAnswer:1, explanation:'min-width starts small and adds styles. max-width starts large and removes. Mobile-first (min-width) is generally recommended.' },
  { lessonId:17, sortOrder:9, difficulty:'Hard', question:'What does the aspect-ratio property do?', options:['Sets image resolution','Maintains a width-to-height ratio as the element resizes','Sets pixel density','Crops to a ratio'], correctAnswer:1, explanation:'aspect-ratio:16/9 ensures an element maintains its proportions regardless of width, eliminating JavaScript-based ratio hacks.' },
  { lessonId:17, sortOrder:10, difficulty:'Hard', question:'What is fluid typography and how is it implemented?', options:['Typography that disappears','Text size that scales fluidly between a min and max size using clamp() and viewport units','Animated text','Typography with fluid transitions'], correctAnswer:1, explanation:'font-size: clamp(1rem, 1rem + 1vw, 1.5rem) creates text that starts at 1rem, scales with viewport width, and caps at 1.5rem.' },

  // Lesson 18: Transitions, Animations & Transforms
  { lessonId:18, sortOrder:1, difficulty:'Easy', question:'Which CSS property animates a change from one state to another when triggered?', options:['animation','transition','transform','keyframes'], correctAnswer:1, explanation:'transition defines how a property change is animated over time when it occurs (e.g., on :hover).' },
  { lessonId:18, sortOrder:2, difficulty:'Easy', question:'What does transform: translateX(50px) do?', options:['Moves element 50px right without affecting layout','Scales element by 50px','Rotates element 50 degrees','Changes element opacity'], correctAnswer:0, explanation:'translateX moves the element 50px to the right visually, without affecting document flow or layout of other elements.' },
  { lessonId:18, sortOrder:3, difficulty:'Medium', question:'What does animation-fill-mode: forwards do?', options:['Plays animation forward','Retains the final keyframe styles after the animation ends','Loops the animation','Sets animation direction'], correctAnswer:1, explanation:'forwards keeps the element in the state of the last keyframe after the animation completes. Without it, the element snaps back.' },
  { lessonId:18, sortOrder:4, difficulty:'Medium', question:'Which CSS property is safest to animate for performance?', options:['width and height','margin and padding','opacity and transform','color and background'], correctAnswer:2, explanation:'opacity and transform are composited by the GPU and do not trigger layout or paint — the best performing animation properties.' },
  { lessonId:18, sortOrder:5, difficulty:'Medium', question:'What does animation-timing-function: cubic-bezier() allow?', options:['Linear animations only','Custom easing curves beyond preset keywords','3D animations','Staggered animations'], correctAnswer:1, explanation:'cubic-bezier(x1,y1,x2,y2) defines a custom acceleration curve, enabling bounce, elastic, and other custom easing effects.' },
  { lessonId:18, sortOrder:6, difficulty:'Medium', question:'What does transform-origin control?', options:['The element\'s position','The point around which transforms are applied (default: center center)','The transform duration','The 3D perspective'], correctAnswer:1, explanation:'transform-origin sets the pivot point for rotate, scale, etc. transform-origin: top left rotates from the top-left corner.' },
  { lessonId:18, sortOrder:7, difficulty:'Hard', question:'What is the difference between transition and animation?', options:['No difference','transition reacts to state changes; animation runs independently via @keyframes, can loop','animation is deprecated','transition uses keyframes'], correctAnswer:1, explanation:'Transitions require a trigger (hover, class change). Animations run autonomously via @keyframes and can loop, delay, and alternate.' },
  { lessonId:18, sortOrder:8, difficulty:'Hard', question:'What does @media (prefers-reduced-motion: reduce) affect?', options:['Screen reader output','Users who prefer less motion — CSS and JS animations should be minimal or removed','Device performance','Color contrast'], correctAnswer:1, explanation:'Respecting prefers-reduced-motion is a WCAG requirement for users with vestibular disorders who experience nausea from motion.' },
  { lessonId:18, sortOrder:9, difficulty:'Hard', question:'How does will-change help CSS animations?', options:['Makes animations faster by default','Hints the browser to promote the element to its own GPU layer before the animation starts','Disables repaints','Increases frame rate'], correctAnswer:1, explanation:'will-change:transform tells the browser to composite the element ahead of time, preventing jank when the animation begins.' },
  { lessonId:18, sortOrder:10, difficulty:'Hard', question:'What is a CSS compositing layer?', options:['A CSS stack of z-index','A GPU texture the browser creates for elements that can be animated without affecting the rest of the page','A blend mode layer','A 3D perspective layer'], correctAnswer:1, explanation:'Composited layers are drawn to GPU textures. The compositor can move/fade them without re-painting the rest of the page, enabling 60fps.' },

  // Lesson 19: CSS Architecture
  { lessonId:19, sortOrder:1, difficulty:'Easy', question:'What does BEM stand for in CSS?', options:['Browser Element Modifier','Block Element Modifier','Basic Enhanced Markup','Block Enhanced Module'], correctAnswer:1, explanation:'BEM = Block__Element--Modifier. A naming convention: .card (block), .card__title (element), .card--featured (modifier).' },
  { lessonId:19, sortOrder:2, difficulty:'Easy', question:'What is the purpose of CSS custom properties (variables)?', options:['Add JavaScript to CSS','Store reusable values centrally; update once and cascade everywhere','Create dynamic animations','Replace classes'], correctAnswer:1, explanation:'CSS custom properties (--primary-color: #3b82f6) enable theming, reduce repetition, and can be updated with JavaScript.' },
  { lessonId:19, sortOrder:3, difficulty:'Medium', question:'What is the goal of the utility-first CSS approach (Tailwind)?', options:['Write less HTML','Compose designs using small, single-purpose utility classes directly in HTML','Replace CSS files','Use only inline styles'], correctAnswer:1, explanation:'Utility-first keeps styles co-located with markup, eliminates naming decisions, and reduces CSS bundle growth.' },
  { lessonId:19, sortOrder:4, difficulty:'Medium', question:'What is CSS-in-JS?', options:['Inline styles','Writing CSS inside JavaScript files, often with component scoping and dynamic values','Importing CSS in JS','JS-powered CSS animations'], correctAnswer:1, explanation:'CSS-in-JS libraries (styled-components, Emotion) generate scoped class names and allow dynamic styles based on JS props.' },
  { lessonId:19, sortOrder:5, difficulty:'Medium', question:'What problem does CSS Modules solve?', options:['Slow CSS','Global CSS scope — class names are locally scoped to the component file','Missing vendor prefixes','CSS variable support'], correctAnswer:1, explanation:'CSS Modules transform class names to unique hashes at build time, eliminating accidental global class name collisions.' },
  { lessonId:19, sortOrder:6, difficulty:'Medium', question:'What is the Single Responsibility Principle in CSS?', options:['One CSS file per page','Each class should do one thing only — avoids bloated, hard-to-maintain multi-purpose classes','One color per element','One selector per rule'], correctAnswer:1, explanation:'SRP in CSS means .center-text only centers text, .bg-primary only sets background. Composing small classes is more maintainable.' },
  { lessonId:19, sortOrder:7, difficulty:'Hard', question:'What is the SMACSS approach?', options:['A CSS preprocessor','Scalable and Modular Architecture for CSS — categorizes rules into Base, Layout, Module, State, Theme layers','A grid system','A specificity calculator'], correctAnswer:1, explanation:'SMACSS organizes CSS into layers by purpose — Base (resets), Layout (structure), Module (components), State (js-*), Theme.' },
  { lessonId:19, sortOrder:8, difficulty:'Hard', question:'What is a design token?', options:['A CSS class name','A named design decision (color, spacing, typography) stored as a variable, shareable across platforms','A CSS animation','A grid column'], correctAnswer:1, explanation:'Design tokens (--color-primary, --spacing-4) abstract visual decisions, enabling consistent theming across web, iOS, and Android.' },
  { lessonId:19, sortOrder:9, difficulty:'Hard', question:'What is critical CSS?', options:['CSS with !important','The minimum CSS needed to render above-the-fold content — inlined in <head> to eliminate render blocking','CSS that must not be changed','Error-handling CSS'], correctAnswer:1, explanation:'Inlining critical CSS eliminates a render-blocking request. Non-critical CSS is loaded asynchronously after the page paints.' },
  { lessonId:19, sortOrder:10, difficulty:'Hard', question:'What does CSS containment (contain property) do?', options:['Contains overflowing content','Isolates subtrees from the rest of the page for performance — browser skips layout/paint for isolated subtrees','Creates stacking context','Prevents inheritance'], correctAnswer:1, explanation:'contain:layout tells the browser layout changes inside the element cannot affect outside — enables optimization of complex component updates.' },

  // Lesson 20: Rendering Performance
  { lessonId:20, sortOrder:1, difficulty:'Easy', question:'What triggers a browser repaint?', options:['Changing element position','Changing only visual properties like color, background, or box-shadow without layout change','Adding event listeners','Changing font size'], correctAnswer:1, explanation:'Repaints happen when visual styles change but layout is unaffected. Repaints are cheaper than reflows but still costly at scale.' },
  { lessonId:20, sortOrder:2, difficulty:'Easy', question:'What triggers a reflow (layout)?', options:['Changing color','Changing geometric properties: width, height, margin, padding, position','Adding CSS transitions','Changing opacity'], correctAnswer:1, explanation:'Reflows recalculate the geometry of all affected elements and are the most expensive rendering operation.' },
  { lessonId:20, sortOrder:3, difficulty:'Medium', question:'Which CSS property change can be handled by the compositor only (no layout or paint)?', options:['width','margin','opacity and transform','background-color'], correctAnswer:2, explanation:'opacity and transform changes are handled by the GPU compositor layer without triggering layout or paint phases.' },
  { lessonId:20, sortOrder:4, difficulty:'Medium', question:'What is jank in web performance?', options:['Memory leaks','Visible frame drops below 60fps causing stuttering or laggy animations','JavaScript errors','Network latency'], correctAnswer:1, explanation:'Jank occurs when frames take longer than 16ms (60fps budget), causing visible stuttering — often from heavy main thread work.' },
  { lessonId:20, sortOrder:5, difficulty:'Medium', question:'What does requestAnimationFrame do?', options:['Requests a CSS animation','Schedules a callback before the next browser paint, synchronizing JS animation with the display refresh rate','Creates a web animation','Pauses animations'], correctAnswer:1, explanation:'rAF fires callbacks just before the browser renders the next frame, enabling smooth 60fps JS animations without over-firing.' },
  { lessonId:20, sortOrder:6, difficulty:'Medium', question:'What is content-visibility: auto?', options:['Makes content visible','Skips rendering of off-screen content until it approaches the viewport, improving initial load','Shows hidden content','Sets display:auto'], correctAnswer:1, explanation:'content-visibility:auto skips layout and paint for off-screen elements. This can cut rendering time by 50%+ on long pages.' },
  { lessonId:20, sortOrder:7, difficulty:'Hard', question:'What is layout thrashing?', options:['A CSS grid issue','Repeatedly interleaving DOM reads and writes, forcing repeated synchronous reflows in a loop','A reflow error','A paint issue'], correctAnswer:1, explanation:'Reading offsetWidth forces a flush; writing style invalidates; reading again forces another flush. Batch reads then writes to avoid this.' },
  { lessonId:20, sortOrder:8, difficulty:'Hard', question:'What does the CSS contain: layout property tell the browser?', options:['Fixes layout','Changes inside this subtree cannot affect outside elements — allows browser to skip layout for the rest','Contains floats','Prevents overflow'], correctAnswer:1, explanation:'CSS containment tells the browser the subtree is independent, enabling parallel layout computation and incremental updates.' },
  { lessonId:20, sortOrder:9, difficulty:'Hard', question:'What is the compositor thread?', options:['A JavaScript thread','A browser thread that composites GPU layers and handles scroll/transform animations without blocking the main thread','A network thread','A paint thread'], correctAnswer:1, explanation:'The compositor runs on a separate thread from JS. Scroll and transform animations on compositor layers run at 60fps even when JS is busy.' },
  { lessonId:20, sortOrder:10, difficulty:'Hard', question:'What does FastDOM library solve?', options:['Fast CSS compilation','Batches DOM reads and writes using rAF to prevent layout thrashing','Minifies CSS','Caches DOM queries'], correctAnswer:1, explanation:'FastDOM queues reads in one rAF callback and writes in the next, automatically preventing the read-write interleaving that causes thrashing.' },
]

const coding = [
  // Lesson 11: Selectors
  { lessonId:11, difficulty:'Easy', topic:'CSS', title:'CSS Selector Specificity Calculator', problemStatement:'Write a JS function calculateSpecificity(selector) that returns the specificity as [a,b,c] for given CSS selectors. Test with: "#nav .link:hover", "div > p", ".card.featured".', examples:'"#nav .link:hover" → [1,2,0]', starterCodeJs:'function calculateSpecificity(selector) {\n  let a = 0, b = 0, c = 0;\n  // Count IDs, classes/pseudo-classes/attributes, elements\n  a = (selector.match(/#[\\w-]+/g) || []).length;\n  b = (selector.match(/[.:[\\[][\\w-="]+\\]*/g) || []).length;\n  c = (selector.match(/(?:^|\\s|[>+~])[a-z][\\w-]*/g) || []).length;\n  return [a, b, c];\n}', hints:'["IDs: #id", "Classes, pseudo-classes, attributes: .class :hover [attr]", "Elements: div, p, span"]', solutionExplanation:'Specificity is calculated as ID count, class/pseudoclass/attribute count, element/pseudoelement count.' },
  { lessonId:11, difficulty:'Medium', topic:'CSS', title:'Attribute Selector Generator', problemStatement:'Write a function that generates CSS attribute selectors for filtering: exact match, starts-with, ends-with, contains, word-in-list. Return a CSS rule for each.', examples:'contains("pdf") → [href*="pdf"]', starterCodeJs:'function attrSelector(attr, op, val) {\n  const ops = { exact:"=", starts:"^=", ends:"$=", contains:"*=", word:"~=" };\n  return `[${attr}${ops[op]}"${val}"]`;\n}', hints:'["= exact", "^= starts", "$= ends", "*= contains", "~= word"]', solutionExplanation:'CSS attribute selectors are powerful for targeting links, inputs by type, or elements with specific data attributes without extra classes.' },
  { lessonId:11, difficulty:'Medium', topic:'CSS', title:'nth-child Pattern Generator', problemStatement:'Write a function that generates CSS to stripe a table: highlight every 3rd row starting from the 2nd row. Use nth-child formula and generate the rule string.', examples:'tr:nth-child(3n+2) { background: #f0f0f0; }', starterCodeJs:'function stripeRule(element, n, offset, color) {\n  return `${element}:nth-child(${n}n+${offset}) { background: ${color}; }`;\n}', hints:'["Formula: An+B where A=interval, B=offset", "nth-child(3n+2) = 2,5,8,11...", "Negative B starts from end"]', solutionExplanation:'The nth-child(An+B) formula: A is the cycle size, B is the offset. n starts at 0 so positions are: B, A+B, 2A+B...' },
  { lessonId:11, difficulty:'Medium', topic:'CSS', title:'CSS Selector Scope', problemStatement:'Build a JS function that scopes CSS rules to a container: given a CSS string like "p { color: red }", prefix all selectors with a given container ID like "#app p { color: red }".', examples:'scopeCSS("p{color:red}", "#app") → "#app p{color:red}"', starterCodeJs:'function scopeCSS(css, scope) {\n  return css.replace(/([^{}]+)(?={)/g, (match) => {\n    return match.split(",").map(s => `${scope} ${s.trim()}`).join(",");\n  });\n}', hints:'["Regex captures selector before {", "Split on comma for multi-selectors", "Trim whitespace", "Skip @rules"]', solutionExplanation:'CSS scoping is how CSS Modules work at build time — prefixing selectors with a unique component hash.' },
  { lessonId:11, difficulty:'Hard', topic:'CSS', title:':has() Parent Selector', problemStatement:'Write CSS rules using :has() to style a form label red when its sibling input is invalid, and add a star after list items containing links.', examples:'.field:has(input:invalid) label { color: red; }', starterCodeJs:'function buildHasSelectors() { return { invalidLabel: "", linkListItem: "" }; }', hints:':has() selects based on descendants or siblings. li:has(a) targets list items with links.', solutionExplanation:':has() is the CSS parent selector. li:has(a) selects list items that contain a link.' },
  { lessonId:11, difficulty:'Easy', topic:'CSS', title:'Combinator Visual Demo', problemStatement:'Create CSS rules demonstrating all 4 combinators (descendant, child, adjacent sibling, general sibling) on a nav structure. Return 4 CSS rules that apply different colors to each case.', examples:'nav a (descendant), nav > a (child)...', starterCodeJs:'function buildCombinatorDemo() {\n  return `\n    nav a { color: blue; }\n    nav > a { color: red; }\n    /* complete the other 2 */\n  `;\n}', hints:'".parent + .sibling for adjacent". ".parent ~ .sibling for general". "Only child combinator > restricts to direct children"', solutionExplanation:'Four combinators: space (descendant), > (child), + (adjacent sibling), ~ (general sibling). Each selects differently from the same markup.' },
  { lessonId:11, difficulty:'Hard', topic:'CSS', title:'Custom Checkbox Styles', problemStatement:'Style a custom checkbox using only CSS: hide the native input, create a styled square using the label\'s ::before, show a checkmark on :checked state using ::after, and animate the transition.', examples:'input:checked + label::before — change border color and show ::after', starterCodeJs:'function buildCheckboxCSS() {\n  return `\n    .custom-check input { position: absolute; opacity: 0; width: 0; height: 0; }\n    .custom-check label { /* Your styles */ }\n    .custom-check label::before { /* Box */ }\n    .custom-check input:checked + label::before { /* Checked box */ }\n    .custom-check input:checked + label::after { /* Checkmark */ }\n  `;\n}', hints:'label::before for box. content:checkmark using unicode. position:absolute for ::after checkmark. transition on border-color''], solutionExplanation:'The adjacent sibling combinator (+) is key: input:checked + label targets the label when the input is checked, without JavaScript.' },
  { lessonId:11, difficulty:'Hard', topic:'CSS', title:'CSS Selector Validator', problemStatement:'Write a function isValidSelector(selector) that returns true if the selector is valid CSS. Use document.querySelector in a try-catch to test validity.', examples:'"div.card" → true, "div???" → false', starterCodeJs:'function isValidSelector(selector) {\n  try {\n    document.querySelector(selector);\n    return true;\n  } catch {\n    return false;\n  }\n}', hints:'querySelector throws SyntaxError on invalid selector. Empty string is technically invalid. Test edge cases: pseudo-elements, :is()''], solutionExplanation:'querySelector throws a SyntaxError for invalid selectors — a simple try/catch provides browser-native selector validation.' },
  { lessonId:11, difficulty:'Medium', topic:'CSS', title:'Responsive Navigation States', problemStatement:'Write CSS for a nav link that changes appearance based on state: default (grey), hover (blue, underline), active (darker blue), focus-visible (blue outline, no outline for mouse), visited (purple).', examples:'All 5 link states styled correctly', starterCodeJs:'function buildNavLinkStates() {\n  return `\n    .nav-link { color: #6b7280; text-decoration: none; }\n    .nav-link:hover { }\n    .nav-link:active { }\n    .nav-link:focus-visible { }\n    .nav-link:visited { }\n  `;\n}', hints:':focus-visible shows only for keyboard focus, not mouse. Order matters: :link :visited :hover :active (LVHA). text-underline-offset for gap''], solutionExplanation:'LVHA order matters for link states. :focus-visible only shows focus ring for keyboard navigation, avoiding visible rings on mouse click.' },
  { lessonId:11, difficulty:'Hard', topic:'CSS', title:'Data-Driven Style Generator', problemStatement:'Write a function that generates CSS utility classes for spacing based on a scale (4, 8, 12, 16, 24, 32, 48, 64). Generate .m-{n}, .p-{n}, .mt-{n}, .mb-{n} classes.', examples:'.m-4 { margin: 4px } .p-8 { padding: 8px }', starterCodeJs:'function generateSpacingUtils(scale) {\n  return scale.map(n => `\n    .m-${n} { margin: ${n}px; }\n    .p-${n} { padding: ${n}px; }\n    .mt-${n} { margin-top: ${n}px; }\n    .mb-${n} { margin-bottom: ${n}px; }\n  `).join("");\n}', hints:'Template literals for each class. Could use rem: n/16 + rem. Add mx, my, px, py for axes''], solutionExplanation:'This is how Tailwind generates its spacing scale at build time — a programmatic approach to CSS utility generation.' },

  // Lesson 12: Specificity
  { lessonId:12, difficulty:'Easy', topic:'CSS', title:'Specificity Battle', problemStatement:'Given 5 CSS rules targeting the same element, write a function that determines which declaration wins (highest specificity). Return the winning color.', examples:'#id .class p → wins over .class p → wins over p', starterCodeJs:'function winsSpecificity(rules) {\n  // rules = [{selector, color}]\n  // Parse specificity of each, return winning color\n  function spec(sel) {\n    const a = (sel.match(/#/g)||[]).length;\n    const b = (sel.match(/[.:[]/g)||[]).length;\n    const c = (sel.match(/\\b[a-z]/g)||[]).length;\n    return a*100 + b*10 + c;\n  }\n  return rules.sort((x,y) => spec(y.selector)-spec(x.selector))[0].color;\n}', hints:'IDs beat classes beat elements. !important beats all (handle separately). Equal specificity: last in source wins''], solutionExplanation:'Specificity is compared left to right: ID count, then class/pseudo/attribute count, then element count. !important overrides all.' },
  { lessonId:12, difficulty:'Medium', topic:'CSS', title:'CSS Custom Properties Theme', problemStatement:'Build a complete theming system using CSS custom properties: define light and dark themes, apply them with a .dark class on <html>, and provide a JS toggle function.', examples:':root { --bg: white; } .dark { --bg: #0f172a; }', starterCodeJs:'function buildTheme() {\n  return `\n    :root {\n      --color-bg: #ffffff;\n      --color-text: #0f172a;\n      --color-primary: #3b82f6;\n    }\n    .dark {\n      --color-bg: #0f172a;\n      --color-text: #f1f5f9;\n      --color-primary: #60a5fa;\n    }\n    body { background: var(--color-bg); color: var(--color-text); }\n  `;\n}\nfunction toggleDark() {\n  document.documentElement.classList.toggle("dark");\n  localStorage.setItem("theme", document.documentElement.classList.contains("dark") ? "dark" : "light");\n}', hints:':root for global tokens. .dark overrides them. var() uses the nearest ancestor definition. Persist in localStorage''], solutionExplanation:'Custom properties cascade like any other property — .dark on html overrides :root values for all descendant elements.' },
  { lessonId:12, difficulty:'Medium', topic:'CSS', title:'Cascade Layer Order Demo', problemStatement:'Write CSS using @layer to demonstrate that layer order controls specificity: a low-specificity rule in a later layer beats a high-specificity rule in an earlier layer.', examples:'@layer base, components; @layer base { #id { color: red } } @layer components { p { color: blue } } → blue wins', starterCodeJs:'function buildLayerDemo() {\n  return `\n    @layer base, components, utilities;\n    @layer base {\n      #special-text { color: red; font-size: 2rem; }\n    }\n    @layer components {\n      p { color: blue; }\n    }\n    @layer utilities {\n      .small { font-size: 0.75rem; }\n    }\n    /* What color is <p id="special-text">? */\n    /* Answer: blue — components layer beats base */\n  `;\n}', hints:'Layer order defined in @layer base, comp declaration. Later layer wins over earlier regardless of specificity. Unlayered styles beat all layers''], solutionExplanation:'@layer declarations define order; later layers have higher priority regardless of selector specificity within them.' },
  { lessonId:12, difficulty:'Hard', topic:'CSS', title:'Specificity Override Refactor', problemStatement:'Refactor these overly specific CSS rules to use lower-specificity alternatives without changing visual output. Avoid !important and IDs where possible.', examples:'#main #sidebar .widget h2 → .widget-title', starterCodeJs:'// Overly specific (BAD):\nconst bad = `\n  #main #sidebar .widget h2 { color: blue; }\n  #header nav ul li a { font-weight: bold; }\n  body #footer .links a:hover { text-decoration: none; }\n`;\n\n// Refactor to lower specificity (GOOD):\nconst good = `\n  /* Your refactored rules here */\n`;', hints:'Extract semantic class names. .widget-title, .nav-link, .footer-link. BEM eliminates need for high specificity''], solutionExplanation:'High specificity creates fragile CSS that is hard to override without escalating to even higher specificity or !important.' },
  { lessonId:12, difficulty:'Easy', topic:'CSS', title:'Inheritance Demo', problemStatement:'Demonstrate CSS inheritance with a code example: set color and font on body, show that a nested div inherits them, then show that border (non-inheritable) does not inherit. Add explicit inherit keyword to force inheritance of border.', examples:'body { color: red } div { /* inherits color */ border: inherit; /* copies parent border */ }', starterCodeJs:'function buildInheritanceDemo() {\n  return {\n    html: `<body><div class="child"><span>Text</span></div></body>`,\n    css: `\n      body { color: #1e293b; font-family: sans-serif; border: 2px solid red; }\n      .child { /* inherits color and font automatically */ }\n      .child span { border: inherit; /* explicitly inherits border */ }\n    `\n  };\n}', hints:'Inheritable: color, font-*, line-height, text-*. Non-inheritable: border, margin, padding, width. inherit forces inheritance of any property''], solutionExplanation:'Properties designed for text (color, font) inherit; box model properties (border, padding) do not — this prevents unwanted style leakage.' },
  { lessonId:12, difficulty:'Hard', topic:'CSS', title:'CSS Reset vs Normalize', problemStatement:'Write two CSS resets: (1) A minimal modern reset that sets box-sizing, removes margins/padding, and sets sensible defaults. (2) Write a comment explaining when to use reset vs normalize.', examples:'*, *::before, *::after { box-sizing: border-box; }', starterCodeJs:'function buildModernReset() {\n  return `\n    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n    /* Add: img max-width, smooth scroll, font inheritance */\n  `;\n}\n// Normalize vs Reset:\n// Reset: removes ALL browser defaults\n// Normalize: preserves useful defaults, fixes inconsistencies', hints:'img { max-width: 100%; display: block; }. html { scroll-behavior: smooth; }. input/button { font: inherit; }''], solutionExplanation:'Modern reset eliminates default margins that cause unexpected spacing. Normalize keeps useful defaults like heading sizes.' },
  { lessonId:12, difficulty:'Medium', topic:'CSS', title:'CSS Variable Scope', problemStatement:'Demonstrate that CSS custom properties can be scoped to components: create a card component that has its own --bg and --border variables, and a dark variant that overrides just those variables.', examples:'.card { --bg: white; } .card--dark { --bg: #1e293b; }', starterCodeJs:'function buildScopedVars() {\n  return `\n    .card {\n      --card-bg: #ffffff;\n      --card-border: #e2e8f0;\n      --card-text: #0f172a;\n      background: var(--card-bg);\n      border: 1px solid var(--card-border);\n      color: var(--card-text);\n    }\n    .card--dark {\n      --card-bg: #1e293b;\n      --card-border: #334155;\n      --card-text: #f1f5f9;\n    }\n  `;\n}', hints:'["Component-scoped tokens don\''], solutionExplanation:'Component-level custom properties are the CSS-native approach to component theming without JS or CSS-in-JS.' },
  { lessonId:12, difficulty:'Hard', topic:'CSS', title:'Specificity Graph Analyzer', problemStatement:'Write a function that takes an array of CSS rule objects and returns a "specificity health" report: count of rules using IDs, !important, inline styles, and rules with specificity > (0,2,0). Flag as unhealthy if > 20% are high specificity.', examples:'{ idCount: 5, importantCount: 3, highSpecCount: 8, healthy: false }', starterCodeJs:'function analyzeCSS(rules) {\n  // rules = [{selector, hasImportant}]\n  function spec(sel) {\n    const a = (sel.match(/#\\w+/g)||[]).length;\n    const b = (sel.match(/[.:[]/g)||[]).length;\n    return [a, b];\n  }\n  const report = { idCount:0, importantCount:0, highSpecCount:0 };\n  rules.forEach(r => {\n    const [a,b] = spec(r.selector);\n    if (a > 0) report.idCount++;\n    if (r.hasImportant) report.importantCount++;\n    if (a > 0 || b > 2) report.highSpecCount++;\n  });\n  report.healthy = report.highSpecCount / rules.length < 0.2;\n  return report;\n}', hints:'High specificity = IDs or 3+ classes. Healthy threshold: <20% high-specificity rules. This is what CSS linters (stylelint) do''], solutionExplanation:'Specificity analysis helps maintain CSS scalability. High-specificity rules create a "specificity arms race" in large codebases.' },
  { lessonId:12, difficulty:'Easy', topic:'CSS', title:'unset and revert Demo', problemStatement:'Show the difference between inherit, initial, unset, and revert keyword values. Create an example with a color property applied on body and nested elements using each keyword.', examples:'color: unset → inherits if inheritable property, else initial', starterCodeJs:'function buildKeywordDemo() {\n  return `\n    body { color: red; border: 2px solid blue; }\n    .inherit  { color: inherit; }   /* → red (from body) */\n    .initial  { color: initial; }   /* → browser default (black) */\n    .unset    { color: unset; }     /* → red (color inherits) */\n    .unset-b  { border: unset; }    /* → none (border does not inherit) */\n    .revert   { color: revert; }    /* → UA stylesheet default */\n  `;\n}', hints:'inherit: always inherit from parent. initial: CSS spec default value. unset: inherit if inheritable, else initial. revert: UA stylesheet value''], solutionExplanation:'unset is the most useful: it cleanly undoes author styles while respecting whether the property is naturally inheritable.' },
  { lessonId:12, difficulty:'Medium', topic:'CSS', title:'BEM Naming Generator', problemStatement:'Write a JS function bemClass(block, element, modifier) that generates proper BEM class names. Also write parseBEM(className) that extracts block, element, modifier from a BEM class string.', examples:'bemClass("card","title","large") → "card__title--large"', starterCodeJs:'function bemClass(block, element, modifier) {\n  let cls = block;\n  if (element) cls += "__" + element;\n  if (modifier) cls += "--" + modifier;\n  return cls;\n}\nfunction parseBEM(className) {\n  const [blockEl, modifier] = className.split("--");\n  const [block, element] = blockEl.split("__");\n  return { block, element: element || null, modifier: modifier || null };\n}', hints:'Block__Element--Modifier. __ separates element. -- separates modifier. element and modifier are optional''], solutionExplanation:'BEM prevents specificity issues by using flat class names. No descendant selectors needed — each class is uniquely named.' },

  // Lessons 13-20: Add 10 coding questions each
  // Lesson 13: Box Model
  { lessonId:13, difficulty:'Easy', topic:'CSS', title:'Box Model Calculator', problemStatement:'Write a function that calculates the total space (including margin) an element occupies given: content width/height, padding, border, and margin values.', examples:'{width:200,padding:20,border:2,margin:16} → total width: 200+40+4+32 = 276px', starterCodeJs:'function totalSize(content, padding, border, margin) {\n  return {\n    totalWidth: content.w + padding*2 + border*2 + margin*2,\n    totalHeight: content.h + padding*2 + border*2 + margin*2,\n    borderBoxWidth: content.w + padding*2 + border*2\n  };\n}', hints:'content-box: width is content only. border-box: width = content+padding+border. margin is always outside''], solutionExplanation:'Understanding box model math is critical — it directly affects layout. border-box makes width = content+padding+border.' },
  { lessonId:13, difficulty:'Medium', topic:'CSS', title:'Card with Perfect Spacing', problemStatement:'Build a CSS card component using box-sizing:border-box, with 24px padding, 1px border, border-radius:12px, and box-shadow. The card should always be exactly 320px wide regardless of padding.', examples:'width:320px with box-sizing:border-box includes padding and border', starterCodeJs:'function buildCardCSS() {\n  return `\n    .card {\n      box-sizing: border-box;\n      width: 320px;\n      padding: 24px;\n      border: 1px solid #e2e8f0;\n      border-radius: 12px;\n      box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);\n    }\n  `;\n}', hints:'Without border-box: 320 + 48 + 2 = 370px actual width. border-box keeps it at exactly 320px. This is why global * {box-sizing:border-box} is recommended''], solutionExplanation:'border-box makes width predictable: declared width IS the rendered width. Content area = 320 - 48 (padding) - 2 (border) = 270px.' },
  { lessonId:13, difficulty:'Medium', topic:'CSS', title:'Margin Collapse Demo', problemStatement:'Create an HTML/CSS demo that shows margin collapse. Two divs each with margin:20px should have 20px between them (not 40px). Then show how to prevent collapse with padding or overflow:hidden.', examples:'margin:20px + margin:20px = 20px between them (not 40px)', starterCodeJs:'function buildMarginCollapseDemo() {\n  return {\n    html: `<div class="box">Box 1</div><div class="box">Box 2</div>`,\n    css: `\n      .box { margin: 20px; padding: 10px; background: #e2e8f0; }\n      /* The gap between boxes = 20px, not 40px */\n    `,\n    fix: `\n      /* Fix 1: Add border to parent */\n      /* Fix 2: overflow:hidden on parent */\n      /* Fix 3: Use padding instead of margin */\n    `\n  };\n}', hints:'Collapse only between vertical margins. Never horizontal margins. Does not collapse inside flex/grid containers''], solutionExplanation:'Margin collapse prevents excessive whitespace between consecutive block elements. Flexbox and grid always disable it.' },
  { lessonId:13, difficulty:'Hard', topic:'CSS', title:'Aspect Ratio Container', problemStatement:'Build a CSS aspect ratio container (16:9) without using the aspect-ratio property — using the padding-top hack. Then show the modern version with aspect-ratio:16/9.', examples:'padding-top:56.25% creates 16:9 container', starterCodeJs:'function buildAspectRatioCSS() {\n  return `\n    /* Old technique: padding-top hack */\n    .ratio-old {\n      position: relative;\n      padding-top: 56.25%; /* 9/16 = 0.5625 */\n    }\n    .ratio-old > * {\n      position: absolute;\n      inset: 0;\n    }\n    /* Modern: */\n    .ratio-new {\n      aspect-ratio: 16 / 9;\n    }\n  `;\n}', hints:'padding percentage is relative to width. 9/16 = 56.25%. inset:0 is shorthand for top:0 right:0 bottom:0 left:0''], solutionExplanation:'The padding hack works because percentage padding is always relative to the element\'s width — so padding-top:56.25% creates a height that\'s 56.25% of width.' },
  { lessonId:13, difficulty:'Easy', topic:'CSS', title:'Centering Cheatsheet', problemStatement:'Write CSS for 5 different centering scenarios: (1) center text, (2) center an inline element horizontally, (3) center a block with margin auto, (4) center with flexbox, (5) center with grid.', examples:'5 working centering techniques', starterCodeJs:'function buildCenteringCSS() {\n  return `\n    /* 1. Center text */\n    .center-text { text-align: center; }\n    /* 2. Inline element horizontal */\n    .center-inline { display: block; margin: 0 auto; }\n    /* 3. Block with margin auto */\n    .center-block { width: 200px; margin: 0 auto; }\n    /* 4. Flexbox */\n    .center-flex { display: flex; justify-content: center; align-items: center; }\n    /* 5. Grid */\n    .center-grid { display: grid; place-items: center; }\n  `;\n}', hints:'place-items is shorthand for align-items + justify-items. margin:auto on block needs explicit width. flex centering for parent container''], solutionExplanation:'place-items:center is the most concise modern centering. For absolute centering: inset:0; margin:auto on position:absolute element.' },
  { lessonId:13, difficulty:'Medium', topic:'CSS', title:'Overflow Scroll with Custom Scrollbar', problemStatement:'Build a scrollable content area with a custom scrollbar: thin, rounded, matching brand colors. Ensure it degrades gracefully in Firefox (which uses scrollbar-width).', examples:'::-webkit-scrollbar and scrollbar-width:thin for Firefox', starterCodeJs:'function buildScrollbarCSS() {\n  return `\n    .scroll-area {\n      height: 300px;\n      overflow-y: auto;\n      scrollbar-width: thin;\n      scrollbar-color: #3b82f6 #f1f5f9;\n    }\n    .scroll-area::-webkit-scrollbar { width: 6px; }\n    .scroll-area::-webkit-scrollbar-track { background: #f1f5f9; border-radius: 3px; }\n    .scroll-area::-webkit-scrollbar-thumb { background: #3b82f6; border-radius: 3px; }\n  `;\n}', hints:'::-webkit-scrollbar for Chrome/Safari. scrollbar-width:thin for Firefox. scrollbar-color: thumb track for Firefox''], solutionExplanation:'Two APIs cover all browsers: ::-webkit-scrollbar pseudo-elements (Chromium) and scrollbar-width/scrollbar-color (Firefox/modern standard).' },
  { lessonId:13, difficulty:'Hard', topic:'CSS', title:'Block Formatting Context Demo', problemStatement:'Show 3 scenarios where creating a BFC solves layout issues: (1) containing floats without clearfix, (2) preventing margin collapse, (3) preventing text wrapping around a float.', examples:'overflow:hidden on parent → BFC → contains child floats', starterCodeJs:'function buildBFCDemo() {\n  return `\n    /* 1. Contain floats */\n    .clearfix { overflow: hidden; } /* Creates BFC */\n    .float-child { float: left; }\n    /* 2. Prevent margin collapse */\n    .no-collapse { overflow: hidden; } /* BFC prevents collapse */\n    /* 3. Prevent text wrap around float */\n    .text-block { overflow: hidden; } /* BFC creates own block */\n  `;\n}', hints:'BFC created by: overflow!=visible, float, position absolute/fixed, display inline-block/flex/grid/table-cell''], solutionExplanation:'A BFC is a self-contained layout region. Its key properties: it contains its floats, prevents margin collapse with its contents, and does not wrap around external floats.' },
  { lessonId:13, difficulty:'Hard', topic:'CSS', title:'Negative Margin Layout', problemStatement:'Use negative margins to: (1) overlap two elements, (2) pull an element outside its parent, (3) create a full-width section inside a narrow container. Explain why this works.', examples:'margin-left: -24px pulls left beyond parent edge', starterCodeJs:'function buildNegativeMarginDemo() {\n  return `\n    /* 1. Overlap elements */\n    .overlap { margin-top: -20px; position: relative; }\n    /* 2. Pull outside parent */\n    .pull-out { margin-left: -16px; margin-right: -16px; }\n    /* 3. Full-width inside container */\n    .full-bleed {\n      margin-left: calc(-50vw + 50%);\n      margin-right: calc(-50vw + 50%);\n    }\n  `;\n}', hints:'Negative margin on one side pulls element in that direction. The full-bleed trick: -50vw + 50% of container width. Negative top/left margins pull the element, not its space''], solutionExplanation:'The full-bleed calc trick: 50vw is half the viewport. 50% is half the container. Their difference extends the element to the viewport edge.' },
  { lessonId:13, difficulty:'Easy', topic:'CSS', title:'Box Shadow Depth System', problemStatement:'Create a CSS elevation system with 5 shadow levels (shadow-sm, shadow-md, shadow-lg, shadow-xl, shadow-2xl) following Material Design\'s approach of multiple layered shadows for realism.', examples:'.shadow-md { box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06); }', starterCodeJs:'function buildShadowSystem() {\n  return `\n    .shadow-sm { box-shadow: 0 1px 2px rgba(0,0,0,0.05); }\n    .shadow-md { box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1); }\n    .shadow-lg { box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1); }\n    .shadow-xl { box-shadow: 0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1); }\n    .shadow-2xl { box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25); }\n  `;\n}', hints:'Negative blur spread: -3px makes shadow start inside element. Layered shadows: one diffuse + one sharp. rgba alpha: 0.1 is subtle, 0.25 is strong''], solutionExplanation:'Layered box-shadows with different offsets and blurs create realistic elevation — mimicking how physical objects cast both diffuse and sharp shadows.' },
  { lessonId:13, difficulty:'Medium', topic:'CSS', title:'Logical Properties', problemStatement:'Rewrite a CSS rule that uses physical properties (margin-left, padding-right, border-top) using CSS logical properties (margin-inline-start, padding-inline-end, border-block-start) for RTL support.', examples:'margin-left → margin-inline-start (left in LTR, right in RTL)', starterCodeJs:'// Physical (LTR only):\nconst physical = `\n  .card {\n    margin-left: 16px;\n    padding-right: 24px;\n    border-top: 2px solid blue;\n    text-align: left;\n  }\n`;\n// Logical (LTR + RTL):\nconst logical = `\n  .card {\n    margin-inline-start: 16px;\n    padding-inline-end: 24px;\n    border-block-start: 2px solid blue;\n    text-align: start;\n  }\n`;', hints:'inline = horizontal axis. block = vertical axis. start = left in LTR, right in RTL. end = opposite of start''], solutionExplanation:'Logical properties adapt to writing direction. text-align:start = left in LTR, right in RTL — no need for [dir=rtl] overrides.' },
]

async function main() {
  console.log('Seeding lessons 11-20 (CSS module)...')
  let qCount = 0, cCount = 0
  for (const q of quiz) {
    const exists = await p.quizQuestion.findFirst({ where: { lessonId: q.lessonId, question: q.question } })
    if (!exists) { await p.quizQuestion.create({ data: q }); qCount++ }
  }
  console.log(`✓ ${qCount} quiz questions inserted`)
  for (const q of coding) {
    const exists = await p.practiceQuestion.findFirst({ where: { lessonId: q.lessonId, title: q.title } })
    if (!exists) { await p.practiceQuestion.create({ data: q }); cCount++ }
  }
  console.log(`✓ ${cCount} coding questions inserted`)
}
main().catch(console.error).finally(() => p.$disconnect())
