const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const quizQuestions = [
  // Lesson 41 - Node.js Advanced
  {lessonId:41,question:"What does the Node.js Event Loop do?",options:["Executes synchronous code","Manages asynchronous callbacks and I/O","Compiles JavaScript code","Manages memory allocation"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:41,question:"What is the difference between process.nextTick() and setImmediate()?",options:["No difference","nextTick fires before I/O callbacks; setImmediate fires after","nextTick is async; setImmediate is sync","setImmediate is faster"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:41,question:"What is a Node.js Stream?",options:["A database connection","An abstract interface for reading/writing data in chunks","A type of Promise","A file system path"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:41,question:"Which stream type is both readable and writable?",options:["Readable","Writable","Duplex","Transform"],correctAnswer:2,difficulty:"Medium"},
  {lessonId:41,question:"What does the cluster module do?",options:["Clusters database connections","Creates child processes to utilize multiple CPU cores","Groups modules together","Manages environment variables"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:41,question:"What is the purpose of the worker_threads module?",options:["To create HTTP servers","To run JavaScript in parallel threads","To manage file uploads","To handle database queries"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:41,question:"What does util.promisify() do?",options:["Creates a new Promise","Converts callback-style functions to Promise-based","Logs utility messages","Validates function types"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:41,question:"What is the Node.js Buffer class used for?",options:["Buffering HTTP responses","Handling binary data","Storing environment variables","Caching database queries"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:41,question:"How do you detect memory leaks in a Node.js application?",options:["Use console.log","Use process.memoryUsage() and heap snapshots","Use Math.random()","Check the package.json"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:41,question:"What is the difference between spawn() and exec() in child_process?",options:["No difference","spawn streams output; exec buffers entire output","exec is newer","spawn is synchronous"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 42 - Node.js HTTP
  {lessonId:42,question:"What is the purpose of the http.createServer() method?",options:["To make HTTP requests","To create an HTTP server that handles incoming requests","To parse URLs","To create HTTPS connections"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:42,question:"How do you parse query parameters from a URL in Node.js?",options:["Use req.query","Use the url module and URLSearchParams","Use JSON.parse","Use Buffer.from"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:42,question:"What does res.setHeader() do?",options:["Sends the response","Sets an HTTP response header","Reads a request header","Redirects the request"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:42,question:"How do you handle POST request body in raw Node.js?",options:["Use req.body directly","Listen to data and end events on req stream","Use fs.readFile","Use process.stdin"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:42,question:"What HTTP status code means 'Created'?",options:["200","204","201","301"],correctAnswer:2,difficulty:"Easy"},
  {lessonId:42,question:"What is CORS and why is it needed?",options:["A compression algorithm","Cross-Origin Resource Sharing - browser security for cross-domain requests","A caching strategy","A routing algorithm"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:42,question:"What does the Content-Type header specify?",options:["The response size","The format of the request/response body","The encoding","The route path"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:42,question:"What is the difference between HTTP/1.1 and HTTP/2?",options:["HTTP/2 is slower","HTTP/2 supports multiplexing and header compression","HTTP/1.1 is encrypted","HTTP/2 only works with HTTPS"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:42,question:"How do you create an HTTPS server in Node.js?",options:["Use http.createServer with ssl option","Use https.createServer with key and cert options","Use tls.createServer","Use http.secure()"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:42,question:"What is a Keep-Alive connection?",options:["A WebSocket connection","Reusing TCP connection for multiple HTTP requests","A heartbeat signal","A timeout mechanism"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 43 - npm and Package Management
  {lessonId:43,question:"What is the purpose of package-lock.json?",options:["To list dev dependencies only","To lock exact dependency versions for reproducible installs","To store scripts","To cache packages"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:43,question:"What does 'npm ci' do differently from 'npm install'?",options:["Installs only CI dependencies","Installs from lock file exactly, fails if lock file mismatches","Clears cache first","Installs globally"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:43,question:"What is a peer dependency?",options:["A shared dependency that the consumer must install","An optional dependency","A dev-only dependency","A bundled dependency"],correctAnswer:0,difficulty:"Hard"},
  {lessonId:43,question:"What does 'npm audit' do?",options:["Checks code quality","Scans dependencies for known security vulnerabilities","Lists all packages","Tests npm connection"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:43,question:"What is the difference between ~ and ^ in semantic versioning?",options:["No difference","~ allows patch updates; ^ allows minor+patch updates","~ is older syntax","^ is for prerelease"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:43,question:"What is npm workspaces?",options:["A plugin system","A way to manage multiple packages in a monorepo","A GUI tool","A caching layer"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:43,question:"How do you publish a package to npm?",options:["git push npm","npm publish","npm deploy","npm push"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:43,question:"What does the 'files' field in package.json specify?",options:["Files to ignore","Files to include when publishing the package","Test files","Config files"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:43,question:"What is npx used for?",options:["To install packages permanently","To run packages without installing them globally","To publish packages","To update packages"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:43,question:"What is the purpose of .npmrc file?",options:["Defines npm scripts","Configures npm settings like registry, auth tokens","Ignores packages","Lists dependencies"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 44 - Express Basics
  {lessonId:44,question:"What is Express.js?",options:["A database ORM","A minimal Node.js web framework","A frontend framework","A testing library"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:44,question:"How do you define a GET route in Express?",options:["app.route('/path', handler)","app.get('/path', handler)","app.define('GET', '/path', handler)","app.handle('/path', 'GET', handler)"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:44,question:"What are Express middleware functions?",options:["Database query functions","Functions that have access to req, res, and next","Route handlers","Error handlers only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:44,question:"What does next() do in Express middleware?",options:["Ends the request","Passes control to the next middleware function","Redirects the request","Sends a response"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:44,question:"How do you serve static files in Express?",options:["app.serve('public')","app.use(express.static('public'))","app.files('public')","app.public('public')"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:44,question:"What is express.json() middleware used for?",options:["To serve JSON files","To parse incoming JSON request bodies","To serialize responses","To validate JSON"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:44,question:"How do you access route parameters in Express?",options:["req.query.id","req.params.id","req.body.id","req.headers.id"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:44,question:"What does app.use() do?",options:["Defines GET routes only","Mounts middleware for all HTTP methods and routes","Creates a new app","Configures settings"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:44,question:"How do you handle errors in Express?",options:["Use try/catch only","Add error middleware with 4 params: (err, req, res, next)","Use process.on('error')","Use app.error()"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:44,question:"What is the difference between app.get() and router.get()?",options:["No difference","router.get() is modular - used in express.Router() for organizing routes","app.get() is deprecated","router.get() only handles GET"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 45 - Express Routing
  {lessonId:45,question:"How do you create a modular router in Express?",options:["import { Router } from 'express'","const router = express.Router()","app.createRouter()","new express.Route()"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:45,question:"What is route chaining in Express?",options:["Linking multiple apps","Using .route('/path').get(fn).post(fn) to chain method handlers","Nesting routes","Async route handling"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:45,question:"How do you define a wildcard route parameter?",options:["/:id*","/:param+","/*","/:id?"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:45,question:"What does router.param() do?",options:["Validates route parameters","Adds pre-processing callback for named route parameters","Lists all params","Sets default params"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:45,question:"How do you mount a router at a specific path prefix?",options:["router.prefix('/api')","app.use('/api', router)","app.mount('/api', router)","router.base('/api')"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:45,question:"What is an Express sub-application?",options:["A smaller Express instance for modular routing","A child process","A route group","An API version"],correctAnswer:0,difficulty:"Hard"},
  {lessonId:45,question:"How do you handle 404 in Express?",options:["app.error(404, handler)","Add middleware after all routes: app.use((req,res)=>res.status(404)...)","app.notFound(handler)","Express handles it automatically"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:45,question:"What is the order of middleware execution in Express?",options:["Random","Alphabetical","Order of app.use()/app.METHOD() calls","Reverse order"],correctAnswer:2,difficulty:"Medium"},
  {lessonId:45,question:"How do you group routes with a common prefix using Router?",options:["Express does not support prefix","const router = express.Router(); app.use('/prefix', router)","app.prefix('/prefix')","router.prefix('/prefix')"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:45,question:"What happens if you don't call next() in middleware and don't send a response?",options:["Express automatically continues","The request hangs (no response)","Express throws an error","next() is called automatically"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 46 - Express Middleware
  {lessonId:46,question:"What is the correct signature for Express error-handling middleware?",options:["(req, res, next)","(err, req, res, next)","(error, next)","(req, res, error)"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:46,question:"What does helmet.js do?",options:["Authentication middleware","Sets security-related HTTP headers","Compresses responses","Handles CORS"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:46,question:"What is morgan used for in Express?",options:["Authentication","HTTP request logging middleware","Rate limiting","Input validation"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:46,question:"How does express-rate-limit work?",options:["By blocking all requests","By counting requests per IP and rejecting those over the limit","By queuing requests","By caching responses"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:46,question:"What is the purpose of compression middleware?",options:["To encrypt responses","To gzip/deflate responses for smaller payload sizes","To compress images","To minify code"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:46,question:"How do you pass data between middleware functions?",options:["Use global variables","Attach properties to req object (e.g., req.user = ...)","Use res.locals","Both req object and res.locals work"],correctAnswer:3,difficulty:"Medium"},
  {lessonId:46,question:"What is cors middleware used for?",options:["Content compression","Allowing/restricting cross-origin requests via HTTP headers","Route caching","Input sanitization"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:46,question:"When should you use next(err) vs next()?",options:["They are identical","next(err) skips to error-handling middleware; next() continues normal flow","next(err) retries the request","next() sends a 200 response"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:46,question:"What is multer used for?",options:["Authentication","Handling multipart/form-data (file uploads)","JSON parsing","Rate limiting"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:46,question:"How do you validate request input in Express?",options:["Only manually in route handlers","Use express-validator or Joi libraries with middleware","Express validates automatically","Use SQL constraints only"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 47 - REST API Design
  {lessonId:47,question:"What does REST stand for?",options:["Remote Execution State Transfer","Representational State Transfer","Resource Endpoint State Technology","Relational Endpoint Specification Type"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:47,question:"Which HTTP method should be used to update a resource partially?",options:["PUT","POST","PATCH","DELETE"],correctAnswer:2,difficulty:"Easy"},
  {lessonId:47,question:"What is HATEOAS in REST?",options:["A security protocol","Hypermedia As The Engine Of Application State - API responses include links","A pagination strategy","An error format"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:47,question:"What is the best practice for API versioning?",options:["Never version APIs","Include version in URL (/api/v1) or Accept header","Use query params only","Version is not needed"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:47,question:"What HTTP status code means 'Unprocessable Entity' (validation error)?",options:["400","404","422","500"],correctAnswer:2,difficulty:"Medium"},
  {lessonId:47,question:"What is idempotency in REST APIs?",options:["APIs that return the same response format","Operations that can be repeated without changing the outcome","REST APIs that use GET only","Caching responses"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:47,question:"How should errors be returned from a REST API?",options:["Always return 200 with error in body","Return appropriate HTTP status code with structured error body","Throw exceptions","Return empty responses"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:47,question:"What is pagination in REST APIs?",options:["Splitting large API responses into pages","A caching strategy","An auth method","URL encoding"],correctAnswer:0,difficulty:"Easy"},
  {lessonId:47,question:"What is the difference between PUT and POST?",options:["No difference","PUT updates/replaces a specific resource; POST creates a new resource","POST is more secure","PUT is for files only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:47,question:"What is JWT and when is it used in REST APIs?",options:["A JSON library","JSON Web Token - compact token for stateless authentication","A query language","A caching mechanism"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 48 - Express Advanced
  {lessonId:48,question:"What is Express.js template engine integration?",options:["A way to use React in Express","View rendering engines like EJS/Pug that generate HTML from templates","A database adapter","An authentication system"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:48,question:"How do you set up WebSockets with Express?",options:["app.ws()","Use socket.io or ws alongside the Express HTTP server","Express has built-in WebSocket","app.upgrade()"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:48,question:"What is express-session used for?",options:["Static file serving","Managing server-side sessions with session IDs stored in cookies","JWT authentication","Request logging"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:48,question:"How do you implement graceful shutdown in Express?",options:["Call process.exit(0) immediately","Listen for SIGTERM, stop accepting new connections, close existing ones","Use app.close()","Graceful shutdown is not needed"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:48,question:"What is express-async-errors or asyncHandler used for?",options:["Making routes faster","Catching async errors and passing to next(err) without try/catch wrappers","Handling streams","CORS handling"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:48,question:"How do you configure trust proxy in Express?",options:["It is not needed","app.set('trust proxy', 1) - tells Express to trust X-Forwarded-For headers behind a proxy","app.proxy = true","In nginx config only"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:48,question:"What is the difference between res.send() and res.json()?",options:["No difference","res.json() sets Content-Type to application/json and serializes object","res.send() is async","res.json() is deprecated"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:48,question:"How do you implement file download in Express?",options:["res.sendFile()","res.download() sets Content-Disposition header for file download","fs.pipe(res)","Use multipart response"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:48,question:"What is app.locals in Express?",options:["Local variables for a single request","Application-level variables available in all templates and route handlers","Module-scoped variables","Configuration settings only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:48,question:"How do you implement request timeout in Express?",options:["Express has built-in timeout","Use connect-timeout middleware or set socket timeout on server","Use setTimeout in each route","Timeouts are not needed"],correctAnswer:1,difficulty:"Hard"}
];

const codingQuestions = [
  // Lesson 38 - Node.js Advanced
  {lessonId:38,difficulty:"Easy",title:"File Copy with Streams",problemStatement:"Write a function copyFile(src, dest) using Node.js streams that copies a file chunk by chunk. Handle errors and cleanup streams on failure.",examples:"copyFile('input.txt','output.txt') pipes read stream to write stream",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nfunction copyFile(src, dest) {\n  return new Promise((resolve, reject) => {\n    const readStream = fs.createReadStream(src);\n    const writeStream = fs.createWriteStream(dest);\n    readStream.on('error', err => { writeStream.destroy(); reject(err); });\n    writeStream.on('error', err => { readStream.destroy(); reject(err); });\n    writeStream.on('finish', resolve);\n    readStream.pipe(writeStream);\n  });\n}\n// Modern approach using pipeline:\nconst { pipeline } = require('stream/promises');\nasync function copyFileModern(src, dest) {\n  await pipeline(fs.createReadStream(src), fs.createWriteStream(dest));\n}",hints:"pipeline() from stream/promises handles cleanup automatically. Classic approach needs manual error handling on both streams.",solutionExplanation:"pipe() forwards data but doesn't handle cleanup on error. pipeline() is the modern way: it destroys all streams on error automatically."},
  {lessonId:38,difficulty:"Medium",title:"Transform Stream for CSV Parsing",problemStatement:"Build a Transform stream that reads a CSV file line by line and outputs JSON objects. Handle the header row and data types.",examples:"CSV line 'Alice,30,NYC' -> JSON {name:'Alice',age:30,city:'NYC'}",starterCodeJs:"const { Transform } = require('stream');\nclass CSVToJSON extends Transform {\n  constructor(options = {}) {\n    super({ ...options, readableObjectMode: true });\n    this._headers = null;\n    this._buffer = '';\n  }\n  _transform(chunk, encoding, callback) {\n    this._buffer += chunk.toString();\n    const lines = this._buffer.split('\\n');\n    this._buffer = lines.pop(); // keep incomplete line\n    for (const line of lines) {\n      if (!line.trim()) continue;\n      const values = line.split(',').map(v => v.trim());\n      if (!this._headers) { this._headers = values; continue; }\n      const obj = {};\n      this._headers.forEach((h, i) => { obj[h] = isNaN(values[i]) ? values[i] : Number(values[i]); });\n      this.push(obj);\n    }\n    callback();\n  }\n  _flush(callback) {\n    if (this._buffer.trim() && this._headers) {\n      const values = this._buffer.split(',').map(v => v.trim());\n      const obj = {};\n      this._headers.forEach((h,i) => { obj[h] = values[i]; });\n      this.push(obj);\n    }\n    callback();\n  }\n}",hints:"readableObjectMode:true allows pushing objects. Buffer incomplete lines between chunks. _flush handles the last line after all chunks.",solutionExplanation:"Transform streams process data: _transform handles each chunk, _flush runs when source ends. Object mode allows non-Buffer output."},
  {lessonId:38,difficulty:"Medium",title:"Custom EventEmitter",problemStatement:"Build a TypedEventEmitter class that wraps EventEmitter with type safety and once() support for cleanup.",examples:"emitter.on('data', handler). emitter.emit('data', payload). emitter.off('data', handler).",starterCodeJs:"const { EventEmitter } = require('events');\nclass TypedEventEmitter extends EventEmitter {\n  constructor(options = {}) {\n    super(options);\n    this._handlers = new Map();\n  }\n  on(event, listener) {\n    super.on(event, listener);\n    return this; // chainable\n  }\n  once(event, listener) {\n    super.once(event, listener);\n    return this;\n  }\n  off(event, listener) {\n    super.off(event, listener);\n    return this;\n  }\n  waitFor(event, timeout = 5000) {\n    return new Promise((resolve, reject) => {\n      const timer = setTimeout(() => {\n        this.off(event, handler);\n        reject(new Error(`Timeout waiting for ${event}`));\n      }, timeout);\n      const handler = data => { clearTimeout(timer); resolve(data); };\n      this.once(event, handler);\n    });\n  }\n  removeAllListeners(event) {\n    super.removeAllListeners(event);\n    return this;\n  }\n}",hints:"waitFor() returns a Promise that resolves on next event emission. Timeout cleanup requires storing and removing the listener.",solutionExplanation:"EventEmitter pattern enables loose coupling. waitFor() converts event-based async to Promise-based. Timeout prevents hanging promises."},
  {lessonId:38,difficulty:"Hard",title:"HTTP Server with Cluster",problemStatement:"Build an HTTP server that uses cluster to fork workers for each CPU core. Handle worker crashes with automatic restart and graceful shutdown.",examples:"Master forks numCPUs workers. On SIGTERM, workers finish current requests then exit.",starterCodeJs:"const cluster = require('cluster');\nconst http = require('http');\nconst numCPUs = require('os').cpus().length;\nif (cluster.isPrimary) {\n  console.log(`Primary ${process.pid} running`);\n  for (let i = 0; i < numCPUs; i++) cluster.fork();\n  cluster.on('exit', (worker, code, signal) => {\n    console.log(`Worker ${worker.process.pid} died (${signal||code}). Restarting...`);\n    if (!worker.exitedAfterDisconnect) cluster.fork(); // don't restart on graceful shutdown\n  });\n  process.on('SIGTERM', () => {\n    Object.values(cluster.workers).forEach(w => w.send('shutdown'));\n  });\n} else {\n  const server = http.createServer((req, res) => {\n    res.writeHead(200);\n    res.end(`Handled by worker ${process.pid}\\n`);\n  });\n  server.listen(3000);\n  process.on('message', msg => {\n    if (msg === 'shutdown') {\n      server.close(() => process.exit(0));\n    }\n  });\n  console.log(`Worker ${process.pid} started`);\n}",hints:"isPrimary (or isMaster) splits master/worker code. exitedAfterDisconnect prevents re-forking gracefully disconnected workers.",solutionExplanation:"Cluster multiplies processes across CPU cores. IPC (process.send/message) enables master-worker communication for graceful shutdown."},
  {lessonId:38,difficulty:"Easy",title:"Environment Config Module",problemStatement:"Build a config module that reads environment variables with defaults and type coercion. Throw on required missing vars.",examples:"config.port is a Number. config.debug is a Boolean. Missing required var throws.",starterCodeJs:"function getEnv(key, options = {}) {\n  const { default: def, required = false, type = 'string' } = options;\n  const value = process.env[key];\n  if (value === undefined) {\n    if (required) throw new Error(`Missing required environment variable: ${key}`);\n    return def;\n  }\n  switch (type) {\n    case 'number': return Number(value);\n    case 'boolean': return value === 'true' || value === '1';\n    case 'json': return JSON.parse(value);\n    case 'array': return value.split(',').map(v => v.trim());\n    default: return value;\n  }\n}\nconst config = {\n  port: getEnv('PORT', { default: 3000, type: 'number' }),\n  dbUrl: getEnv('DATABASE_URL', { required: true }),\n  debug: getEnv('DEBUG', { default: false, type: 'boolean' }),\n  allowedOrigins: getEnv('ALLOWED_ORIGINS', { default: ['http://localhost:3000'], type: 'array' }),\n  jwtSecret: getEnv('JWT_SECRET', { required: true })\n};\nmodule.exports = config;",hints:"Coerce types at startup so route handlers never deal with strings for numbers/booleans. required check fails fast on misconfigured environments.",solutionExplanation:"Fail-fast configuration: if required env vars are missing, crash at startup with a clear message rather than failing silently later."},
  {lessonId:38,difficulty:"Medium",title:"Rate Limiter Implementation",problemStatement:"Implement a sliding window rate limiter using an in-memory Map. Support per-key limits (e.g., per IP).",examples:"limiter.check('ip:192.168.1.1', 100, 60000) returns {allowed:true, remaining:99}",starterCodeJs:"class SlidingWindowRateLimiter {\n  constructor() {\n    this._windows = new Map();\n  }\n  check(key, limit, windowMs) {\n    const now = Date.now();\n    const windowStart = now - windowMs;\n    if (!this._windows.has(key)) this._windows.set(key, []);\n    let timestamps = this._windows.get(key);\n    // Remove expired timestamps\n    timestamps = timestamps.filter(t => t > windowStart);\n    this._windows.set(key, timestamps);\n    const count = timestamps.length;\n    if (count >= limit) {\n      const resetAt = timestamps[0] + windowMs;\n      return { allowed: false, remaining: 0, resetAt };\n    }\n    timestamps.push(now);\n    return { allowed: true, remaining: limit - count - 1, resetAt: now + windowMs };\n  }\n  reset(key) { this._windows.delete(key); }\n  cleanup() { // Call periodically to free memory\n    const now = Date.now();\n    for (const [key, ts] of this._windows) {\n      if (ts.length === 0 || ts[ts.length-1] < now - 3600000) this._windows.delete(key);\n    }\n  }\n}",hints:"Sliding window: store timestamps of each request, filter out old ones. Count remaining timestamps = request count in window.",solutionExplanation:"Sliding window vs fixed window: sliding tracks actual time of each request, preventing burst at window boundary. Trades memory for accuracy."},
  {lessonId:38,difficulty:"Hard",title:"Worker Threads for CPU Work",problemStatement:"Use worker_threads to offload a CPU-intensive task (Fibonacci calculation) off the main thread. Use a worker pool.",examples:"pool.run(task) returns Promise. Workers reuse across tasks. Main thread stays responsive.",starterCodeJs:"const { Worker, isMainThread, parentPort, workerData } = require('worker_threads');\nif (!isMainThread) {\n  // Worker code: do CPU work and post result\n  const { n } = workerData;\n  function fib(n) { if (n<=1) return n; return fib(n-1)+fib(n-2); }\n  parentPort.postMessage(fib(n));\n} else {\n  // Main thread: worker pool\n  class WorkerPool {\n    constructor(size = 4) {\n      this._workers = [];\n      this._queue = [];\n      for (let i = 0; i < size; i++) this._createWorker();\n    }\n    _createWorker() {\n      const w = { busy: false, worker: null };\n      this._workers.push(w);\n    }\n    run(workerData) {\n      return new Promise((resolve, reject) => {\n        const task = { workerData, resolve, reject };\n        const idle = this._workers.find(w => !w.busy);\n        if (idle) this._runTask(idle, task); else this._queue.push(task);\n      });\n    }\n    _runTask(slot, { workerData, resolve, reject }) {\n      slot.busy = true;\n      slot.worker = new Worker(__filename, { workerData });\n      slot.worker.once('message', result => { slot.busy = false; slot.worker = null; resolve(result); if (this._queue.length) this._runTask(slot, this._queue.shift()); });\n      slot.worker.once('error', err => { slot.busy = false; reject(err); });\n    }\n  }\n  module.exports = new WorkerPool(4);\n}",hints:"if (!isMainThread) branch runs in the worker. Pool queues tasks when all workers busy. Worker is created per-task (or can be persistent with message passing).",solutionExplanation:"Worker threads run in parallel OS threads, unlike child_process. Pool pattern reuses thread overhead. Main thread is never blocked."},
  {lessonId:38,difficulty:"Medium",title:"HTTP Keep-Alive Server",problemStatement:"Build an HTTP server optimized for high concurrency: keep-alive connections, connection limiting, and request timeout.",examples:"Server accepts 10k connections, limits per IP, times out idle connections after 30s.",starterCodeJs:"const http = require('http');\nconst server = http.createServer((req, res) => {\n  res.setHeader('Connection', 'keep-alive');\n  res.setHeader('Keep-Alive', 'timeout=30');\n  res.writeHead(200, { 'Content-Type': 'application/json' });\n  res.end(JSON.stringify({ pid: process.pid, time: Date.now() }));\n});\nserver.keepAliveTimeout = 30000; // 30s idle timeout\nserver.headersTimeout = 35000; // must be > keepAliveTimeout\nserver.maxConnections = 10000;\nconst connections = new Map();\nserver.on('connection', socket => {\n  const id = Symbol();\n  connections.set(id, socket);\n  socket.on('close', () => connections.delete(id));\n});\nfunction gracefulShutdown() {\n  server.close(() => { console.log('Server closed'); process.exit(0); });\n  for (const socket of connections.values()) socket.destroy();\n}\nprocess.on('SIGTERM', gracefulShutdown);\nserver.listen(3000, () => console.log('Listening on 3000'));",hints:"keepAliveTimeout and headersTimeout prevent slow-client attacks. Track connections for graceful shutdown. headersTimeout > keepAliveTimeout.",solutionExplanation:"Keep-alive reuses TCP connections for multiple requests. Proper timeouts prevent connection exhaustion. Connection tracking enables graceful shutdown."},
  {lessonId:38,difficulty:"Easy",title:"Promisified File Operations",problemStatement:"Build a file utilities module using fs.promises. Support reading JSON, writing JSON, appending lines, and checking file existence.",examples:"await fileUtils.readJSON('config.json'). await fileUtils.writeJSON('out.json', data).",starterCodeJs:"const fs = require('fs').promises;\nconst path = require('path');\nconst fileUtils = {\n  async readJSON(filePath) {\n    const content = await fs.readFile(filePath, 'utf8');\n    return JSON.parse(content);\n  },\n  async writeJSON(filePath, data, indent = 2) {\n    await fs.mkdir(path.dirname(filePath), { recursive: true });\n    await fs.writeFile(filePath, JSON.stringify(data, null, indent), 'utf8');\n  },\n  async appendLine(filePath, line) {\n    await fs.appendFile(filePath, line + '\\n', 'utf8');\n  },\n  async exists(filePath) {\n    try { await fs.access(filePath); return true; } catch { return false; }\n  },\n  async readLines(filePath) {\n    const content = await fs.readFile(filePath, 'utf8');\n    return content.split('\\n').filter(l => l.trim());\n  },\n  async ensureDir(dirPath) {\n    await fs.mkdir(dirPath, { recursive: true });\n  }\n};\nmodule.exports = fileUtils;",hints:"fs.promises avoids callback-style code. mkdir with recursive:true creates parent directories. access() for existence check (not stat).",solutionExplanation:"fs.promises API returns Promises directly. mkdir recursive:true is idempotent. access() checks file accessibility more accurately than exists checks."},
  {lessonId:38,difficulty:"Hard",title:"Graceful Shutdown Handler",problemStatement:"Build a GracefulShutdown class that: listens for SIGTERM/SIGINT, stops accepting requests, waits for in-flight requests, then exits.",examples:"graceful.register(server). SIGTERM received -> wait max 30s for requests to finish -> exit.",starterCodeJs:"class GracefulShutdown {\n  constructor({ timeout = 30000, signals = ['SIGTERM', 'SIGINT'] } = {}) {\n    this._timeout = timeout;\n    this._servers = [];\n    this._shutting = false;\n    signals.forEach(sig => process.on(sig, () => this.shutdown(sig)));\n  }\n  register(server) {\n    this._servers.push(server);\n    return this;\n  }\n  async shutdown(signal) {\n    if (this._shutting) return;\n    this._shutting = true;\n    console.log(`${signal} received. Graceful shutdown...`);\n    const timer = setTimeout(() => { console.error('Forced shutdown after timeout'); process.exit(1); }, this._timeout);\n    try {\n      await Promise.all(this._servers.map(s => new Promise(resolve => s.close(resolve))));\n      clearTimeout(timer);\n      console.log('Shutdown complete');\n      process.exit(0);\n    } catch (err) {\n      console.error('Shutdown error:', err);\n      process.exit(1);\n    }\n  }\n}\nmodule.exports = GracefulShutdown;\n// Usage:\n// const shutdown = new GracefulShutdown();\n// shutdown.register(httpServer).register(httpsServer);",hints:"Promise.all closes all servers concurrently. Forced timeout as fallback prevents hanging. shutting flag prevents double-shutdown.",solutionExplanation:"Graceful shutdown: stop accepting new requests (server.close), wait for existing to finish, then exit. 30s timeout as safety net."},

  // Lesson 39 - Node.js File System
  {lessonId:39,difficulty:"Easy",title:"Directory Tree Walker",problemStatement:"Write a walkDir(dir) function that recursively lists all files in a directory tree. Return an array of file paths. Handle permission errors.",examples:"walkDir('./src') returns ['./src/index.js','./src/utils/helpers.js',...]",starterCodeJs:"const fs = require('fs').promises;\nconst path = require('path');\nasync function walkDir(dir, options = {}) {\n  const { extensions, ignore = ['node_modules', '.git'] } = options;\n  const results = [];\n  async function walk(currentDir) {\n    let entries;\n    try { entries = await fs.readdir(currentDir, { withFileTypes: true }); }\n    catch (e) { if (e.code === 'EACCES') return; throw e; }\n    for (const entry of entries) {\n      const fullPath = path.join(currentDir, entry.name);\n      if (ignore.includes(entry.name)) continue;\n      if (entry.isDirectory()) await walk(fullPath);\n      else if (entry.isFile()) {\n        if (!extensions || extensions.includes(path.extname(entry.name))) results.push(fullPath);\n      }\n    }\n  }\n  await walk(dir);\n  return results;\n}",hints:"withFileTypes:true returns Dirent objects with isDirectory()/isFile() methods (no extra stat call). Ignore node_modules to avoid recursion.",solutionExplanation:"Recursive async walk. withFileTypes avoids extra fs.stat calls per entry. Catch EACCES (permission denied) and continue rather than crash."},
  {lessonId:39,difficulty:"Medium",title:"File Watcher",problemStatement:"Build a file watcher using fs.watch that monitors a directory, debounces rapid changes, and emits events with the changed file and type.",examples:"watcher.on('change', ({type, file}) => ...). Handles rapid-fire saves from editors.",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nconst { EventEmitter } = require('events');\nclass FileWatcher extends EventEmitter {\n  constructor(dir, options = {}) {\n    super();\n    this._dir = dir;\n    this._debounceMs = options.debounce || 100;\n    this._timers = new Map();\n    this._watcher = fs.watch(dir, { recursive: true }, (eventType, filename) => {\n      if (!filename) return;\n      const key = filename;\n      clearTimeout(this._timers.get(key));\n      this._timers.set(key, setTimeout(() => {\n        this._timers.delete(key);\n        this.emit('change', { type: eventType, file: path.join(dir, filename) });\n      }, this._debounceMs));\n    });\n  }\n  close() {\n    this._watcher.close();\n    for (const t of this._timers.values()) clearTimeout(t);\n    this._timers.clear();\n  }\n}",hints:"fs.watch fires multiple events per save (especially on macOS). Debounce with setTimeout/clearTimeout per filename prevents duplicate events.",solutionExplanation:"fs.watch is fast but fires multiple events per real change. Debouncing per filename groups rapid events into one. EventEmitter enables reactive consumption."},
  {lessonId:39,difficulty:"Medium",title:"Atomic File Write",problemStatement:"Write an atomicWrite(path, data) function that writes to a temp file first, then renames. This prevents partial writes on crash.",examples:"atomicWrite('/etc/config', data) writes to /etc/config.tmp then renames to /etc/config",starterCodeJs:"const fs = require('fs').promises;\nconst path = require('path');\nconst os = require('os');\nasync function atomicWrite(filePath, data, options = {}) {\n  const dir = path.dirname(filePath);\n  const tmpPath = path.join(dir, `.${path.basename(filePath)}.${process.pid}.tmp`);\n  try {\n    await fs.writeFile(tmpPath, data, options);\n    await fs.rename(tmpPath, filePath);\n  } catch (err) {\n    try { await fs.unlink(tmpPath); } catch {}\n    throw err;\n  }\n}\nasync function atomicWriteJSON(filePath, data, indent = 2) {\n  await atomicWrite(filePath, JSON.stringify(data, null, indent) + '\\n', 'utf8');\n}",hints:"Include PID in temp filename to avoid conflicts between processes. rename() is atomic on most filesystems. Cleanup temp file on error.",solutionExplanation:"Write-then-rename is atomic on POSIX: rename() either succeeds fully or not at all. Readers never see partial data. PID makes temp name unique."},
  {lessonId:39,difficulty:"Hard",title:"Log Rotation",problemStatement:"Build a log rotation utility that writes logs to files, rotates when size limit is reached, keeps N old files, and compresses rotated logs.",examples:"logger.write('message') -> app.log. On 10MB: rename to app.1.log, optionally gzip.",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nconst zlib = require('zlib');\nconst { pipeline } = require('stream/promises');\nclass RotatingFileLogger {\n  constructor(options = {}) {\n    this._filePath = options.filePath || 'app.log';\n    this._maxSize = options.maxSize || 10 * 1024 * 1024;\n    this._maxFiles = options.maxFiles || 5;\n    this._compress = options.compress || false;\n    this._stream = this._open();\n    this._size = 0;\n  }\n  _open() {\n    try { this._size = fs.statSync(this._filePath).size; } catch { this._size = 0; }\n    return fs.createWriteStream(this._filePath, { flags: 'a' });\n  }\n  async write(line) {\n    const entry = `[${new Date().toISOString()}] ${line}\\n`;\n    this._size += Buffer.byteLength(entry);\n    this._stream.write(entry);\n    if (this._size >= this._maxSize) await this._rotate();\n  }\n  async _rotate() {\n    this._stream.end();\n    for (let i = this._maxFiles - 1; i >= 1; i--) {\n      const old = `${this._filePath}.${i}`;\n      const next = `${this._filePath}.${i+1}`;\n      try { fs.renameSync(old, next); } catch {}\n    }\n    fs.renameSync(this._filePath, `${this._filePath}.1`);\n    if (this._compress) {\n      await pipeline(fs.createReadStream(`${this._filePath}.1`), zlib.createGzip(), fs.createWriteStream(`${this._filePath}.1.gz`));\n      fs.unlinkSync(`${this._filePath}.1`);\n    }\n    this._stream = this._open();\n  }\n}",hints:"Check current file size on open (append mode). Rotate by renaming .1->.2, .0->.1, current->.0. zlib.createGzip() compresses rotated file.",solutionExplanation:"Log rotation: file.1 is most recent old log. Shift old logs up, rename current to .1. Optional gzip compression saves disk space."},
  {lessonId:39,difficulty:"Easy",title:"Simple CLI Tool",problemStatement:"Build a CLI tool using process.argv that accepts a command (create, delete, list) and writes/reads a simple JSON todo file.",examples:"node todo.js create 'Buy milk'. node todo.js list. node todo.js delete 1",starterCodeJs:"#!/usr/bin/env node\nconst fs = require('fs');\nconst path = require('path');\nconst TODO_FILE = path.join(os.homedir(), '.todos.json');\nfunction load() { try { return JSON.parse(fs.readFileSync(TODO_FILE,'utf8')); } catch { return []; } }\nfunction save(todos) { fs.writeFileSync(TODO_FILE, JSON.stringify(todos, null, 2)); }\nconst [,, cmd, ...args] = process.argv;\nconst todos = load();\nswitch (cmd) {\n  case 'create': todos.push({id: Date.now(), text: args.join(' '), done: false}); save(todos); console.log('Created'); break;\n  case 'list': todos.forEach((t,i)=>console.log(`${i+1}. [${t.done?'x':' '}] ${t.text}`)); break;\n  case 'done': todos[parseInt(args[0])-1].done = true; save(todos); console.log('Done'); break;\n  case 'delete': todos.splice(parseInt(args[0])-1, 1); save(todos); console.log('Deleted'); break;\n  default: console.log('Usage: todo.js [create|list|done|delete] [args]');\n}",hints:"process.argv[0] is node, [1] is script. Destructure to get command and args. Sync file ops are fine for CLI tools.",solutionExplanation:"CLI pattern: parse argv, load state, execute command, save state. For production CLIs use yargs or commander for argument parsing."},
  {lessonId:39,difficulty:"Medium",title:"Module Caching and Circular Deps",problemStatement:"Demonstrate and solve circular dependency issues in Node.js modules. Show how module cache works.",examples:"a.js requires b.js which requires a.js -> circular dep. Solution: lazy require or restructure.",starterCodeJs:"// Problem: circular dependency\n// a.js: const b = require('./b'); exports.greet = () => `Hello from A, B says: ${b.message}`;\n// b.js: const a = require('./a'); exports.message = `B using A: ${a.greet?a.greet():'not yet'}`;\n// Solution 1: Lazy require\nconst getB = () => require('./b'); // require at call time, not module load\n// Solution 2: Extract shared code to separate module\n// shared.js: exports.value = 'shared';\n// a.js: const {value} = require('./shared');\n// Solution 3: Dependency injection\nfunction createA(deps) { return { greet: () => `Hello from A using ${deps.b.message}` }; }\n// Understanding the cache:\nconst mod1 = require('./someModule');\nconst mod2 = require('./someModule'); // same object - cached\nconsole.log(mod1 === mod2); // true\n// Force reload (not recommended):\ndelete require.cache[require.resolve('./someModule')];\nconst fresh = require('./someModule');",hints:"Node.js caches modules on first require(). Circular deps get partial exports. Lazy require defers resolution to call time.",solutionExplanation:"Module cache (require.cache) stores modules by filename. Circular deps get incomplete exports at require time. Lazy require or DI are clean solutions."},
  {lessonId:39,difficulty:"Hard",title:"WebSocket Server",problemStatement:"Build a WebSocket server using the 'ws' library. Support rooms, broadcast to room, and handle disconnections.",examples:"client.join('room1'). server broadcasts to all clients in 'room1'.",starterCodeJs:"const WebSocket = require('ws');\nconst http = require('http');\nconst server = http.createServer();\nconst wss = new WebSocket.Server({ server });\nconst rooms = new Map(); // roomName -> Set<WebSocket>\nwss.on('connection', (ws, req) => {\n  let currentRoom = null;\n  ws.on('message', data => {\n    try {\n      const msg = JSON.parse(data);\n      switch (msg.type) {\n        case 'join':\n          if (currentRoom) rooms.get(currentRoom)?.delete(ws);\n          currentRoom = msg.room;\n          if (!rooms.has(currentRoom)) rooms.set(currentRoom, new Set());\n          rooms.get(currentRoom).add(ws);\n          broadcast(currentRoom, { type:'joined', user: msg.user, room: currentRoom }, ws);\n          break;\n        case 'message':\n          if (currentRoom) broadcast(currentRoom, { type:'message', user: msg.user, text: msg.text });\n          break;\n      }\n    } catch {}\n  });\n  ws.on('close', () => { if (currentRoom) rooms.get(currentRoom)?.delete(ws); });\n});\nfunction broadcast(room, data, exclude = null) {\n  const str = JSON.stringify(data);\n  rooms.get(room)?.forEach(client => { if (client !== exclude && client.readyState === WebSocket.OPEN) client.send(str); });\n}\nserver.listen(8080);",hints:"Store rooms as Map<roomName, Set<WebSocket>>. Remove from room on disconnect. Check readyState===OPEN before sending.",solutionExplanation:"WebSocket rooms: a Map of Sets. broadcast() iterates the Set and sends to open connections. Cleanup on close prevents sending to dead connections."},
  {lessonId:39,difficulty:"Easy",title:"Environment Variable Validation",problemStatement:"Write a startup validation function that checks all required environment variables at app start and prints a helpful error if any are missing.",examples:"validateEnv(['DATABASE_URL','JWT_SECRET','PORT']) -> throws listing all missing vars",starterCodeJs:"function validateEnv(required, optional = {}) {\n  const missing = [];\n  const warnings = [];\n  for (const key of required) {\n    if (!process.env[key]) missing.push(key);\n  }\n  for (const [key, defaultVal] of Object.entries(optional)) {\n    if (!process.env[key]) {\n      process.env[key] = defaultVal;\n      warnings.push(`${key} not set, using default: ${defaultVal}`);\n    }\n  }\n  if (warnings.length) console.warn('ENV warnings:\\n' + warnings.map(w=>'  - '+w).join('\\n'));\n  if (missing.length) {\n    console.error('Missing required environment variables:\\n' + missing.map(k=>'  - '+k).join('\\n'));\n    process.exit(1);\n  }\n}\nvalidateEnv(\n  ['DATABASE_URL', 'JWT_SECRET'],\n  { PORT: '3000', NODE_ENV: 'development', LOG_LEVEL: 'info' }\n);",hints:"Check all required vars before throwing so the error lists all missing ones at once. Set defaults for optional vars in process.env.",solutionExplanation:"Fail-fast with clear error message lists ALL missing vars (not just the first). Setting defaults in process.env makes them available to subsequent code."},
  {lessonId:39,difficulty:"Medium",title:"Simple Job Queue",problemStatement:"Build an in-memory job queue with concurrency control. Jobs are async functions. Limit concurrent execution to N jobs.",examples:"queue.add(async()=>fetchData()). queue.concurrency = 3. queue waits when 3 jobs running.",starterCodeJs:"class JobQueue {\n  constructor({ concurrency = 1, onError } = {}) {\n    this.concurrency = concurrency;\n    this._queue = [];\n    this._running = 0;\n    this._onError = onError || console.error;\n  }\n  add(job, priority = 0) {\n    return new Promise((resolve, reject) => {\n      this._queue.push({ job, priority, resolve, reject });\n      this._queue.sort((a,b) => b.priority - a.priority);\n      this._next();\n    });\n  }\n  _next() {\n    while (this._running < this.concurrency && this._queue.length) {\n      const { job, resolve, reject } = this._queue.shift();\n      this._running++;\n      Promise.resolve(job()).then(resolve).catch(reject).finally(() => {\n        this._running--;\n        this._next();\n      });\n    }\n  }\n  get pending() { return this._queue.length; }\n  get active() { return this._running; }\n  clear() { const q = this._queue.splice(0); q.forEach(({reject})=>reject(new Error('Queue cleared'))); }\n}",hints:"while loop in _next starts jobs up to concurrency limit. finally decrements running and calls _next again. Priority sort on insertion.",solutionExplanation:"Concurrency control: track running count, start next job from queue when running < limit. Promise-based so callers can await individual jobs."},

  // Lesson 40 - Node.js Databases
  {lessonId:40,difficulty:"Easy",title:"SQLite Query Builder",problemStatement:"Write a simple query builder class for SQLite using better-sqlite3. Support select, where, orderBy, limit, and insert.",examples:"db.table('users').where('age > ?', 18).orderBy('name').limit(10).select()",starterCodeJs:"const Database = require('better-sqlite3');\nclass QueryBuilder {\n  constructor(db, tableName) {\n    this._db = db;\n    this._table = tableName;\n    this._wheres = [];\n    this._params = [];\n    this._order = null;\n    this._limit = null;\n  }\n  where(condition, ...params) { this._wheres.push(condition); this._params.push(...params); return this; }\n  orderBy(col, dir = 'ASC') { this._order = `${col} ${dir}`; return this; }\n  limit(n) { this._limit = n; return this; }\n  _buildSelect() {\n    let sql = `SELECT * FROM ${this._table}`;\n    if (this._wheres.length) sql += ` WHERE ${this._wheres.join(' AND ')}`;\n    if (this._order) sql += ` ORDER BY ${this._order}`;\n    if (this._limit) sql += ` LIMIT ${this._limit}`;\n    return sql;\n  }\n  select() { return this._db.prepare(this._buildSelect()).all(...this._params); }\n  first() { return this._db.prepare(this._buildSelect() + ' LIMIT 1').get(...this._params); }\n  insert(data) {\n    const cols = Object.keys(data).join(',');\n    const placeholders = Object.keys(data).map(()=>'?').join(',');\n    return this._db.prepare(`INSERT INTO ${this._table} (${cols}) VALUES (${placeholders})`).run(...Object.values(data));\n  }\n}",hints:"Chainable methods return this. Collect conditions and build SQL string at query time. better-sqlite3 is synchronous.",solutionExplanation:"Builder pattern: collect configuration via chained calls, execute on terminal method (select/insert). Parameterized queries prevent SQL injection."},
  {lessonId:40,difficulty:"Medium",title:"Connection Pool Implementation",problemStatement:"Build a database connection pool that manages a set of connections. Connections are checked out and returned. Handles timeout and max wait.",examples:"pool.acquire() returns a connection. pool.release(conn) returns it to pool.",starterCodeJs:"class ConnectionPool {\n  constructor({ create, destroy, max = 10, idleTimeoutMs = 30000, acquireTimeoutMs = 5000 }) {\n    this._create = create;\n    this._destroy = destroy;\n    this._max = max;\n    this._idleTimeout = idleTimeoutMs;\n    this._acquireTimeout = acquireTimeoutMs;\n    this._pool = [];\n    this._waiting = [];\n    this._count = 0;\n  }\n  async acquire() {\n    // Check for idle connection\n    const idle = this._pool.pop();\n    if (idle) { clearTimeout(idle._idleTimer); return idle.conn; }\n    // Create new if under max\n    if (this._count < this._max) {\n      this._count++;\n      try { return await this._create(); } catch(e) { this._count--; throw e; }\n    }\n    // Wait for a connection to be released\n    return new Promise((resolve, reject) => {\n      const timer = setTimeout(() => {\n        const i = this._waiting.findIndex(w=>w.resolve===resolve);\n        if (i>=0) this._waiting.splice(i,1);\n        reject(new Error('Connection pool timeout'));\n      }, this._acquireTimeout);\n      this._waiting.push({ resolve: conn => { clearTimeout(timer); resolve(conn); }, reject });\n    });\n  }\n  release(conn) {\n    if (this._waiting.length) { this._waiting.shift().resolve(conn); return; }\n    const idleTimer = setTimeout(() => { this._destroy(conn); this._count--; }, this._idleTimeout);\n    this._pool.push({ conn, _idleTimer: idleTimer });\n  }\n}",hints:"LIFO (pop) for idle connections keeps recently used warm. If max reached, queue waiters. Release pops waiter or returns to idle pool.",solutionExplanation:"Pool pattern: reuse expensive connections. Idle timeout destroys unused connections. Waiter queue handles all-connections-busy case with timeout."},
  {lessonId:40,difficulty:"Medium",title:"Database Migration System",problemStatement:"Build a simple migration system that tracks which migrations have run, runs new ones in order, and supports rollback.",examples:"migrate up -> runs pending migrations. migrate down -> rolls back last migration.",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nclass MigrationRunner {\n  constructor(db, migrationsDir) {\n    this._db = db;\n    this._dir = migrationsDir;\n    this._db.exec(`CREATE TABLE IF NOT EXISTS _migrations (id TEXT PRIMARY KEY, ran_at TEXT)`);\n  }\n  _getRan() { return new Set(this._db.prepare('SELECT id FROM _migrations').all().map(r=>r.id)); }\n  _getFiles() {\n    return fs.readdirSync(this._dir).filter(f=>f.endsWith('.sql')).sort();\n  }\n  async up() {\n    const ran = this._getRan();\n    const pending = this._getFiles().filter(f => !ran.has(f));\n    for (const file of pending) {\n      console.log(`Running migration: ${file}`);\n      const sql = fs.readFileSync(path.join(this._dir, file), 'utf8');\n      const upSQL = sql.split('-- DOWN')[0].replace('-- UP', '');\n      this._db.exec(upSQL);\n      this._db.prepare('INSERT INTO _migrations VALUES (?,?)').run(file, new Date().toISOString());\n      console.log(`Done: ${file}`);\n    }\n    if (!pending.length) console.log('No pending migrations');\n  }\n  down(steps = 1) {\n    const ran = this._db.prepare('SELECT id FROM _migrations ORDER BY ran_at DESC LIMIT ?').all(steps);\n    for (const {id} of ran) {\n      const sql = fs.readFileSync(path.join(this._dir, id), 'utf8');\n      const downSQL = sql.split('-- DOWN')[1];\n      if (downSQL) { this._db.exec(downSQL); this._db.prepare('DELETE FROM _migrations WHERE id=?').run(id); }\n    }\n  }\n}",hints:"Track ran migrations in _migrations table. Sort files by name (timestamp prefix). Split migration file on -- DOWN comment for rollback SQL.",solutionExplanation:"Migration system: idempotent (skip already-ran), ordered (sort by filename), tracked (metadata table). Split SQL files allow up/down in one file."},
  {lessonId:40,difficulty:"Easy",title:"Repository Pattern",problemStatement:"Implement the repository pattern for a User entity. Abstract all database operations behind a consistent interface.",examples:"userRepo.findById(1). userRepo.findByEmail('a@b.com'). userRepo.create({name,email}). userRepo.update(1, {...}).",starterCodeJs:"class UserRepository {\n  constructor(db) { this._db = db; }\n  async findById(id) { return this._db.get('SELECT * FROM users WHERE id = ?', id); }\n  async findByEmail(email) { return this._db.get('SELECT * FROM users WHERE email = ?', email); }\n  async findAll(options = {}) {\n    const { limit = 50, offset = 0, orderBy = 'created_at', order = 'DESC' } = options;\n    return this._db.all(`SELECT * FROM users ORDER BY ${orderBy} ${order} LIMIT ? OFFSET ?`, limit, offset);\n  }\n  async create(data) {\n    const { lastID } = await this._db.run('INSERT INTO users (name,email,password_hash,role) VALUES (?,?,?,?)',\n      data.name, data.email, data.passwordHash, data.role || 'user');\n    return this.findById(lastID);\n  }\n  async update(id, data) {\n    const fields = Object.keys(data).map(k => `${k} = ?`).join(', ');\n    await this._db.run(`UPDATE users SET ${fields}, updated_at = CURRENT_TIMESTAMP WHERE id = ?`, ...Object.values(data), id);\n    return this.findById(id);\n  }\n  async delete(id) { return this._db.run('DELETE FROM users WHERE id = ?', id); }\n  async count() { const row = await this._db.get('SELECT COUNT(*) as count FROM users'); return row.count; }\n}",hints:"Repository abstracts the data source. If you switch from SQLite to PostgreSQL, only this class changes. Dynamic UPDATE builds field list from object keys.",solutionExplanation:"Repository pattern: encapsulate data access logic. Business logic depends on the interface, not the database. Enables testing with mock repositories."},
  {lessonId:40,difficulty:"Hard",title:"Transaction Manager",problemStatement:"Build a transaction manager for SQLite that supports nested transactions via savepoints and automatic rollback on error.",examples:"await tx(db, async (t) => { await t.run(sql); await nestedTx(t); })",starterCodeJs:"async function withTransaction(db, fn) {\n  db.prepare('BEGIN').run();\n  try {\n    const result = await fn(db);\n    db.prepare('COMMIT').run();\n    return result;\n  } catch (err) {\n    db.prepare('ROLLBACK').run();\n    throw err;\n  }\n}\nlet savepointCounter = 0;\nasync function withSavepoint(db, fn) {\n  const name = `sp_${++savepointCounter}`;\n  db.prepare(`SAVEPOINT ${name}`).run();\n  try {\n    const result = await fn(db);\n    db.prepare(`RELEASE SAVEPOINT ${name}`).run();\n    return result;\n  } catch (err) {\n    db.prepare(`ROLLBACK TO SAVEPOINT ${name}`).run();\n    throw err;\n  }\n}\n// Unified: use savepoint if already in transaction\nasync function tx(db, fn) {\n  const inTx = db.inTransaction; // better-sqlite3 property\n  if (inTx) return withSavepoint(db, fn);\n  return withTransaction(db, fn);\n}",hints:"SQLite savepoints enable nested transactions. db.inTransaction (better-sqlite3) detects if already in a transaction. RELEASE SAVEPOINT commits nested work.",solutionExplanation:"Savepoints are nested transaction markers. ROLLBACK TO SAVEPOINT only undoes work since that savepoint. Combining both handles any nesting depth."},
  {lessonId:40,difficulty:"Hard",title:"Database Seeder with Faker",problemStatement:"Write a database seeder that creates realistic test data using faker.js. Maintain referential integrity (users before posts before comments).",examples:"seed({ users: 50, postsPerUser: 5, commentsPerPost: 3 }) creates 50 users, 250 posts, 750 comments",starterCodeJs:"const { faker } = require('@faker-js/faker');\nasync function seed(db, options = {}) {\n  const { users: numUsers = 20, postsPerUser = 3, commentsPerPost = 2 } = options;\n  console.log('Seeding database...');\n  const userIds = [];\n  for (let i = 0; i < numUsers; i++) {\n    const result = await db.user.create({ data: {\n      name: faker.person.fullName(),\n      email: faker.internet.email().toLowerCase(),\n      avatar: faker.image.avatar(),\n      bio: faker.lorem.sentence(),\n      role: faker.helpers.arrayElement(['user','user','user','admin']),\n      createdAt: faker.date.past({ years: 2 })\n    }});\n    userIds.push(result.id);\n  }\n  const postIds = [];\n  for (const userId of userIds) {\n    for (let i = 0; i < postsPerUser; i++) {\n      const post = await db.post.create({ data: {\n        title: faker.lorem.sentence(),\n        body: faker.lorem.paragraphs(3),\n        authorId: userId,\n        published: faker.datatype.boolean({ probability: 0.8 }),\n        createdAt: faker.date.past({ years: 1 })\n      }});\n      postIds.push(post.id);\n    }\n  }\n  for (const postId of postIds) {\n    for (let i = 0; i < commentsPerPost; i++) {\n      await db.comment.create({ data: {\n        body: faker.lorem.sentence(),\n        postId,\n        authorId: faker.helpers.arrayElement(userIds),\n        createdAt: faker.date.recent({ days: 30 })\n      }});\n    }\n  }\n  console.log(`Seeded: ${numUsers} users, ${postIds.length} posts, ${postIds.length*commentsPerPost} comments`);\n}",hints:"Create in dependency order: users -> posts -> comments. faker.helpers.arrayElement picks random item from array. faker.date.past for historical data.",solutionExplanation:"Referential integrity requires ordered seeding. Store created IDs to use as foreign keys. Faker provides realistic data for all common data types."},
  {lessonId:40,difficulty:"Medium",title:"Caching Layer with Redis-like Map",problemStatement:"Build an in-memory cache layer (Redis-like) with TTL, get/set/del, pattern matching, and LRU eviction.",examples:"cache.set('user:1', data, 60) expires in 60s. cache.get('user:1'). cache.keys('user:*').",starterCodeJs:"class Cache {\n  constructor({ maxSize = 1000 } = {}) {\n    this._store = new Map(); // LRU: Map preserves insertion order\n    this._maxSize = maxSize;\n  }\n  set(key, value, ttlSeconds = null) {\n    this._store.delete(key); // delete to re-insert at end (LRU)\n    if (this._store.size >= this._maxSize) {\n      const firstKey = this._store.keys().next().value;\n      this._store.delete(firstKey);\n    }\n    this._store.set(key, { value, expiresAt: ttlSeconds ? Date.now() + ttlSeconds * 1000 : null });\n  }\n  get(key) {\n    const entry = this._store.get(key);\n    if (!entry) return null;\n    if (entry.expiresAt && Date.now() > entry.expiresAt) { this._store.delete(key); return null; }\n    this._store.delete(key); this._store.set(key, entry); // move to end (LRU)\n    return entry.value;\n  }\n  del(key) { return this._store.delete(key); }\n  keys(pattern) {\n    const regex = new RegExp('^' + pattern.replace(/\\*/g, '.*') + '$');\n    return [...this._store.keys()].filter(k => regex.test(k));\n  }\n  flush() { this._store.clear(); }\n}",hints:"Map preserves insertion order. LRU: delete+re-insert on get/set moves key to 'end'. Evict from 'front' (oldest). Convert glob pattern to RegExp.",solutionExplanation:"LRU via Map ordering: Map.keys() iterates insertion order. Re-inserting on access moves to back. First key() is least recently used, evicted first."},
  {lessonId:40,difficulty:"Easy",title:"CSV to Database Importer",problemStatement:"Build a CSV importer that reads a large CSV file using streams, validates each row, and batch inserts into a database.",examples:"import('./users.csv', db) reads in chunks of 500, validates, inserts batch.",starterCodeJs:"const fs = require('fs');\nconst readline = require('readline');\nasync function importCSV(filePath, db, options = {}) {\n  const { batchSize = 500, validate, onProgress } = options;\n  const rl = readline.createInterface({ input: fs.createReadStream(filePath), crlfDelay: Infinity });\n  let headers = null;\n  let batch = [];\n  let total = 0;\n  let errors = 0;\n  for await (const line of rl) {\n    if (!line.trim()) continue;\n    const values = line.split(',').map(v => v.trim().replace(/^\"|\"$/g, ''));\n    if (!headers) { headers = values; continue; }\n    const row = Object.fromEntries(headers.map((h,i) => [h, values[i]]));\n    if (validate) { const err = validate(row); if (err) { errors++; continue; } }\n    batch.push(row);\n    if (batch.length >= batchSize) {\n      await db.insertMany(batch);\n      total += batch.length;\n      if (onProgress) onProgress(total);\n      batch = [];\n    }\n  }\n  if (batch.length) { await db.insertMany(batch); total += batch.length; }\n  return { total, errors };\n}",hints:"readline with for-await reads line by line without loading entire file. Batch insert reduces round trips. Strip quotes from CSV values.",solutionExplanation:"Streaming CSV: readline createInterface reads line by line. Batch 500 rows before inserting (1 insert vs 500). for-await works with AsyncIterator."}
];

async function main() {
  let qi = 0, qs = 0, ci = 0, cs = 0;
  for (const q of quizQuestions) {
    const exists = await p.quizQuestion.findFirst({ where: { lessonId: q.lessonId, question: q.question } });
    if (!exists) { await p.quizQuestion.create({ data: q }); qi++; } else qs++;
  }
  for (const q of codingQuestions) {
    const exists = await p.practiceQuestion.findFirst({ where: { lessonId: q.lessonId, title: q.title } });
    if (!exists) { await p.practiceQuestion.create({ data: q }); ci++; } else cs++;
  }
  console.log(`Quiz: ${qi} inserted, ${qs} skipped. Coding: ${ci} inserted, ${cs} skipped.`);
}

main().catch(console.error).finally(() => p.$disconnect());
