// Seed: Quiz + Coding questions for lessons 1-10 (HTML module)
const { PrismaClient } = require('@prisma/client')
const p = new PrismaClient()

const quiz = [
  // Lesson 1: HTML Fundamentals
  { lessonId:1, sortOrder:1, difficulty:'Easy', question:'What does HTML stand for?', options:['HyperText Markup Language','High Tech Modern Language','HyperText Modern Language','Home Tool Markup Language'], correctAnswer:0, explanation:'HTML stands for HyperText Markup Language — the standard language for creating web pages.' },
  { lessonId:1, sortOrder:2, difficulty:'Easy', question:'Which tag is used for the largest heading in HTML?', options:['<h6>','<heading>','<h1>','<head>'], correctAnswer:2, explanation:'<h1> defines the most important/largest heading. Headings go from <h1> (largest) to <h6> (smallest).' },
  { lessonId:1, sortOrder:3, difficulty:'Easy', question:'What is the correct HTML element for a paragraph?', options:['<para>','<p>','<pg>','<text>'], correctAnswer:1, explanation:'<p> defines a paragraph in HTML.' },
  { lessonId:1, sortOrder:4, difficulty:'Easy', question:'Which attribute specifies a unique id for an HTML element?', options:['class','name','id','key'], correctAnswer:2, explanation:'The id attribute specifies a unique identifier for an element, used by CSS and JavaScript.' },
  { lessonId:1, sortOrder:5, difficulty:'Medium', question:'What is the purpose of the <!DOCTYPE html> declaration?', options:['It links CSS files','It tells the browser to use HTML5 standards mode','It defines the document title','It creates an HTML comment'], correctAnswer:1, explanation:'<!DOCTYPE html> instructs the browser to use HTML5 standards mode, preventing quirks mode rendering.' },
  { lessonId:1, sortOrder:6, difficulty:'Medium', question:'Which HTML element contains metadata about the document?', options:['<meta>','<body>','<head>','<header>'], correctAnswer:2, explanation:'The <head> element contains metadata like <title>, <meta>, <link>, and <script> tags.' },
  { lessonId:1, sortOrder:7, difficulty:'Medium', question:'What is the correct syntax for an HTML comment?', options:['// comment','/* comment */','<!-- comment -->','** comment **'], correctAnswer:2, explanation:'HTML comments use <!-- to open and --> to close.' },
  { lessonId:1, sortOrder:8, difficulty:'Medium', question:'Which attribute makes an input field required in HTML5?', options:['validate','mandatory','required','must'], correctAnswer:2, explanation:'The required attribute on an <input> element prevents form submission if the field is empty.' },
  { lessonId:1, sortOrder:9, difficulty:'Hard', question:'What is the difference between <b> and <strong>?', options:['They are identical','<b> is bold for styling; <strong> indicates semantic importance','<strong> is deprecated','<b> adds more weight than <strong>'], correctAnswer:1, explanation:'<b> is purely visual (bold). <strong> carries semantic meaning — screen readers may emphasize it.' },
  { lessonId:1, sortOrder:10, difficulty:'Hard', question:'Which of these is a void (self-closing) element?', options:['<div>','<span>','<br>','<p>'], correctAnswer:2, explanation:'Void elements like <br>, <img>, <input> have no closing tag because they cannot have child content.' },

  // Lesson 2: Semantic HTML
  { lessonId:2, sortOrder:1, difficulty:'Easy', question:'Which element represents the main navigation of a page?', options:['<menu>','<nav>','<ul>','<navigation>'], correctAnswer:1, explanation:'<nav> is the semantic element for site navigation links.' },
  { lessonId:2, sortOrder:2, difficulty:'Easy', question:'What is the purpose of the <article> element?', options:['Displays an image','A self-contained piece of content that could stand alone','A sidebar widget','A form section'], correctAnswer:1, explanation:'<article> is for self-contained content like a blog post, news article, or forum post.' },
  { lessonId:2, sortOrder:3, difficulty:'Easy', question:'Which element should wrap the main content of a page?', options:['<section>','<content>','<main>','<body>'], correctAnswer:2, explanation:'<main> contains the dominant content of the document, unique to that page.' },
  { lessonId:2, sortOrder:4, difficulty:'Medium', question:'What is the difference between <section> and <div>?', options:['No difference','<section> has semantic meaning (a thematic group); <div> is purely for layout','<div> is semantic; <section> is not','<section> can only appear once per page'], correctAnswer:1, explanation:'<section> groups related thematic content and is meaningful to accessibility tools. <div> is a generic layout container.' },
  { lessonId:2, sortOrder:5, difficulty:'Medium', question:'Which element is used for a sidebar or related content?', options:['<sidebar>','<aside>','<secondary>','<extra>'], correctAnswer:1, explanation:'<aside> represents content tangentially related to the surrounding content, like a sidebar.' },
  { lessonId:2, sortOrder:6, difficulty:'Medium', question:'What should the <footer> element contain?', options:['Only copyright text','Navigation links only','Author info, copyright, links — metadata about the section','The page title'], correctAnswer:2, explanation:'<footer> contains information about its nearest ancestor section: author, copyright, links, etc.' },
  { lessonId:2, sortOrder:7, difficulty:'Medium', question:'Which element represents a figure with an optional caption?', options:['<img>','<picture>','<figure>','<media>'], correctAnswer:2, explanation:'<figure> wraps self-contained media (images, diagrams, code). <figcaption> provides its caption.' },
  { lessonId:2, sortOrder:8, difficulty:'Hard', question:'When should you use <header> vs <h1>?', options:['They are interchangeable','<header> is a structural container (can hold h1, nav, logo); <h1> is a text heading element','<h1> is deprecated','<header> replaces all headings'], correctAnswer:1, explanation:'<header> is a section container. <h1> is the heading text itself. A <header> often contains an <h1> plus other introductory content.' },
  { lessonId:2, sortOrder:9, difficulty:'Hard', question:'How many <main> elements should a page have?', options:['As many as needed','Two maximum','Exactly one','Zero — it is optional'], correctAnswer:2, explanation:'Each page should have exactly one <main> element. Multiple <main> elements are invalid HTML.' },
  { lessonId:2, sortOrder:10, difficulty:'Hard', question:'Which element marks up a date/time value machine-readably?', options:['<date>','<time>','<calendar>','<datetime>'], correctAnswer:1, explanation:'<time datetime="2024-01-15"> provides a machine-readable date alongside human-readable text.' },

  // Lesson 3: Accessibility
  { lessonId:3, sortOrder:1, difficulty:'Easy', question:'What does the alt attribute on <img> provide?', options:['Image title shown on hover','Alternative text for screen readers and broken images','Image caption','SEO keyword'], correctAnswer:1, explanation:'alt text is read by screen readers for blind users and shown when the image fails to load.' },
  { lessonId:3, sortOrder:2, difficulty:'Easy', question:'What is ARIA?', options:['A CSS framework','Accessible Rich Internet Applications — attributes that enhance accessibility','A JavaScript library','A browser API'], correctAnswer:1, explanation:'ARIA (Accessible Rich Internet Applications) attributes add semantic information for assistive technologies.' },
  { lessonId:3, sortOrder:3, difficulty:'Easy', question:'Which HTML element associates a label with a form input?', options:['<caption>','<label>','<description>','<hint>'], correctAnswer:1, explanation:'<label for="id"> associates text with an input, improving click target and screen reader experience.' },
  { lessonId:3, sortOrder:4, difficulty:'Medium', question:'What does role="button" accomplish on a <div>?', options:['Styles it as a button','Tells assistive tech it behaves like a button','Makes it clickable','Adds keyboard support automatically'], correctAnswer:1, explanation:'role="button" informs screen readers the element is a button — but you must also add keyboard handlers manually.' },
  { lessonId:3, sortOrder:5, difficulty:'Medium', question:'What does tabindex="0" do?', options:['Removes element from tab order','Makes element first in tab order','Includes element in natural tab order','Sets tab stop position to zero'], correctAnswer:2, explanation:'tabindex="0" adds an element to the natural keyboard tab order without specifying a specific position.' },
  { lessonId:3, sortOrder:6, difficulty:'Medium', question:'Which ARIA attribute announces live content updates?', options:['aria-live','aria-update','aria-announce','aria-notify'], correctAnswer:0, explanation:'aria-live="polite" or "assertive" tells screen readers to announce dynamic content changes.' },
  { lessonId:3, sortOrder:7, difficulty:'Medium', question:'What is the minimum recommended color contrast ratio for normal text (WCAG AA)?', options:['2:1','3:1','4.5:1','7:1'], correctAnswer:2, explanation:'WCAG AA requires a 4.5:1 contrast ratio for normal text and 3:1 for large text (18pt+).' },
  { lessonId:3, sortOrder:8, difficulty:'Hard', question:'What is the purpose of aria-describedby?', options:['Adds a visible tooltip','Links an element to a longer description read by screen readers','Sets the element label','Hides element from screen readers'], correctAnswer:1, explanation:'aria-describedby points to an element whose text provides additional description for the current element.' },
  { lessonId:3, sortOrder:9, difficulty:'Hard', question:'Which approach correctly hides content visually but keeps it accessible to screen readers?', options:['display:none','visibility:hidden','position:absolute; clip:rect(0,0,0,0); width:1px; height:1px','opacity:0'], correctAnswer:2, explanation:'The "visually hidden" CSS technique keeps content in the accessibility tree while hiding it visually. display:none and visibility:hidden remove it from both.' },
  { lessonId:3, sortOrder:10, difficulty:'Hard', question:'What does aria-hidden="true" do?', options:['Hides element visually','Makes element invisible to screen readers only','Removes element from DOM','Focuses the element'], correctAnswer:1, explanation:'aria-hidden="true" removes the element from the accessibility tree but keeps it visually visible — useful for decorative icons.' },

  // Lesson 4: Forms & Validation
  { lessonId:4, sortOrder:1, difficulty:'Easy', question:'Which input type shows a date picker in modern browsers?', options:['type="calendar"','type="date"','type="datetime"','type="day"'], correctAnswer:1, explanation:'<input type="date"> renders a native date picker UI in supporting browsers.' },
  { lessonId:4, sortOrder:2, difficulty:'Easy', question:'What attribute prevents a form from submitting if a field is empty?', options:['validate','notnull','required','must-fill'], correctAnswer:2, explanation:'The required attribute triggers browser-native validation, blocking submission when the field is empty.' },
  { lessonId:4, sortOrder:3, difficulty:'Easy', question:'Which element groups related form fields together?', options:['<group>','<fieldset>','<section>','<formgroup>'], correctAnswer:1, explanation:'<fieldset> groups related inputs; <legend> provides a caption for the group.' },
  { lessonId:4, sortOrder:4, difficulty:'Medium', question:'What does the pattern attribute on an input do?', options:['Applies CSS styling','Validates input against a regex','Sets placeholder text','Restricts character count'], correctAnswer:1, explanation:'pattern accepts a regex. The browser validates the input value against it on form submission.' },
  { lessonId:4, sortOrder:5, difficulty:'Medium', question:'Which input type prevents the user from entering a value outside a range?', options:['type="number" with min/max','type="limit"','type="range" only','type="bounded"'], correctAnswer:0, explanation:'type="number" with min and max attributes restricts the allowed numeric range.' },
  { lessonId:4, sortOrder:6, difficulty:'Medium', question:'What does autocomplete="off" do on a form?', options:['Disables spellcheck','Prevents browser from auto-filling saved values','Disables form submission','Removes input validation'], correctAnswer:1, explanation:'autocomplete="off" asks the browser not to pre-fill the field with previously saved data.' },
  { lessonId:4, sortOrder:7, difficulty:'Medium', question:'Which method should a login form use?', options:['GET','POST','PUT','PATCH'], correctAnswer:1, explanation:'POST sends credentials in the request body (not visible in the URL), making it appropriate for sensitive data.' },
  { lessonId:4, sortOrder:8, difficulty:'Hard', question:'What is the purpose of enctype="multipart/form-data"?', options:['Encrypts form data','Required when uploading files in a form','Encodes special characters','Enables AJAX submission'], correctAnswer:1, explanation:'multipart/form-data encoding is required for file uploads so binary data is transmitted correctly.' },
  { lessonId:4, sortOrder:9, difficulty:'Hard', question:'Which constraint validation API method checks if an input is valid?', options:['input.isValid()','input.checkValidity()','input.validate()','input.verify()'], correctAnswer:1, explanation:'checkValidity() returns true if the element passes all constraint validation rules.' },
  { lessonId:4, sortOrder:10, difficulty:'Hard', question:'What is the novalidate attribute on a <form> used for?', options:['Makes all fields optional','Disables browser native validation so you can handle it in JS','Removes all required attributes','Prevents form submission'], correctAnswer:1, explanation:'novalidate disables the built-in browser validation UI, letting you implement custom JS validation instead.' },

  // Lesson 5: Tables
  { lessonId:5, sortOrder:1, difficulty:'Easy', question:'Which element defines a table row?', options:['<td>','<tr>','<row>','<th>'], correctAnswer:1, explanation:'<tr> (table row) wraps all cells in a single horizontal row.' },
  { lessonId:5, sortOrder:2, difficulty:'Easy', question:'What is the difference between <th> and <td>?', options:['No difference','<th> is a header cell (bold, centered by default); <td> is a data cell','<td> is the header','<th> can only appear in <thead>'], correctAnswer:1, explanation:'<th> marks header cells and carries semantic meaning for screen readers. <td> holds data.' },
  { lessonId:5, sortOrder:3, difficulty:'Easy', question:'Which element contains the table header rows?', options:['<thead>','<th>','<header>','<tgroup>'], correctAnswer:0, explanation:'<thead> groups the header rows of a table, helping browsers and screen readers identify them.' },
  { lessonId:5, sortOrder:4, difficulty:'Medium', question:'What does the colspan attribute do?', options:['Sets column width','Makes a cell span multiple columns','Merges table rows','Aligns cell content'], correctAnswer:1, explanation:'colspan="N" makes a cell span N columns horizontally.' },
  { lessonId:5, sortOrder:5, difficulty:'Medium', question:'Which element provides a table caption for accessibility?', options:['<title>','<summary>','<caption>','<label>'], correctAnswer:2, explanation:'<caption> provides a visible title for the table, read first by screen readers to describe its purpose.' },
  { lessonId:5, sortOrder:6, difficulty:'Medium', question:'What attribute on <th> associates headers with data cells for screen readers?', options:['id + headers','scope','aria-label','for'], correctAnswer:1, explanation:'scope="col" or scope="row" on <th> tells screen readers which cells the header applies to.' },
  { lessonId:5, sortOrder:7, difficulty:'Medium', question:'When should you NOT use an HTML table?', options:['For financial data','For comparison grids','For page layout','For schedule data'], correctAnswer:2, explanation:'Tables are for tabular data only. Using them for layout is an accessibility and maintainability anti-pattern.' },
  { lessonId:5, sortOrder:8, difficulty:'Hard', question:'What does <tfoot> do and where does it render?', options:['Renders at the bottom visually but can appear anywhere in HTML','Must be placed at the bottom of the table HTML','Is deprecated in HTML5','Is the same as <tbody>'], correctAnswer:0, explanation:'<tfoot> semantically marks footer rows. Browsers render it at the bottom regardless of its position in the markup.' },
  { lessonId:5, sortOrder:9, difficulty:'Hard', question:'How do you make a cell span 2 rows?', options:['rowspan="2"','colspan="2" on the row','height="2"','rowmerge="2"'], correctAnswer:0, explanation:'rowspan="2" makes a cell span 2 rows vertically.' },
  { lessonId:5, sortOrder:10, difficulty:'Hard', question:'Which element defines column-level styling for a table?', options:['<col>','<column>','<colstyle>','<tc>'], correctAnswer:0, explanation:'<col> inside <colgroup> applies styles to entire columns without repeating styles on each cell.' },
]

const coding = [
  // Lesson 1: HTML Fundamentals
  { lessonId:1, difficulty:'Easy', topic:'HTML', title:'Build a Valid HTML5 Boilerplate', problemStatement:'Create a complete, valid HTML5 document with: DOCTYPE declaration, html lang attribute, head with charset meta and title "My Page", and a body containing an h1 "Hello World" and a paragraph.', examples:'Expected output: A valid HTML5 file that passes W3C validation.', starterCodeJs:'// Write the HTML structure as a string and return it\nfunction buildHTML() {\n  return `\n    <!DOCTYPE html>\n    <!-- complete the structure -->\n  `;\n}', hints:'["Start with <!DOCTYPE html>", "Add lang attribute to <html>", "Include charset meta tag in head"]', solutionExplanation:'A valid HTML5 doc always starts with <!DOCTYPE html>, followed by <html lang="en">, <head> with <meta charset="UTF-8"> and <title>, then <body>.' },
  { lessonId:1, difficulty:'Easy', topic:'HTML', title:'Heading Hierarchy', problemStatement:'Create an HTML snippet with all 6 heading levels (h1-h6), each containing the text "Heading N" where N is the level number.', examples:'<h1>Heading 1</h1>... <h6>Heading 6</h6>', starterCodeJs:'function buildHeadings() {\n  // Return an HTML string with h1 through h6\n  return "";\n}', hints:'["Use a loop from 1 to 6", "Template literal: `<h${n}>Heading ${n}</h${n}>`"]', solutionExplanation:'Heading levels communicate document outline. h1 is the page title, h2-h6 are sub-sections in order.' },
  { lessonId:1, difficulty:'Easy', topic:'HTML', title:'Ordered vs Unordered List', problemStatement:'Create a function that returns an HTML string with: an ordered list of 5 programming languages and an unordered list of 3 favourite foods.', examples:'<ol><li>JavaScript</li>...</ol><ul><li>Pizza</li>...</ul>', starterCodeJs:'function buildLists() {\n  return "";\n}', hints:'["<ol> for ordered, <ul> for unordered", "Each item wrapped in <li>"]', solutionExplanation:'<ol> creates numbered lists; <ul> creates bulleted lists. Both use <li> for each item.' },
  { lessonId:1, difficulty:'Medium', topic:'HTML', title:'Hyperlinks and Targets', problemStatement:'Write a function that returns HTML with: (1) a link to https://example.com opening in a new tab with rel="noopener noreferrer", (2) an email link, (3) a phone link.', examples:'<a href="https://example.com" target="_blank" rel="noopener noreferrer">Visit</a>', starterCodeJs:'function buildLinks() {\n  return "";\n}', hints:'["target=\"_blank\" opens new tab", "mailto: for email links", "tel: for phone links", "Always add rel=noopener when using target=_blank"]', solutionExplanation:'rel="noopener noreferrer" prevents the new page accessing window.opener (security) and hides referrer info.' },
  { lessonId:1, difficulty:'Medium', topic:'HTML', title:'Image with Fallback', problemStatement:'Create HTML for an image of a "mountain landscape" with a descriptive alt text, a width of 800, height of 400, and loading="lazy". Also add a <figure> wrapper with a <figcaption>.', examples:'<figure><img ...><figcaption>...</figcaption></figure>', starterCodeJs:'function buildImage() {\n  return "";\n}', hints:'["Use <figure> and <figcaption>", "loading=lazy for performance", "Alt text should describe the image content"]', solutionExplanation:'loading="lazy" defers image loading until near the viewport, improving initial page load.' },
  { lessonId:1, difficulty:'Medium', topic:'HTML', title:'HTML Entities', problemStatement:'Write a function that returns HTML displaying the following characters using HTML entities: &, <, >, ", © (copyright), and → (right arrow).', examples:'&amp; renders as &', starterCodeJs:'function buildEntities() {\n  // Return a paragraph showing each entity rendered\n  return "";\n}', hints:'["& = &amp;", "< = &lt;", "> = &gt;", "© = &copy;", "→ = &rarr;"]', solutionExplanation:'HTML entities encode special characters that would otherwise be parsed as HTML markup.' },
  { lessonId:1, difficulty:'Hard', topic:'HTML', title:'Nested Definition List', problemStatement:'Build a definition list (<dl>) for a mini HTML glossary containing terms: Element, Attribute, and Tag — each with a <dt> and a detailed <dd>.', examples:'<dl><dt>Element</dt><dd>An HTML element is...</dd></dl>', starterCodeJs:'function buildGlossary() {\n  return "";\n}', hints:'["<dl> wraps the whole list", "<dt> is the term", "<dd> is the definition", "Multiple <dd> per <dt> is valid"]', solutionExplanation:'<dl> is a description list. It semantically pairs terms with their definitions, used for glossaries and metadata.' },
  { lessonId:1, difficulty:'Hard', topic:'HTML', title:'Embedded Media', problemStatement:'Create an HTML snippet that embeds a YouTube video using an <iframe> with: responsive aspect-ratio wrapper, title attribute, allow="accelerometer; autoplay" and allowfullscreen.', examples:'<div class="video-wrapper"><iframe ...></iframe></div>', starterCodeJs:'function buildVideo(youtubeId) {\n  return "";\n}', hints:'["aspect-video class or padding-top:56.25%", "src: https://www.youtube.com/embed/${id}", "Always add title for accessibility"]', solutionExplanation:'Wrapping the iframe in a div with padding-top:56.25% creates a 16:9 responsive container.' },
  { lessonId:1, difficulty:'Hard', topic:'HTML', title:'Meta Tags for SEO', problemStatement:'Write a <head> section containing: charset, viewport meta, a title (max 60 chars), meta description (max 160 chars), og:title, og:description, og:image Open Graph tags.', examples:'<meta property="og:title" content="...">', starterCodeJs:'function buildHead(title, description, image) {\n  return "";\n}', hints:'["viewport meta: width=device-width, initial-scale=1", "og: tags use property attribute, not name", "Twitter cards use name attribute"]', solutionExplanation:'Open Graph meta tags control how your page appears when shared on social media (Facebook, LinkedIn, etc.).' },
  { lessonId:1, difficulty:'Hard', topic:'HTML', title:'Data Attributes', problemStatement:'Create a product card HTML element using data-* attributes: data-id, data-price, data-category, data-in-stock. Write a JS function that reads these attributes from the element.', examples:'el.dataset.price returns the price value', starterCodeJs:'function buildProductCard(id, price, category, inStock) {\n  // Return HTML string\n  return "";\n}\nfunction readProductData(el) {\n  // Read and return an object from data attributes\n  return {};\n}', hints:'["data-* attributes use kebab-case in HTML", "dataset converts to camelCase in JS", "el.dataset.dataId would be data-data-id"]', solutionExplanation:'dataset.inStock reads data-in-stock. The browser converts kebab-case HTML names to camelCase in the JS dataset API.' },

  // Lesson 2: Semantic HTML
  { lessonId:2, difficulty:'Easy', topic:'HTML', title:'Page Layout with Semantic Elements', problemStatement:'Build a complete page skeleton using only semantic HTML elements: <header>, <nav> with 3 links, <main> with an <article>, <aside>, and <footer>.', examples:'No <div> wrappers — all semantic elements.', starterCodeJs:'function buildLayout() {\n  return "";\n}', hints:'["header → nav → main → footer order", "article inside main", "aside is a sibling of article inside main"]', solutionExplanation:'Semantic structure lets screen readers and search engines understand the page without CSS context.' },
  { lessonId:2, difficulty:'Easy', topic:'HTML', title:'Article with Metadata', problemStatement:'Create an <article> for a blog post that includes: <header> with <h1> title and <time datetime="..."> for the publish date, a few paragraphs, and a <footer> with author name.', examples:'Proper date format: datetime="2024-06-15"', starterCodeJs:'function buildArticle(title, date, author) {\n  return "";\n}', hints:'["<time> datetime must be a machine-readable format", "article > header and article > footer are valid", "author info often in <address>"]', solutionExplanation:'<time datetime="2024-06-15"> gives search engines a parseable date even if the visible text says "June 15, 2024".' },
  { lessonId:2, difficulty:'Medium', topic:'HTML', title:'Navigation Landmark', problemStatement:'Build a <nav> with an aria-label="Primary" containing a logo link and 4 page links. Include an active state on the current page link using aria-current="page".', examples:'<a href="/about" aria-current="page">About</a>', starterCodeJs:'function buildNav(currentPage) {\n  return "";\n}', hints:'["aria-label distinguishes multiple navs", "aria-current=page marks active link", "Logo should be a link to home"]', solutionExplanation:'aria-current="page" tells screen readers which nav item represents the current page — better than just a CSS class.' },
  { lessonId:2, difficulty:'Medium', topic:'HTML', title:'Figure and Figcaption', problemStatement:'Create 3 <figure> elements: one with an image, one with a <pre><code> block (code listing), and one with a <table> — each with appropriate <figcaption>.', examples:'<figure><pre><code>...</code></pre><figcaption>Listing 1: ...</figcaption></figure>', starterCodeJs:'function buildFigures() {\n  return "";\n}', hints:'["<figure> is not just for images", "figcaption can be before or after the content", "Use numbered captions for reference"]', solutionExplanation:'<figure> semantically wraps any self-contained content that can be moved or referenced independently.' },
  { lessonId:2, difficulty:'Medium', topic:'HTML', title:'Section vs Article Decision', problemStatement:'Given this content: (1) A page with tabs for "Overview", "Features", "Pricing". (2) A blog listing with individual posts. Write the correct semantic HTML wrapper for each scenario and explain in a JS comment why.', examples:'Section for tabs (no standalone meaning), Article for posts (standalone content)', starterCodeJs:'function buildTabsSection() {\n  // Use <section> — related themed content\n  return "";\n}\nfunction buildBlogListing() {\n  // Use <article> for each post\n  return "";\n}', hints:'["Ask: could this content make sense extracted to another site? If yes, use article.", "Section needs a heading to be valid"]', solutionExplanation:'<article> = standalone publishable content. <section> = thematic group with a heading that is part of a larger whole.' },
  { lessonId:2, difficulty:'Hard', topic:'HTML', title:'Accessible Skip Link', problemStatement:'Implement a "Skip to main content" link that is visually hidden but becomes visible on keyboard focus, allowing keyboard users to bypass the navigation.', examples:'Link jumps to #main-content on Enter', starterCodeJs:'function buildSkipLink() {\n  // Return HTML + style for the skip link\n  return "";\n}', hints:'["Position absolute, clip to 1px normally", "On :focus, reset clip and position", "href must match the id of <main>"]', solutionExplanation:'Skip links let keyboard users bypass repetitive navigation. They must be the first focusable element on the page.' },
  { lessonId:2, difficulty:'Hard', topic:'HTML', title:'Breadcrumb Navigation', problemStatement:'Build a breadcrumb nav: Home > Courses > HTML > Lesson 2. Use <nav aria-label="Breadcrumb">, <ol>, and mark the last item with aria-current="page". The last item should not be a link.', examples:'<li><a href="/">Home</a></li>...', starterCodeJs:'function buildBreadcrumb(crumbs) {\n  // crumbs = [{label, href}] — last has no href\n  return "";\n}', hints:'["Use <ol> not <ul> — order matters", "aria-current=page on last <li>", "Separate items visually with CSS ::after or aria-hidden spans"]', solutionExplanation:'Ordered list is correct because breadcrumb order is meaningful. Structured data (Schema.org BreadcrumbList) can also be added.' },
  { lessonId:2, difficulty:'Hard', topic:'HTML', title:'Document Outline', problemStatement:'Given a blog site with a sidebar, create an HTML structure where the main article headings (h1, h2, h3) form a logical outline independent of the sidebar headings — using correct semantic nesting.', examples:'Sidebar uses its own <section> with <h2> so it does not break article outline', starterCodeJs:'function buildDocumentOutline() {\n  return "";\n}', hints:'["Each sectioning element resets heading level context", "article > h1 is valid even if page has h1 in header", "Use sectioning elements to create independent outlines"]', solutionExplanation:'HTML5 sectioning elements (article, section, aside, nav) create implicit document outline sections, each with their own heading hierarchy.' },
  { lessonId:2, difficulty:'Hard', topic:'HTML', title:'Address and Contact Info', problemStatement:'Create a contact section using <address> for an organization, with name, email (mailto:), phone (tel:), and physical address using proper sub-elements.', examples:'<address> should only contain contact info for its nearest article/body ancestor', starterCodeJs:'function buildContactSection() {\n  return "";\n}', hints:'["<address> is semantic, not just for physical addresses", "Do not put non-contact content inside <address>", "Can include <a href=mailto:> and <a href=tel:>"]', solutionExplanation:'<address> semantically marks contact information for the nearest <article> or <body>, improving machine readability.' },
  { lessonId:2, difficulty:'Easy', topic:'HTML', title:'Mark and Highlight', problemStatement:'Write HTML for a search results page where the search term "JavaScript" is highlighted in each result snippet using the appropriate semantic element.', examples:'<p>Learn <mark>JavaScript</mark> from scratch...</p>', starterCodeJs:'function highlightTerm(text, term) {\n  // Return HTML with all occurrences of term wrapped in appropriate tag\n  return "";\n}', hints:'["<mark> is for highlighting relevance", "Not <b> or <span> — use semantic element", "Use split + join or regex replace"]', solutionExplanation:'<mark> semantically marks text highlighted for reference or relevance — exactly right for search term highlighting.' },

  // Lesson 3: Accessibility
  { lessonId:3, difficulty:'Easy', topic:'Accessibility', title:'Add Alt Text to Images', problemStatement:'Write a function that takes an array of image objects {src, description, isDecorative} and returns proper <img> tags — descriptive alt for meaningful images, empty alt="" for decorative ones.', examples:'Decorative: alt="" | Meaningful: alt="A developer coding at night"', starterCodeJs:'function buildImages(images) {\n  return images.map(img => {\n    // Your code here\n    return "";\n  }).join("");\n}', hints:'["Decorative images: alt=\"\" (not missing alt)", "Never use the filename as alt text", "Describe what the image conveys, not just what it shows"]', solutionExplanation:'An empty alt="" signals to screen readers that the image is decorative and should be skipped.' },
  { lessonId:3, difficulty:'Easy', topic:'Accessibility', title:'Form Labels and Inputs', problemStatement:'Create an accessible login form with email and password fields, each with a proper <label>, placeholder, required attribute, and autocomplete attributes. Include a visible submit button.', examples:'label for="email" + input id="email"', starterCodeJs:'function buildLoginForm() {\n  return "";\n}', hints:'["autocomplete=email and autocomplete=current-password", "placeholder is not a substitute for label", "Use for/id pairing or wrap input inside label"]', solutionExplanation:'Explicit label association improves both accessibility and usability — clicking the label focuses the input.' },
  { lessonId:3, difficulty:'Medium', topic:'Accessibility', title:'Keyboard-Accessible Modal', problemStatement:'Build an accessible modal dialog that: has role="dialog" and aria-modal="true", traps focus within it when open, has an aria-labelledby pointing to the modal title, and has an aria-describedby for the modal body.', examples:'<div role="dialog" aria-modal="true" aria-labelledby="modal-title">', starterCodeJs:'function buildModal(title, body) {\n  return "";\n}\n// Also write the focus trap logic\nfunction trapFocus(modalEl) {\n  // Your JS here\n}', hints:'["Get all focusable elements: a, button, input, [tabindex]", "On Tab keydown: if last element, move focus to first", "On Shift+Tab: if first element, move to last"]', solutionExplanation:'Focus trapping prevents keyboard users from accidentally leaving the modal into hidden background content.' },
  { lessonId:3, difficulty:'Medium', topic:'Accessibility', title:'Live Region Announcements', problemStatement:'Implement a notification system where messages (success/error) are announced to screen readers without visual focus change. Use aria-live with appropriate politeness levels.', examples:'Errors should interrupt (assertive); status updates should wait (polite)', starterCodeJs:'function buildNotificationRegion() {\n  return `<div id="notifications" aria-live="polite" aria-atomic="true"></div>`;\n}\nfunction announce(message, isError = false) {\n  // Update the live region\n}', hints:'["polite = waits for user to finish speaking", "assertive = interrupts immediately", "aria-atomic=true reads entire region contents"]', solutionExplanation:'The live region must exist in the DOM before content is injected — injecting with content already inside will not trigger announcement.' },
  { lessonId:3, difficulty:'Medium', topic:'Accessibility', title:'Accessible Icon Buttons', problemStatement:'Create 3 icon-only buttons (close, share, bookmark) that are accessible to screen readers. Icons are SVG — add proper accessible names without visible text.', examples:'<button aria-label="Close dialog"><svg aria-hidden="true">...</svg></button>', starterCodeJs:'function buildIconButton(action, svgPath) {\n  return "";\n}', hints:'["Use aria-label on the button", "Hide SVG from screen readers with aria-hidden=true", "Or use <span class=sr-only> for visually hidden text"]', solutionExplanation:'aria-hidden="true" on the SVG prevents it being read twice. The button\'s aria-label provides the accessible name.' },
  { lessonId:3, difficulty:'Hard', topic:'Accessibility', title:'Accessible Data Table', problemStatement:'Build a table of students with name, grade, and score. Add: caption, scope attributes on headers, and a summary of what the table contains via aria-describedby.', examples:'<th scope="col">Name</th>', starterCodeJs:'function buildStudentTable(students) {\n  // students = [{name, grade, score}]\n  return "";\n}', hints:'["scope=col for column headers, scope=row for row headers", "<caption> is the visible title", "aria-describedby points to a description paragraph"]', solutionExplanation:'scope attributes help screen readers associate cells with their headers in complex tables.' },
  { lessonId:3, difficulty:'Hard', topic:'Accessibility', title:'Error Identification in Forms', problemStatement:'Implement form error handling that: marks invalid fields with aria-invalid="true", links error messages with aria-describedby, moves focus to the first error on submit, and announces a summary count with a live region.', examples:'<input aria-invalid="true" aria-describedby="email-error">', starterCodeJs:'function validateForm(formEl) {\n  const errors = [];\n  // Validate fields\n  // Update aria attributes\n  // Move focus\n  // Announce summary\n}', hints:'["aria-invalid=true on invalid fields", "Error message element id matches aria-describedby", "Move focus to first invalid field or error summary"]', solutionExplanation:'Moving focus to the first error ensures keyboard and screen reader users are immediately aware that validation failed.' },
  { lessonId:3, difficulty:'Hard', topic:'Accessibility', title:'Custom Select Dropdown', problemStatement:'Build an accessible custom select component using proper ARIA: role="listbox", role="option", aria-selected, aria-expanded, and full keyboard support (arrows, Enter, Escape, Home, End).', examples:'<div role="listbox" aria-expanded="true">', starterCodeJs:'function buildCustomSelect(options, label) {\n  return "";\n}\nfunction handleKeydown(e, listbox) {\n  // Arrow keys, Enter, Escape, Home, End\n}', hints:'["Button triggers listbox open/close", "aria-expanded on trigger button", "aria-selected on active option", "Arrow keys move focus between options"]', solutionExplanation:'Custom widgets must replicate all native select keyboard behaviour — missing keyboard support excludes keyboard-only users.' },
  { lessonId:3, difficulty:'Easy', topic:'Accessibility', title:'Skip Navigation Link', problemStatement:'Add a skip link that is the first element in <body>, links to #main-content, is visually hidden but visible on :focus, and uses sr-only class.', examples:'<a href="#main-content" class="sr-only focus:not-sr-only">Skip to content</a>', starterCodeJs:'function buildSkipNav() {\n  const css = `.sr-only { position:absolute; width:1px; height:1px; clip:rect(0,0,0,0); overflow:hidden; }\n.sr-only:focus { position:static; width:auto; height:auto; clip:auto; }`;\n  const html = "";\n  return { css, html };\n}', hints:'["Must be the FIRST focusable element", "On focus: remove sr-only styles to show it", "href must match an id in the page"]', solutionExplanation:'Skip links save keyboard users from tabbing through every nav link on every page — WCAG 2.4.1 Bypass Blocks.' },
  { lessonId:3, difficulty:'Medium', topic:'Accessibility', title:'Progress Bar Accessibility', problemStatement:'Create an accessible animated progress bar showing 65% completion, using role="progressbar", aria-valuenow, aria-valuemin, aria-valuemax, and a visible label.', examples:'<div role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">', starterCodeJs:'function buildProgressBar(value, label) {\n  return "";\n}', hints:'["aria-valuenow is the current value", "aria-valuetext can provide a human description", "Visual bar width = value% of container"]', solutionExplanation:'Without ARIA attributes, screen readers cannot determine progress bar values — they only see an empty div.' },

  // Lesson 4: Forms & Validation
  { lessonId:4, difficulty:'Easy', topic:'HTML Forms', title:'Registration Form', problemStatement:'Build a registration form with: name (text), email, password (min 8 chars), date of birth (date picker), gender (radio buttons), country (select), and terms checkbox. Use proper labels and validation attributes.', examples:'All fields required, password minlength=8', starterCodeJs:'function buildRegForm() {\n  return "";\n}', hints:'["minlength=8 on password", "type=date for DOB", "fieldset + legend for radio group", "required on all fields"]', solutionExplanation:'Native HTML validation attributes give users instant feedback without JavaScript. Always pair with server-side validation.' },
  { lessonId:4, difficulty:'Easy', topic:'HTML Forms', title:'Search Form', problemStatement:'Create an accessible search form with: a visible label "Search", an input type="search" with placeholder, a clear button (×), and keyboard support. Wrap in <form role="search">.', examples:'<form role="search"><label>...', starterCodeJs:'function buildSearchForm() {\n  return "";\n}', hints:'["role=search identifies the landmark", "type=search enables browser clear (×) button", "Label should be visible or use aria-label"]', solutionExplanation:'role="search" creates a search landmark that screen reader users can jump to directly.' },
  { lessonId:4, difficulty:'Medium', topic:'HTML Forms', title:'Real-time Password Strength', problemStatement:'Create a password field with a live strength indicator (Weak/Medium/Strong) that updates as the user types. Use an aria-live region to announce strength changes to screen readers.', examples:'Strength based on length, numbers, special chars', starterCodeJs:'function checkStrength(password) {\n  // Return "weak", "medium", or "strong"\n}\nfunction buildPasswordField() {\n  return "";\n}\nfunction attachStrengthChecker(inputEl, statusEl) {\n  // Listen to input event\n}', hints:'["Weak: <8 chars", "Medium: 8+ chars with numbers", "Strong: 8+ chars + numbers + symbols", "Update aria-live region text"]', solutionExplanation:'The aria-live region announces strength changes so screen reader users get the same real-time feedback as visual users.' },
  { lessonId:4, difficulty:'Medium', topic:'HTML Forms', title:'Multi-step Form Wizard', problemStatement:'Build a 3-step form (Personal Info, Address, Payment) with: progress indicator showing current step, only current step visible, Next/Back buttons, and form data persisted across steps in an object.', examples:'Step 1/3: Personal Info', starterCodeJs:'let formData = {};\nlet currentStep = 1;\n\nfunction showStep(n) {\n  // Show only step n\n}\nfunction nextStep() {\n  // Validate + advance\n}\nfunction buildWizard() {\n  return "";\n}', hints:'["Hide inactive steps with display:none or hidden attribute", "Save step data to formData object on Next", "Update progress indicator aria-valuenow"]', solutionExplanation:'Persisting data across steps prevents frustration. Always validate the current step before allowing navigation to the next.' },
  { lessonId:4, difficulty:'Medium', topic:'HTML Forms', title:'File Upload with Preview', problemStatement:'Create a custom file upload input that: shows a drag-and-drop zone, previews selected images using FileReader, shows file name and size, and validates file type (images only) and max size (2MB).', examples:'FileReader.readAsDataURL() for preview', starterCodeJs:'function buildFileUpload() {\n  return "";\n}\nfunction handleFiles(files) {\n  // Validate and preview\n}', hints:'["accept=image/* on input", "dragover/drop events on the zone", "FileReader.readAsDataURL for preview", "file.size > 2 * 1024 * 1024 for size check"]', solutionExplanation:'The actual <input type="file"> is hidden; the styled zone triggers it via label or .click(). FileReader runs client-side only.' },
  { lessonId:4, difficulty:'Hard', topic:'HTML Forms', title:'Custom Constraint Validation', problemStatement:'Create a username field that validates: 3-20 characters, only letters/numbers/underscores, not starting with a number, and not a reserved word (admin, root). Use the Constraint Validation API (setCustomValidity).', examples:'input.setCustomValidity("Username cannot be admin")', starterCodeJs:'function validateUsername(input) {\n  const value = input.value;\n  // Check all rules\n  // Call input.setCustomValidity(message) or setCustomValidity("")\n}', hints:'["setCustomValidity(\"\") clears the error", "/^[a-zA-Z_][a-zA-Z0-9_]{2,19}$/ regex", "Check reserved words array", "Call on input event for real-time feedback"]', solutionExplanation:'setCustomValidity integrates with the browser\'s native validation UI. Empty string = valid; any other string = the error message.' },
  { lessonId:4, difficulty:'Hard', topic:'HTML Forms', title:'Accessible Date Range Picker', problemStatement:'Build a date range picker with two date inputs (start, end). Validate that end >= start, show error messages using aria-describedby, and clear errors on valid input.', examples:'End date must be after start date', starterCodeJs:'function buildDateRangePicker() {\n  return "";\n}\nfunction validateRange(startEl, endEl) {\n  // Validate and set aria-invalid\n}', hints:'["Compare Date objects", "aria-invalid=true on invalid field", "Error message id matches aria-describedby value", "min attribute on end = start value"]', solutionExplanation:'Setting the end date input\'s min attribute dynamically to the start value provides both native and custom validation.' },
  { lessonId:4, difficulty:'Hard', topic:'HTML Forms', title:'Form Auto-save with LocalStorage', problemStatement:'Create a contact form that auto-saves to localStorage on every keystroke and restores saved values on page load. Add a "Resume saved form" banner when saved data is detected.', examples:'localStorage.setItem("contact-form", JSON.stringify(data))', starterCodeJs:'function buildContactForm() {\n  return "";\n}\nfunction saveForm(formEl) {\n  // Serialize and save\n}\nfunction restoreForm(formEl) {\n  // Load from localStorage\n}', hints:'["querySelectorAll all named inputs", "Debounce save by 500ms", "Check localStorage on DOMContentLoaded", "Clear localStorage on successful submit"]', solutionExplanation:'Debouncing prevents excessive localStorage writes on every keystroke. Always clear saved data after successful submission.' },
  { lessonId:4, difficulty:'Easy', topic:'HTML Forms', title:'Checkbox Group with Select All', problemStatement:'Build a skill selection form with a "Select All" checkbox and 5 individual skill checkboxes. Selecting all checks all; if all individual are checked, auto-check "Select All"; unchecking any unchecks "Select All".', examples:'Indeterminate state when some but not all checked', starterCodeJs:'function buildCheckboxGroup(skills) {\n  return "";\n}\nfunction initSelectAll() {\n  const selectAll = document.querySelector("#select-all");\n  const checkboxes = document.querySelectorAll(".skill-cb");\n  // Wire up logic\n}', hints:'["checkbox.indeterminate = true for partial state", "Listen to change on all checkboxes", "Count checked to set indeterminate"]', solutionExplanation:'The indeterminate state is a visual hint only — it cannot be set in HTML, only via JS: checkbox.indeterminate = true.' },
  { lessonId:4, difficulty:'Medium', topic:'HTML Forms', title:'Dynamic Form Fields', problemStatement:'Build a form where clicking "Add Experience" appends a new fieldset with job title and company inputs. Each fieldset has a "Remove" button. Limit to 5 entries. Update field names/ids to avoid duplicates.', examples:'name="experience[0][title]", name="experience[1][title]"', starterCodeJs:'let count = 0;\nfunction addExperience() {\n  // Create and append fieldset\n  count++;\n}\nfunction removeExperience(btn) {\n  // Remove the fieldset\n}', hints:'["Use count index in name attributes", "Check count < 5 before adding", "Disable Add button when at max", "Update remaining count label"]', solutionExplanation:'Indexed names (experience[0][title]) let server frameworks parse the data as an array of objects.' },

  // Lesson 5: Tables
  { lessonId:5, difficulty:'Easy', topic:'HTML Tables', title:'Basic Data Table', problemStatement:'Create a table of 5 students with columns: Name, Subject, and Grade. Include <thead> with <th scope="col">, <tbody> with the data, and a <caption>.', examples:'<caption>Student Grades — Q1 2024</caption>', starterCodeJs:'function buildTable(students) {\n  // students = [{name, subject, grade}]\n  return "";\n}', hints:'["<thead> → <th scope=col>", "<tbody> → <td>", "<caption> before any thead"]', solutionExplanation:'scope="col" explicitly associates each header with its column for screen readers.' },
  { lessonId:5, difficulty:'Medium', topic:'HTML Tables', title:'Sortable Table', problemStatement:'Build an HTML table with a sort button in each column header. Clicking a header sorts the table by that column (ascending/descending toggle). Use data-sort attribute on the header to track sort state.', examples:'th.dataset.sort = "asc" or "desc"', starterCodeJs:'function buildSortableTable(data, columns) {\n  return "";\n}\nfunction sortTable(th, data) {\n  const col = th.dataset.col;\n  const dir = th.dataset.sort === "asc" ? "desc" : "asc";\n  // Sort and re-render\n}', hints:'["data-col on each th for column key", "data-sort toggles asc/desc", "aria-sort=ascending/descending for accessibility", "Re-render tbody on sort"]', solutionExplanation:'aria-sort should be set on the sorted column header so screen readers can announce the sort direction.' },
  { lessonId:5, difficulty:'Medium', topic:'HTML Tables', title:'Spanning Cells Table', problemStatement:'Create a schedule table where Monday cells span 2 columns (double-period), and a Saturday row spans 2 rows. Use both colspan and rowspan.', examples:'<td colspan="2">Double Period</td>', starterCodeJs:'function buildSchedule() {\n  return "";\n}', hints:'["colspan=2 expands cell horizontally", "rowspan=2 expands cell vertically", "Omit the cells that the spanned cell covers in subsequent rows/cols"]', solutionExplanation:'When using rowspan=2, omit the corresponding cell in the next row — the spanning cell occupies that space.' },
  { lessonId:5, difficulty:'Medium', topic:'HTML Tables', title:'Column Styling with colgroup', problemStatement:'Build a table with 4 columns where the 2nd and 3rd columns have a different background color, using <colgroup> and <col> without adding class attributes to every cell.', examples:'<colgroup><col><col class="highlight" span="2"><col></colgroup>', starterCodeJs:'function buildStyledTable() {\n  return "";\n}', hints:'["<colgroup> comes right after <table>", "span=2 makes one <col> cover 2 columns", "Only background, border, visibility work on col"]', solutionExplanation:'<col> styling is limited to: background-color, border, visibility, width. For other properties, use td:nth-child().' },
  { lessonId:5, difficulty:'Hard', topic:'HTML Tables', title:'Responsive Table', problemStatement:'Make a wide data table responsive on mobile: on small screens, each row becomes a card where the column header appears as a label before each value. Use data-label attributes and CSS.', examples:'th text copied to td::before via data-label + CSS content', starterCodeJs:'function buildResponsiveTable(headers, rows) {\n  return "";\n}\nconst css = `\n@media (max-width: 640px) {\n  /* Your CSS here */\n}`', hints:'["Set data-label on each td matching its column header", "td::before { content: attr(data-label) } in CSS", "display:block on tr for card layout"]', solutionExplanation:'The CSS attr() function reads data-label from each td to display the column name as a prefix label in mobile view.' },
  { lessonId:5, difficulty:'Hard', topic:'HTML Tables', title:'Zebra-Striped Accessible Table', problemStatement:'Style every other table row with a subtle background and add a hover highlight. Ensure the stripes have sufficient color contrast and add aria-label to the table describing its contents.', examples:'tr:nth-child(even) + :hover + aria-label', starterCodeJs:'function buildZebraTable(data) {\n  return "";\n}\nconst css = `\n  table { }\n  tr:nth-child(even) { }\n  tr:hover { }\n`;', hints:'["tr:nth-child(even) targets even rows", "Contrast ratio must be at least 4.5:1 for text", "aria-label on table supplements or replaces caption"]', solutionExplanation:'Zebra striping helps visual scanning but must not be the only differentiator — sufficient contrast is required.' },
  { lessonId:5, difficulty:'Easy', topic:'HTML Tables', title:'Comparison Table', problemStatement:'Build a feature comparison table for 3 pricing plans (Basic, Pro, Enterprise) with 6 features. Use checkmarks (✓) and crosses (✗) for feature support. Include proper headers with scope="col".', examples:'Column: Basic | Pro | Enterprise. Row: API Access | ✗ | ✓ | ✓', starterCodeJs:'function buildComparisonTable(plans, features) {\n  return "";\n}', hints:'["First column is feature names with scope=row", "Use aria-label on ✓/✗ cells: aria-label=Included", "Header row uses scope=col"]', solutionExplanation:'✓ and ✗ are visual — add aria-label="Included" or "Not included" so screen readers convey the meaning.' },
  { lessonId:5, difficulty:'Hard', topic:'HTML Tables', title:'Nested Table Headers', problemStatement:'Create a table for quarterly revenue by region and product with grouped column headers: Q1, Q2 spanning 2 sub-columns each (North, South). Use <colgroup> and nested <th> with colspan.', examples:'<th colspan="2">Q1</th> above individual region headers', starterCodeJs:'function buildQuarterlyTable(data) {\n  return "";\n}', hints:'["Two header rows: one for quarters (colspan=2), one for regions", "id + headers attributes for complex header associations", "thead can have multiple tr rows"]', solutionExplanation:'For complex tables with multiple header rows, use id attributes on headers and headers attributes on cells for maximum screen reader compatibility.' },
  { lessonId:5, difficulty:'Medium', topic:'HTML Tables', title:'Filterable Table', problemStatement:'Add a search input above a table that filters rows in real-time. Rows where no cell matches the search query are hidden. Update a live region announcing how many results are shown.', examples:'"Showing 3 of 10 rows"', starterCodeJs:'function buildFilterableTable(data) {\n  return "";\n}\nfunction filterTable(query) {\n  // Filter rows and update count\n}', hints:'["tr.style.display = none/table-row", "toLowerCase() both query and cell text", "Update aria-live region with count", "Debounce 150ms"]', solutionExplanation:'The aria-live region ensures screen reader users hear the result count when filtering — matching the visual update.' },
  { lessonId:5, difficulty:'Easy', topic:'HTML Tables', title:'tfoot Summary Row', problemStatement:'Build a sales table with 5 product rows and a <tfoot> summary row that shows the total sales. Calculate the total in JavaScript and insert it into the footer.', examples:'<tfoot><tr><td>Total</td><td>₹12,500</td></tr></tfoot>', starterCodeJs:'function buildSalesTable(products) {\n  // products = [{name, sales}]\n  const total = products.reduce((s, p) => s + p.sales, 0);\n  return "";\n}', hints:'["tfoot comes after tbody in HTML", "But browsers render it at the bottom visually", "Format total with toLocaleString()"]', solutionExplanation:'<tfoot> allows the browser to render footer rows at the bottom of long scrollable tables regardless of markup position.' },
]

async function main() {
  console.log('Seeding lessons 1-5 quiz + coding questions...')

  // Insert quiz questions (skip if already exist)
  for (const q of quiz) {
    const exists = await p.quizQuestion.findFirst({ where: { lessonId: q.lessonId, question: q.question } })
    if (!exists) await p.quizQuestion.create({ data: q })
  }
  console.log(`✓ ${quiz.length} quiz questions inserted`)

  // Insert coding questions
  for (const q of coding) {
    const exists = await p.practiceQuestion.findFirst({ where: { lessonId: q.lessonId, title: q.title } })
    if (!exists) await p.practiceQuestion.create({ data: q })
  }
  console.log(`✓ ${coding.length} coding questions inserted`)
}

main().catch(console.error).finally(() => p.$disconnect())
