const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const quizQuestions = [
  // Lesson 54 - Component Design
  {lessonId:54,question:"What is the Single Responsibility Principle in component design?",options:["A component should be small","A component should do one thing and do it well","Components should use hooks","Components should be functional"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:54,question:"What is the difference between presentational and container components?",options:["No difference","Presentational handles UI; container handles data/logic","Container is bigger","Presentational uses state"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:54,question:"What is prop drilling and why is it a problem?",options:["Using too many props","Passing props through many intermediate components that don't need them","Performance issue","A React bug"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:54,question:"What is a compound component pattern?",options:["Using multiple frameworks","Related components sharing implicit state via Context","Nesting components","Using HOCs"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:54,question:"What makes a good component API?",options:["As many props as possible","Minimal required props, sensible defaults, predictable behavior, composition-friendly","No props","Static components only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:54,question:"What is component co-location?",options:["Putting components in one file","Keeping related code (component, styles, tests) close together in the same directory","Using global state","Sharing components"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:54,question:"When should you split a component into smaller components?",options:["Always split into tiny components","When it's too large to understand, has multiple concerns, or parts are reusable elsewhere","Never split","Only for performance"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:54,question:"What is the render props pattern?",options:["Passing JSX as props","Sharing code by passing a function as a prop that returns JSX","Prop drilling","HOC pattern"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:54,question:"What is component composition vs inheritance in React?",options:["No difference","React favors composition (combining components) over class inheritance","Inheritance is better","Composition is for HOCs only"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:54,question:"What is the purpose of defaultProps or default parameter values in components?",options:["They prevent errors only","They define fallback values so components work without every prop being specified","They are deprecated","Only for TypeScript"],correctAnswer:1,difficulty:"Easy"},

  // Lesson 55 - Folder Structure
  {lessonId:55,question:"What is the feature-based folder structure?",options:["One folder per component","Organizing code by feature/domain rather than by file type","Alphabetical ordering","Flat structure"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:55,question:"What goes in a components/ vs pages/ folder in a Next.js app?",options:["No difference","pages/ contains route-level components; components/ contains reusable UI components","pages/ is deprecated","components/ is for tests"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:55,question:"What is the barrel file pattern?",options:["A large configuration file","An index.js that re-exports from multiple files in a directory for cleaner imports","A database migration","A test utility"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:55,question:"Where should shared utility functions live in a project?",options:["In components/","In a utils/ or lib/ directory at the project root","In node_modules","In public/"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:55,question:"What is the colocation principle for tests?",options:["Put all tests in a separate test/ folder","Keep test files next to the files they test (Component.test.tsx next to Component.tsx)","Tests belong in src/","No convention needed"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:55,question:"What is a monorepo and what tools manage it?",options:["A single repository with one project","A single repository containing multiple related packages; managed by Turborepo, Nx, or npm workspaces","Multiple repositories","A GitHub feature"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:55,question:"Where should environment-specific configuration live?",options:["In source code","In .env files that are gitignored, with .env.example committed","In package.json","In README"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:55,question:"What is the purpose of a lib/ or services/ folder?",options:["For UI components","For business logic, API clients, and external service integrations","For CSS files","For static assets"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:55,question:"How should you organize shared types in a TypeScript project?",options:["Inline in each file","In a types/ or @types/ directory, or co-located with the code that owns them","In package.json","In tsconfig"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:55,question:"What is the problem with a flat project structure for large apps?",options:["It's too organized","Files become hard to find, implicit dependencies grow, and concerns get mixed together","Flat is always better","No problem"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 56 - Reusability & Abstraction
  {lessonId:56,question:"What is the DRY principle?",options:["Code should be fast","Don't Repeat Yourself - avoid duplicating logic by extracting into shared functions/components","Always use HOCs","Write minimal code"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:56,question:"When is it appropriate to abstract code?",options:["Always abstract immediately","After the third time you need it (Rule of Three) - don't abstract prematurely","Never abstract","Immediately on first use"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:56,question:"What is the wrong abstraction problem?",options:["No problem with abstractions","Premature abstractions that try to handle all cases become complex and harder to change than duplication","Abstractions are always good","Only applies to functions"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:56,question:"What is a design system and why is it valuable?",options:["A diagram tool","A collection of reusable components, patterns, and guidelines that ensure consistency across an application","A CSS framework","A project management tool"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:56,question:"What makes a hook reusable?",options:["Being complex","Encapsulating a specific concern, accepting configuration parameters, and not being tied to a specific component","Using useEffect","Having many return values"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:56,question:"What is the difference between a generic and a specific component?",options:["No difference","Generic components work in many contexts; specific components are tailored to one use case","Generic is better","Specific is faster"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:56,question:"What is the interface segregation principle applied to React props?",options:["More props is better","Don't force components to depend on props they don't use; split large prop interfaces","Use TypeScript always","Fewer props always"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:56,question:"What is a utility-first approach to CSS reusability?",options:["Writing utility functions","Using low-level CSS utility classes (like Tailwind) instead of component-specific classes","Using CSS modules","Inline styles"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:56,question:"How do you make a data fetching hook reusable across different resources?",options:["Duplicate it for each resource","Accept the URL/endpoint as a parameter; use generic types for the response data","Use global state","Copy-paste approach"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:56,question:"What is the principle of least knowledge (Law of Demeter) in component design?",options:["Components should be small","A component should only know about its direct dependencies, not deeply nested structures","Always use Context","Don't use state"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 57 - Scalability
  {lessonId:57,question:"What is code splitting in React and why does it improve scalability?",options:["Splitting files into multiple lines","Dividing the JavaScript bundle into smaller chunks loaded on demand, reducing initial load time","Splitting components","A build tool feature"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:57,question:"What is a micro-frontend architecture?",options:["Small components","Splitting a frontend app into independently deployable pieces owned by different teams","A CSS methodology","A bundling strategy"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:57,question:"What is the purpose of memoization in scalable React apps?",options:["To save data permanently","Caching expensive computation results or component renders to avoid redundant work","A debugging technique","For animations"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:57,question:"How does React Query/SWR help with scalability?",options:["By making components smaller","By managing server state: caching, deduplication, background refetch, and sync across components","By reducing bundle size","By improving CSS"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:57,question:"What is the purpose of a CDN in frontend scalability?",options:["Database caching","Serving static assets (JS, CSS, images) from servers geographically close to users","API rate limiting","Load balancing"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:57,question:"What is tree shaking in bundlers?",options:["A debugging technique","Eliminating dead/unused code from the final bundle based on ES module imports","A React pattern","A testing strategy"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:57,question:"What is the benefit of a stateless frontend architecture?",options:["No advantages","Frontend doesn't store user sessions; any server can handle any request; horizontally scalable","Required for Next.js","Only for APIs"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:57,question:"What is lazy loading in React and when should you use it?",options:["Loading data slowly","Loading components or data only when needed (e.g., below-fold content, non-critical routes)","A performance anti-pattern","For all components"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:57,question:"How does proper state management affect scalability?",options:["It doesn't matter","Poor state management causes unnecessary re-renders and prop drilling; good management scales with app complexity","Only affects large apps","State should always be global"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:57,question:"What is the purpose of a service worker in scalable web apps?",options:["A Node.js worker","A script that runs in the background, enabling offline support, caching, and push notifications","A database proxy","A CDN replacement"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 58 - API Architecture
  {lessonId:58,question:"What is the Backend for Frontend (BFF) pattern?",options:["A CSS framework","A dedicated API layer tailored to a specific frontend's needs, aggregating multiple microservices","A database pattern","A testing approach"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:58,question:"What is the difference between REST and GraphQL at the architecture level?",options:["No difference","REST: multiple fixed endpoints; GraphQL: one flexible endpoint with client-specified queries","GraphQL is always better","REST is deprecated"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:58,question:"What is API gateway pattern?",options:["A frontend routing tool","A single entry point for all API requests that handles auth, rate limiting, routing to microservices","A database proxy","A caching layer only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:58,question:"What is the strangler fig pattern for API migration?",options:["A refactoring tool","Gradually replacing old API endpoints with new ones, routing traffic incrementally, without a big-bang migration","A security pattern","A testing strategy"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:58,question:"What is event-driven API architecture?",options:["Using click events","Services communicate via events (queues/topics) rather than direct API calls; enables loose coupling","A REST variant","A database pattern"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:58,question:"What is API backward compatibility and why does it matter?",options:["Not important","Old clients must continue working when new API versions are released; breaking changes force all clients to update simultaneously","A security concern","Only for public APIs"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:58,question:"What is circuit breaking in microservice API calls?",options:["Stopping all requests","Automatically stopping calls to a failing service to prevent cascade failures; circuit opens on error threshold","A load balancer feature","A database pattern"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:58,question:"What is API documentation and what tools generate it?",options:["README files only","Formal specification of endpoints, params, responses; tools include Swagger/OpenAPI, Postman, Insomnia","Comments in code","Test files"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:58,question:"What is the difference between synchronous and asynchronous API design?",options:["No difference","Synchronous: client waits for response; Asynchronous: client gets job ID, polls or gets webhook when done","Async is always better","Sync is deprecated"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:58,question:"What is rate limiting at the API architecture level?",options:["Making APIs slow","Controlling how many requests a client can make in a time window to protect against abuse and ensure fair use","A caching strategy","Authentication"],correctAnswer:1,difficulty:"Easy"},

  // Lesson 59 - State Management (Architecture level)
  {lessonId:59,question:"What is the Flux architecture pattern?",options:["A CSS framework","Unidirectional data flow: Action -> Dispatcher -> Store -> View; Redux is based on this","A React hook","A backend pattern"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:59,question:"What is the difference between client state and server state?",options:["No difference","Client state: UI state (modals, filters); Server state: data from API that needs caching and sync","Server state is faster","Client state only matters"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:59,question:"When should you use global state vs local component state?",options:["Always global","Use local state for UI-only concerns; global for state shared by multiple unrelated components","Always local","No rule exists"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:59,question:"What is optimistic UI and what state management concept supports it?",options:["Making UI look nice","Updating UI immediately before server confirmation; rollback on failure; requires tracking pending state","A React hook","CSS animations"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:59,question:"What is the problem with Redux boilerplate and how does Redux Toolkit solve it?",options:["No problem","Redux requires manual action types, action creators, and switch statements; RTK simplifies with createSlice","Redux is deprecated","RTK is slower"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:59,question:"What is Zustand and how does it compare to Redux?",options:["A CSS library","A minimal state management library using a store hook without the boilerplate of Redux","A database ORM","A router"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:59,question:"What is the purpose of React Query for state management?",options:["For UI state only","Managing server/remote state: caching, background updates, loading/error states, deduplication","A Redux replacement","For forms only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:59,question:"What is the atom model in state management (Jotai/Recoil)?",options:["A physics concept","Splitting global state into small independent atoms that components subscribe to individually","A Redux pattern","A class pattern"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:59,question:"What is state normalization and why is it important?",options:["Making state uniform","Storing data in flat structures (like a database) to prevent duplication and simplify updates","A Redux requirement","Only for large apps"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:59,question:"What is the selector pattern in state management?",options:["CSS selectors","Functions that derive computed values from state, often memoized to prevent recalculation","A React hook","A component pattern"],correctAnswer:1,difficulty:"Medium"}
];

const codingQuestions = [
  // Lesson 41 - Events & EventEmitter coding
  {lessonId:41,difficulty:"Easy",title:"Custom EventEmitter",problemStatement:"Build a class that implements EventEmitter: on, off, emit, once. Use a Map to store listeners.",examples:"emitter.on('data', fn). emitter.emit('data', payload). emitter.off('data', fn). emitter.once('done', fn).",starterCodeJs:"class EventEmitter {\n  constructor() { this._events = new Map(); }\n  on(event, listener) {\n    if (!this._events.has(event)) this._events.set(event, new Set());\n    this._events.get(event).add(listener);\n    return () => this.off(event, listener); // return unsubscribe\n  }\n  off(event, listener) {\n    this._events.get(event)?.delete(listener);\n    return this;\n  }\n  emit(event, ...args) {\n    this._events.get(event)?.forEach(fn => { try { fn(...args); } catch(e) { console.error(e); } });\n    return this;\n  }\n  once(event, listener) {\n    const wrapper = (...args) => { listener(...args); this.off(event, wrapper); };\n    return this.on(event, wrapper);\n  }\n  removeAll(event) { if (event) this._events.delete(event); else this._events.clear(); }\n  listenerCount(event) { return this._events.get(event)?.size || 0; }\n}",hints:"on() returns unsubscribe function. once() wraps listener in a one-time function that removes itself. Try/catch prevents one bad listener from stopping others.",solutionExplanation:"EventEmitter: Map of event->Set<listeners>. on() returns cleanup fn. once() wraps and auto-removes. emit() catches errors per listener."},
  {lessonId:41,difficulty:"Medium",title:"Event-driven File Processor",problemStatement:"Build a file processor using Node.js EventEmitter. Emits progress, error, complete events. Process lines from a text file.",examples:"processor.on('progress', pct=>...). processor.on('complete', result=>...). processor.process('file.txt')",starterCodeJs:"const fs = require('fs');\nconst readline = require('readline');\nconst { EventEmitter } = require('events');\nclass FileProcessor extends EventEmitter {\n  async process(filePath, transform = line => line) {\n    let lineCount = 0;\n    let processed = 0;\n    const results = [];\n    // Get total lines first for progress\n    const rl = readline.createInterface({ input: fs.createReadStream(filePath) });\n    for await (const line of rl) {\n      if (line.trim()) lineCount++;\n    }\n    const rl2 = readline.createInterface({ input: fs.createReadStream(filePath) });\n    for await (const line of rl2) {\n      if (!line.trim()) continue;\n      try {\n        const result = await transform(line);\n        results.push(result);\n        processed++;\n        this.emit('progress', Math.round((processed/lineCount)*100), processed, lineCount);\n      } catch(err) { this.emit('error', err, line); }\n    }\n    this.emit('complete', { results, processed, total: lineCount });\n    return results;\n  }\n}",hints:"for-await works with readline interface (AsyncIterator). Pre-count lines for progress percentage. emit error per line (don't stop processing).",solutionExplanation:"Event-driven processing: emit progress as each line completes. Emit error per line to allow partial processing. AsyncIterator readline avoids loading entire file."},
  {lessonId:41,difficulty:"Medium",title:"Message Bus with Middleware",problemStatement:"Build a message bus that supports middleware (like Express but for events). Middleware can transform, filter, or block messages.",examples:"bus.use((msg,next)=>{ msg.timestamp=Date.now(); next(); }). bus.on('event', handler).",starterCodeJs:"const { EventEmitter } = require('events');\nclass MessageBus extends EventEmitter {\n  constructor() { super(); this._middleware = []; }\n  use(fn) { this._middleware.push(fn); return this; }\n  publish(event, data) {\n    const message = { event, data, id: Math.random().toString(36).slice(2) };\n    this._runMiddleware(message, 0, () => super.emit(event, message));\n  }\n  _runMiddleware(msg, index, done) {\n    if (index >= this._middleware.length) return done();\n    const next = (err) => {\n      if (err) return this.emit('error', err);\n      this._runMiddleware(msg, index+1, done);\n    };\n    try { this._middleware[index](msg, next); } catch(err) { next(err); }\n  }\n}\nconst bus = new MessageBus();\nbus.use((msg,next) => { msg.timestamp = Date.now(); next(); });\nbus.use((msg,next) => { if (!msg.data) next(new Error('Empty message')); else next(); });\nbus.on('order', msg => console.log('Order received:', msg));",hints:"Middleware chain: call _runMiddleware with incremented index. done() is called after last middleware. Error handling calls emit('error').",solutionExplanation:"Middleware bus: events pass through middleware pipeline before reaching handlers. Middleware can enrich, validate, or block messages."},
  {lessonId:41,difficulty:"Hard",title:"Event-driven State Machine",problemStatement:"Build a finite state machine using events. States: idle, running, paused, stopped. Transitions enforced. Invalid transitions throw.",examples:"machine.dispatch('start') -> running. machine.dispatch('pause') -> paused. dispatch('start') from stopped throws.",starterCodeJs:"const { EventEmitter } = require('events');\nconst transitions = {\n  idle:    { start: 'running' },\n  running: { pause: 'paused', stop: 'stopped', complete: 'idle' },\n  paused:  { resume: 'running', stop: 'stopped' },\n  stopped: {}\n};\nclass StateMachine extends EventEmitter {\n  constructor(initial = 'idle') {\n    super();\n    this._state = initial;\n    this._history = [initial];\n  }\n  get state() { return this._state; }\n  dispatch(action) {\n    const allowed = transitions[this._state];\n    if (!allowed[action]) throw new Error(`Invalid transition: ${action} from ${this._state}`);\n    const prev = this._state;\n    this._state = allowed[action];\n    this._history.push(this._state);\n    this.emit('transition', { from: prev, to: this._state, action });\n    this.emit(this._state, { from: prev, action });\n    return this;\n  }\n  can(action) { return !!transitions[this._state]?.[action]; }\n  get history() { return [...this._history]; }\n}",hints:"Valid transitions defined per state. Throw on invalid transition. Emit both 'transition' (generic) and state name (specific) events. Track history.",solutionExplanation:"State machine: only valid transitions allowed. Event emitter communicates state changes. History for debugging. can() checks before dispatch."},
  {lessonId:41,difficulty:"Easy",title:"Async Event Queue",problemStatement:"Build a queue where events are processed one at a time (no concurrent processing). Events are queued if a handler is running.",examples:"queue.add('task1', data). Handlers run sequentially not concurrently.",starterCodeJs:"const { EventEmitter } = require('events');\nclass AsyncEventQueue extends EventEmitter {\n  constructor() {\n    super();\n    this._queue = [];\n    this._running = false;\n    this._handlers = new Map();\n  }\n  on(event, handler) { this._handlers.set(event, handler); return this; }\n  add(event, data) {\n    this._queue.push({ event, data });\n    if (!this._running) this._process();\n  }\n  async _process() {\n    if (this._queue.length === 0) { this._running = false; return; }\n    this._running = true;\n    const { event, data } = this._queue.shift();\n    const handler = this._handlers.get(event);\n    try {\n      if (handler) await handler(data);\n      this.emit('processed', { event, data });\n    } catch(err) { this.emit('error', err, { event, data }); }\n    setImmediate(() => this._process());\n  }\n  get size() { return this._queue.length; }\n  get isRunning() { return this._running; }\n}",hints:"_running flag prevents concurrent processing. setImmediate yields control between items (not blocking). Queue processes FIFO.",solutionExplanation:"Sequential queue: _running prevents overlap. setImmediate gives event loop a chance to run I/O between items. FIFO via shift()."},
  {lessonId:41,difficulty:"Medium",title:"Observable Stream",problemStatement:"Build an Observable class (simplified RxJS) with map, filter, and subscribe. Support unsubscription and completion.",examples:"Observable.from([1,2,3]).map(x=>x*2).filter(x=>x>2).subscribe(v=>console.log(v))",starterCodeJs:"class Observable {\n  constructor(subscriber) { this._subscriber = subscriber; }\n  static from(arr) {\n    return new Observable(({ next, complete, error }) => {\n      arr.forEach(v => next(v));\n      complete();\n    });\n  }\n  static interval(ms) {\n    return new Observable(({ next }) => {\n      const id = setInterval(() => next(Date.now()), ms);\n      return () => clearInterval(id); // teardown\n    });\n  }\n  map(fn) {\n    return new Observable(obs => this.subscribe({ next: v => obs.next(fn(v)), error: obs.error, complete: obs.complete }));\n  }\n  filter(fn) {\n    return new Observable(obs => this.subscribe({ next: v => { if (fn(v)) obs.next(v); }, error: obs.error, complete: obs.complete }));\n  }\n  subscribe(observer) {\n    if (typeof observer === 'function') observer = { next: observer };\n    const { next=()=>{}, error=console.error, complete=()=>{} } = observer;\n    const teardown = this._subscriber({ next, error, complete });\n    return { unsubscribe: () => teardown?.() };\n  }\n}",hints:"Observable: push-based stream. subscribe() calls subscriber with observer. map/filter return new Observable wrapping this. teardown function for cleanup.",solutionExplanation:"Simplified RxJS: lazy (only runs on subscribe). Operators return new Observables. Teardown (unsubscribe) cleans up resources. Observer pattern."},
  {lessonId:41,difficulty:"Hard",title:"Event Sourcing with EventEmitter",problemStatement:"Build an event-sourced counter using Node EventEmitter. All state changes are events. State is always derived by replaying events.",examples:"counter.increment(). counter.decrement(). counter.getState() replays events -> current count.",starterCodeJs:"const { EventEmitter } = require('events');\nclass EventSourcedCounter extends EventEmitter {\n  constructor() {\n    super();\n    this._events = [];\n  }\n  increment(amount=1) {\n    const event = { type:'INCREMENT', payload:{amount}, timestamp:Date.now() };\n    this._events.push(event);\n    this.emit('event', event);\n    return this;\n  }\n  decrement(amount=1) {\n    const event = { type:'DECREMENT', payload:{amount}, timestamp:Date.now() };\n    this._events.push(event);\n    this.emit('event', event);\n    return this;\n  }\n  reset() {\n    const event = { type:'RESET', payload:{}, timestamp:Date.now() };\n    this._events.push(event);\n    this.emit('event', event);\n    return this;\n  }\n  getState(upTo=this._events.length) {\n    return this._events.slice(0,upTo).reduce((count, e) => {\n      if (e.type==='INCREMENT') return count + e.payload.amount;\n      if (e.type==='DECREMENT') return count - e.payload.amount;\n      if (e.type==='RESET') return 0;\n      return count;\n    }, 0);\n  }\n  getHistory() { return [...this._events]; }\n  replay(at) { return this.getState(at); } // time travel\n}",hints:"State is derived by reducing events. upTo enables time travel. Events are immutable append-only log. Never mutate state directly.",solutionExplanation:"Event sourcing: append events, derive state. getState(n) gives state at event n (time travel). Events are the source of truth."},
  {lessonId:41,difficulty:"Easy",title:"Typed EventEmitter",problemStatement:"Build a TypeScript-ready EventEmitter that enforces event types and payload types at compile time.",examples:"TypedEmitter<{login:{userId:number}, logout:{}}> - TypeScript knows login payload has userId.",starterCodeJs:"const { EventEmitter } = require('events');\nfunction createTypedEmitter() {\n  const emitter = new EventEmitter();\n  return {\n    on(event, listener) { emitter.on(event, listener); return this; },\n    off(event, listener) { emitter.off(event, listener); return this; },\n    once(event, listener) { emitter.once(event, listener); return this; },\n    emit(event, ...args) { emitter.emit(event, ...args); return this; },\n    // JavaScript type guard helper\n    typed(eventType) {\n      return {\n        on: (listener) => { emitter.on(eventType, listener); return () => emitter.off(eventType, listener); },\n        once: (listener) => emitter.once(eventType, listener),\n        emit: (data) => emitter.emit(eventType, data)\n      };\n    }\n  };\n}\nconst bus = createTypedEmitter();\nconst loginEvent = bus.typed('login');\nloginEvent.on(({ userId }) => console.log('User logged in:', userId));\nloginEvent.emit({ userId: 123 });",hints:"typed() method scopes event listeners to a specific event name. Returns unsubscribe function. Factory pattern creates event-specific API.",solutionExplanation:"Typed events in JavaScript: factory function returns event-scoped API. In TypeScript, this becomes a generic TypedEmitter<Events> with full type safety."},
  {lessonId:41,difficulty:"Medium",title:"Event Throttle and Debounce",problemStatement:"Wrap EventEmitter to add throttle/debounce to specific events. Prevent rapid-fire events from overwhelming handlers.",examples:"emitter.onThrottled('resize', 100, handler) - handler called at most once per 100ms.",starterCodeJs:"const { EventEmitter } = require('events');\nclass ThrottledEmitter extends EventEmitter {\n  onThrottled(event, limitMs, listener) {\n    let lastCall = 0;\n    const wrapper = (...args) => {\n      const now = Date.now();\n      if (now - lastCall >= limitMs) { lastCall = now; listener(...args); }\n    };\n    super.on(event, wrapper);\n    return () => super.off(event, wrapper);\n  }\n  onDebounced(event, delayMs, listener) {\n    let timer;\n    const wrapper = (...args) => {\n      clearTimeout(timer);\n      timer = setTimeout(() => listener(...args), delayMs);\n    };\n    super.on(event, wrapper);\n    return () => { super.off(event, wrapper); clearTimeout(timer); };\n  }\n  onLeading(event, limitMs, listener) {\n    let blocked = false;\n    const wrapper = (...args) => {\n      if (blocked) return;\n      blocked = true;\n      listener(...args);\n      setTimeout(() => { blocked = false; }, limitMs);\n    };\n    super.on(event, wrapper);\n    return () => super.off(event, wrapper);\n  }\n}",hints:"Throttle: check time since last call. Debounce: reset timer on each call, fire after delay. Both return unsubscribe. Store timer in closure.",solutionExplanation:"Throttle: rate-limit by checking elapsed time. Debounce: delay until events stop. Leading: fire immediately then block. All use closure state."},
  {lessonId:41,difficulty:"Hard",title:"Event Store with Snapshots",problemStatement:"Build an event store that periodically creates snapshots to avoid replaying all events. Load from snapshot + recent events.",examples:"store.append('user:1', event). store.getState('user:1') uses nearest snapshot + events after it.",starterCodeJs:"class EventStore {\n  constructor({ snapshotFrequency=10 }={}) {\n    this._events = new Map(); // aggregateId -> events[]\n    this._snapshots = new Map(); // aggregateId -> {state, eventIndex}\n    this._frequency = snapshotFrequency;\n  }\n  append(aggregateId, event) {\n    if (!this._events.has(aggregateId)) this._events.set(aggregateId, []);\n    const events = this._events.get(aggregateId);\n    events.push({ ...event, sequence: events.length });\n    // Auto-snapshot every N events\n    if (events.length % this._frequency === 0) {\n      const state = this._replay(aggregateId, 0, events.length);\n      this._snapshots.set(aggregateId, { state, afterSequence: events.length-1 });\n    }\n  }\n  _replay(aggregateId, from, to) {\n    const events = (this._events.get(aggregateId)||[]).slice(from, to);\n    return events.reduce((state, e) => apply(state, e), {});\n  }\n  getState(aggregateId) {\n    const snap = this._snapshots.get(aggregateId);\n    if (!snap) return this._replay(aggregateId, 0);\n    const events = (this._events.get(aggregateId)||[]).slice(snap.afterSequence+1);\n    return events.reduce((state, e) => apply(state, e), snap.state);\n  }\n  getEvents(aggregateId, from=0) { return (this._events.get(aggregateId)||[]).slice(from); }\n}",hints:"Snapshot after every N events. getState: load nearest snapshot + replay only events after it. Reduces replay time for long-lived aggregates.",solutionExplanation:"Snapshot optimization: full replay is O(n), snapshot+partial replay is O(n/snapshotFrequency). Trade storage for performance."},

  // Lesson 42 - Process, Environment & Config
  {lessonId:42,difficulty:"Easy",title:"Process Signal Handlers",problemStatement:"Write a Node.js module that handles OS signals: SIGTERM for graceful shutdown, SIGINT for Ctrl+C, and SIGHUP for config reload.",examples:"SIGTERM: finish current requests, disconnect DB, exit 0. SIGHUP: reload config without restart.",starterCodeJs:"const shutdownHandlers = new Set();\nlet isShuttingDown = false;\nfunction onShutdown(handler) {\n  shutdownHandlers.add(handler);\n  return () => shutdownHandlers.delete(handler);\n}\nasync function shutdown(signal) {\n  if (isShuttingDown) return;\n  isShuttingDown = true;\n  console.log(`[${signal}] Graceful shutdown...`);\n  const timeout = setTimeout(() => { console.error('Forced exit'); process.exit(1); }, 30000);\n  try {\n    await Promise.all([...shutdownHandlers].map(h => h()));\n    clearTimeout(timeout);\n    console.log('Shutdown complete');\n    process.exit(0);\n  } catch(err) { console.error('Shutdown error:', err); process.exit(1); }\n}\nprocess.on('SIGTERM', () => shutdown('SIGTERM'));\nprocess.on('SIGINT', () => shutdown('SIGINT'));\nprocess.on('SIGHUP', async () => {\n  console.log('SIGHUP: reloading config...');\n  await loadConfig();\n  console.log('Config reloaded');\n});\nprocess.on('uncaughtException', (err) => { console.error('Uncaught:', err); process.exit(1); });\nprocess.on('unhandledRejection', (reason) => { console.error('Unhandled rejection:', reason); });",hints:"Register shutdown callbacks via onShutdown(). Promise.all runs all cleanup in parallel. uncaughtException/unhandledRejection as last resort.",solutionExplanation:"Signal handlers: SIGTERM from k8s/docker for graceful shutdown. SIGHUP traditionally for reload. 30s timeout prevents hanging. Set of handlers for modularity."},
  {lessonId:42,difficulty:"Medium",title:"Config Manager with Hot Reload",problemStatement:"Build a config manager that reads from environment variables and a JSON file. Supports hot reload when config file changes.",examples:"config.get('db.host'). config.set('cache.ttl', 300). config.reload() re-reads files.",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nconst { EventEmitter } = require('events');\nclass ConfigManager extends EventEmitter {\n  constructor(filePath, envPrefix='APP') {\n    super();\n    this._filePath = filePath;\n    this._envPrefix = envPrefix;\n    this._config = {};\n    this._watcher = null;\n    this._load();\n  }\n  _load() {\n    // Load from file\n    try {\n      const fileConfig = JSON.parse(fs.readFileSync(this._filePath, 'utf8'));\n      this._config = { ...fileConfig };\n    } catch { this._config = {}; }\n    // Override with env vars (APP_DB_HOST -> db.host)\n    for (const [key, val] of Object.entries(process.env)) {\n      if (key.startsWith(this._envPrefix+'_')) {\n        const path = key.slice(this._envPrefix.length+1).toLowerCase().replace(/_/g, '.');\n        this._setNested(this._config, path.split('.'), val);\n      }\n    }\n  }\n  get(key, defaultVal) {\n    const parts = key.split('.');\n    let obj = this._config;\n    for (const p of parts) { obj = obj?.[p]; if (obj===undefined) return defaultVal; }\n    return obj ?? defaultVal;\n  }\n  _setNested(obj, keys, val) { if (keys.length===1) { obj[keys[0]]=val; return; } if (!obj[keys[0]]) obj[keys[0]]={}; this._setNested(obj[keys[0]], keys.slice(1), val); }\n  reload() { const old=this._config; this._load(); this.emit('reload', this._config, old); }\n  watch() { this._watcher = fs.watch(this._filePath, () => this.reload()); return this; }\n  close() { this._watcher?.close(); }\n}",hints:"ENV override: APP_DB_HOST=localhost maps to config.db.host. Recursive _setNested builds nested object from dotted path. fs.watch triggers reload.",solutionExplanation:"Config hierarchy: file < env vars. ENV prefix convention avoids conflicts. fs.watch triggers hot reload. Emit 'reload' for listeners to adapt."},
  {lessonId:42,difficulty:"Medium",title:"Process Metrics Collector",problemStatement:"Build a module that collects Node.js process metrics: memory, CPU, event loop lag, and active handles/requests.",examples:"metrics.collect() returns {heapUsedMB, heapTotalMB, cpuPercent, eventLoopLagMs, activeHandles}",starterCodeJs:"const { PerformanceObserver, performance } = require('perf_hooks');\nclass ProcessMetrics {\n  constructor() {\n    this._cpuUsage = process.cpuUsage();\n    this._lastCheck = Date.now();\n  }\n  collect() {\n    const mem = process.memoryUsage();\n    const now = Date.now();\n    const elapsed = now - this._lastCheck;\n    const cpu = process.cpuUsage(this._cpuUsage);\n    this._cpuUsage = process.cpuUsage();\n    this._lastCheck = now;\n    const cpuPercent = elapsed > 0 ? ((cpu.user + cpu.system) / 1000 / elapsed * 100).toFixed(1) : 0;\n    return {\n      heapUsedMB: (mem.heapUsed/1024/1024).toFixed(1),\n      heapTotalMB: (mem.heapTotal/1024/1024).toFixed(1),\n      rss: (mem.rss/1024/1024).toFixed(1),\n      external: (mem.external/1024/1024).toFixed(1),\n      cpuPercent,\n      uptime: process.uptime().toFixed(0),\n      activeHandles: process._getActiveHandles?.().length || 0,\n      activeRequests: process._getActiveRequests?.().length || 0,\n      pid: process.pid\n    };\n  }\n  measureEventLoopLag() {\n    const start = Date.now();\n    return new Promise(r => setImmediate(() => r(Date.now()-start)));\n  }\n}",hints:"process.cpuUsage() returns delta from last call if previous usage passed. Event loop lag: schedule setImmediate, measure actual delay.",solutionExplanation:"CPU usage: cpuUsage() delta / elapsed time = CPU%. Event loop lag: delay between scheduling and executing setImmediate shows loop blockage."},
  {lessonId:42,difficulty:"Easy",title:"dotenv Implementation",problemStatement:"Write a simple dotenv-like module that reads .env files and sets process.env variables. Support comments, quoted values, and interpolation.",examples:".env: DB_URL=mysql://localhost:3306/db. process.env.DB_URL is set after require('./dotenv').config()",starterCodeJs:"const fs = require('fs');\nconst path = require('path');\nfunction config({ path: filePath = '.env', override = false } = {}) {\n  const fullPath = path.resolve(process.cwd(), filePath);\n  let content;\n  try { content = fs.readFileSync(fullPath, 'utf8'); } catch { return { error: 'File not found' }; }\n  const parsed = {};\n  for (const line of content.split('\\n')) {\n    const trimmed = line.trim();\n    if (!trimmed || trimmed.startsWith('#')) continue; // skip empty/comments\n    const eqIndex = trimmed.indexOf('=');\n    if (eqIndex < 0) continue;\n    const key = trimmed.slice(0, eqIndex).trim();\n    let val = trimmed.slice(eqIndex+1).trim();\n    // Remove surrounding quotes\n    if ((val.startsWith('\"')&&val.endsWith('\"')) || (val.startsWith(\"'\")&&val.endsWith(\"'\"))) {\n      val = val.slice(1,-1);\n    }\n    // Interpolation: ${VAR}\n    val = val.replace(/\\$\\{([^}]+)\\}/g, (_, k) => process.env[k] || '');\n    parsed[key] = val;\n    if (override || process.env[key] === undefined) process.env[key] = val;\n  }\n  return { parsed };\n}\nmodule.exports = { config };",hints:"First = sign splits key/value (values can contain =). Strip quotes. Don't override if already in env (override:false). Interpolate ${VAR} from existing env.",solutionExplanation:"dotenv: parse KEY=VALUE, skip # comments, strip quotes, interpolate. Don't override existing vars (env > .env hierarchy)."},
  {lessonId:42,difficulty:"Hard",title:"Process Manager (PM2-like)",problemStatement:"Build a simple process manager that starts, stops, and restarts Node.js processes. Track status and auto-restart on crash.",examples:"pm.start('server.js', {name:'api', autorestart:true}). pm.stop('api'). pm.status() -> [{name,pid,status}]",starterCodeJs:"const { spawn } = require('child_process');\nconst { EventEmitter } = require('events');\nclass ProcessManager extends EventEmitter {\n  constructor() { super(); this._processes = new Map(); }\n  start(script, options = {}) {\n    const { name = script, env = {}, autorestart = true, maxRestarts = 5 } = options;\n    if (this._processes.has(name) && this._processes.get(name).status === 'running') throw new Error(`${name} already running`);\n    const info = { name, script, status: 'starting', restarts: 0, maxRestarts, autorestart, startTime: Date.now() };\n    this._processes.set(name, info);\n    this._spawn(name, script, env);\n    return info;\n  }\n  _spawn(name, script, env) {\n    const child = spawn(process.execPath, [script], { env: { ...process.env, ...env } });\n    const info = this._processes.get(name);\n    info.pid = child.pid;\n    info.status = 'running';\n    child.on('exit', (code) => {\n      info.status = 'stopped';\n      this.emit('exit', { name, code });\n      if (info.autorestart && code !== 0 && info.restarts < info.maxRestarts) {\n        info.restarts++;\n        console.log(`Restarting ${name} (${info.restarts}/${info.maxRestarts})...`);\n        setTimeout(() => this._spawn(name, script, env), 1000 * info.restarts);\n      }\n    });\n  }\n  stop(name) { const p=this._processes.get(name); if (p?.pid) { p.autorestart=false; process.kill(p.pid); } }\n  status() { return [...this._processes.values()]; }\n}",hints:"spawn() creates child process. Listen to 'exit' for crash detection. Disable autorestart before stop() to prevent unwanted restarts. Exponential backoff delay.",solutionExplanation:"Process manager: spawn child, track status. Auto-restart on non-zero exit code. Backoff delay (1s*restarts) prevents restart storms. Disable autorestart on manual stop."},
  {lessonId:42,difficulty:"Medium",title:"Environment Validation with Schema",problemStatement:"Build a schema-based environment validator using Zod-like syntax. Define expected env vars with types, defaults, and descriptions.",examples:"env.string('DB_URL').url(). env.number('PORT').default(3000).min(1024). env.boolean('DEBUG').default(false).",starterCodeJs:"class EnvSchema {\n  constructor() { this._fields = {}; }\n  string(key) { return this._field(key,'string'); }\n  number(key) { return this._field(key,'number'); }\n  boolean(key) { return this._field(key,'boolean'); }\n  _field(key, type) {\n    const config = { key, type, required:true, default:undefined, validators:[] };\n    this._fields[key] = config;\n    return {\n      default: (v) => { config.required=false; config.default=v; return this._field(key,type); },\n      optional: () => { config.required=false; return this._field(key,type); },\n      describe: (d) => { config.description=d; return this._field(key,type); },\n      url: () => { config.validators.push(v=>{ try{new URL(v);}catch{throw new Error(`${key} must be a valid URL`);} }); return this._field(key,type); },\n      min: (m) => { config.validators.push(v=>{ if(Number(v)<m) throw new Error(`${key} must be >= ${m}`); }); return this._field(key,type); }\n    };\n  }\n  parse(env=process.env) {\n    const result={};\n    const errors=[];\n    for (const [key,cfg] of Object.entries(this._fields)) {\n      let val=env[key];\n      if (val===undefined) { if(cfg.required) { errors.push(`Missing: ${key}`); continue; } val=String(cfg.default??''); }\n      if (cfg.type==='number') val=Number(val);\n      if (cfg.type==='boolean') val=val==='true'||val==='1';\n      try { cfg.validators.forEach(v=>v(val)); result[key]=val; } catch(e) { errors.push(e.message); }\n    }\n    if (errors.length) throw new Error('Env validation failed:\\n'+errors.join('\\n'));\n    return result;\n  }\n}\nmodule.exports = new EnvSchema();",hints:"Fluent API: methods return this (or a field-specific object). parse() checks all fields and collects all errors. Throw with all errors at once.",solutionExplanation:"Schema-based validation: define shape, validate at startup. Fluent API (chainable methods). Collect ALL errors before throwing (not just first)."},
  {lessonId:42,difficulty:"Easy",title:"Child Process Pool",problemStatement:"Build a pool of child processes for CPU-intensive work. Distribute tasks across processes, collect results.",examples:"pool.exec('compute', {n:40}) sends task to idle worker process, returns Promise with result.",starterCodeJs:"const { fork } = require('child_process');\nclass ChildProcessPool {\n  constructor(workerScript, size=4) {\n    this._workers = Array.from({length:size}, () => this._createWorker(workerScript));\n    this._queue = [];\n  }\n  _createWorker(script) {\n    const proc = fork(script);\n    const worker = { proc, busy: false };\n    proc.on('message', ({ id, result, error }) => {\n      const pending = worker._pending;\n      worker.busy = false;\n      worker._pending = null;\n      if (error) pending.reject(new Error(error));\n      else pending.resolve(result);\n      // Process next queued task\n      if (this._queue.length) {\n        const { task, resolve, reject } = this._queue.shift();\n        this._runTask(worker, task, resolve, reject);\n      }\n    });\n    return worker;\n  }\n  _runTask(worker, task, resolve, reject) {\n    worker.busy = true;\n    worker._pending = { resolve, reject };\n    worker.proc.send(task);\n  }\n  exec(type, data) {\n    return new Promise((resolve, reject) => {\n      const idle = this._workers.find(w => !w.busy);\n      const task = { type, data, id: Date.now() };\n      if (idle) this._runTask(idle, task, resolve, reject);\n      else this._queue.push({ task, resolve, reject });\n    });\n  }\n  terminate() { this._workers.forEach(w => w.proc.kill()); }\n}",hints:"fork() creates persistent child processes with IPC. Workers are idle or busy. Queue tasks when all busy. Return Promise per task.",solutionExplanation:"Process pool: fork N workers, distribute tasks. IPC via send/message. Pending callback per worker resolves Promise. Queue for when all workers busy."},
  {lessonId:42,difficulty:"Hard",title:"Memory Leak Detector",problemStatement:"Build a memory leak detector that tracks heap growth over time and alerts when growth exceeds a threshold.",examples:"detector.start(30000). Emits 'leak' event when heap grows consistently over N samples.",starterCodeJs:"const { EventEmitter } = require('events');\nclass MemoryLeakDetector extends EventEmitter {\n  constructor({ interval=30000, threshold=20, samples=5 }={}) {\n    super();\n    this._interval = interval;\n    this._threshold = threshold; // MB growth threshold\n    this._samples = samples;\n    this._history = [];\n    this._timer = null;\n  }\n  start() {\n    this._timer = setInterval(() => this._check(), this._interval);\n    return this;\n  }\n  stop() { clearInterval(this._timer); }\n  _check() {\n    const { heapUsed } = process.memoryUsage();\n    const heapMB = heapUsed / 1024 / 1024;\n    this._history.push({ time: Date.now(), heap: heapMB });\n    if (this._history.length > this._samples * 2) this._history.shift();\n    if (this._history.length >= this._samples) {\n      const recent = this._history.slice(-this._samples);\n      const growth = recent[recent.length-1].heap - recent[0].heap;\n      const allIncreasing = recent.every((s,i) => i===0 || s.heap >= recent[i-1].heap);\n      if (allIncreasing && growth > this._threshold) {\n        this.emit('leak', { growth: growth.toFixed(1), startHeap: recent[0].heap.toFixed(1), currentHeap: heapMB.toFixed(1), samples: recent });\n      }\n    }\n    this.emit('sample', { heap: heapMB.toFixed(1), time: new Date().toISOString() });\n  }\n}",hints:"Leak signature: heap grows consistently across N samples (not just once). allIncreasing checks monotonic growth. Keep rolling window of samples.",solutionExplanation:"Heuristic leak detection: N consecutive increases over threshold. Not foolproof (GC pauses affect measurement) but catches obvious leaks. Use heapDump for confirmation."},
  {lessonId:42,difficulty:"Medium",title:"App Bootstrap System",problemStatement:"Build an application bootstrap system that initializes services in dependency order. Service A must start before Service B that depends on it.",examples:"bootstrap.register('db', dbInit, []). bootstrap.register('cache', cacheInit, ['db']). bootstrap.start() resolves deps.",starterCodeJs:"class Bootstrap {\n  constructor() { this._services = new Map(); this._started = new Set(); }\n  register(name, factory, deps=[]) {\n    this._services.set(name, { name, factory, deps });\n    return this;\n  }\n  async start() {\n    const instances = {};\n    const starting = new Set();\n    const start = async (name) => {\n      if (this._started.has(name)) return;\n      if (starting.has(name)) throw new Error(`Circular dependency detected: ${name}`);\n      starting.add(name);\n      const svc = this._services.get(name);\n      if (!svc) throw new Error(`Unknown service: ${name}`);\n      await Promise.all(svc.deps.map(dep => start(dep)));\n      console.log(`Starting ${name}...`);\n      instances[name] = await svc.factory(instances);\n      this._started.add(name);\n      starting.delete(name);\n    };\n    for (const name of this._services.keys()) await start(name);\n    return instances;\n  }\n  async stop(instances) {\n    const names = [...this._started].reverse();\n    for (const name of names) {\n      if (instances[name]?.close) await instances[name].close();\n    }\n  }\n}",hints:"DFS resolution: start dependencies first. Track 'starting' set for circular dep detection. Reverse order for shutdown.",solutionExplanation:"Dependency-ordered bootstrap: DFS graph traversal. Circular detection via 'starting' set. Shutdown in reverse order (dependents before dependencies)."}
];

async function main() {
  let qi=0,qs=0,ci=0,cs=0;
  for (const q of quizQuestions) {
    const exists = await p.quizQuestion.findFirst({where:{lessonId:q.lessonId,question:q.question}});
    if (!exists) { await p.quizQuestion.create({data:q}); qi++; } else qs++;
  }
  for (const q of codingQuestions) {
    const exists = await p.practiceQuestion.findFirst({where:{lessonId:q.lessonId,title:q.title}});
    if (!exists) { await p.practiceQuestion.create({data:q}); ci++; } else cs++;
  }
  console.log(`Quiz: ${qi} inserted, ${qs} skipped. Coding: ${ci} inserted, ${cs} skipped.`);
}
main().catch(console.error).finally(()=>p.$disconnect());
