const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const codingQuestions = [
  // Lesson 44 - Express Basics coding
  {lessonId:44,difficulty:"Easy",title:"Basic Express Server",problemStatement:"Create a basic Express server with routes: GET / returns welcome message, GET /health returns status JSON, and a 404 handler for unknown routes.",examples:"GET / -> {message:'Welcome'}. GET /health -> {status:'ok',uptime:123}. GET /unknown -> 404",starterCodeJs:"const express = require('express');\nconst app = express();\napp.use(express.json());\napp.get('/', (req, res) => { res.json({ message: 'Welcome to the API', version: '1.0.0' }); });\napp.get('/health', (req, res) => { res.json({ status: 'ok', uptime: process.uptime(), timestamp: new Date().toISOString() }); });\napp.use((req, res) => { res.status(404).json({ error: 'Not Found', path: req.path }); });\napp.use((err, req, res, next) => { console.error(err.stack); res.status(500).json({ error: 'Internal Server Error' }); });\nmodule.exports = app;\nif (require.main === module) app.listen(3000, () => console.log('Running on port 3000'));",hints:"express.json() parses JSON bodies. 404 handler must be after all routes. Error handler needs 4 params (err,req,res,next).",solutionExplanation:"Express middleware runs in order. 404 catch-all at end. Error handlers identified by 4-param signature."},
  {lessonId:44,difficulty:"Easy",title:"CRUD Routes for Todos",problemStatement:"Build complete CRUD routes for a todos resource using an in-memory array. GET /todos, GET /todos/:id, POST /todos, PUT /todos/:id, DELETE /todos/:id.",examples:"POST /todos {text:'Buy milk'} -> 201 {id:1,text:'Buy milk',done:false}",starterCodeJs:"const express = require('express');\nconst router = express.Router();\nlet todos = [];\nlet nextId = 1;\nrouter.get('/', (req, res) => res.json(todos));\nrouter.get('/:id', (req, res) => {\n  const todo = todos.find(t => t.id === parseInt(req.params.id));\n  if (!todo) return res.status(404).json({ error: 'Todo not found' });\n  res.json(todo);\n});\nrouter.post('/', (req, res) => {\n  const { text } = req.body;\n  if (!text) return res.status(400).json({ error: 'text is required' });\n  const todo = { id: nextId++, text, done: false, createdAt: new Date().toISOString() };\n  todos.push(todo);\n  res.status(201).json(todo);\n});\nrouter.put('/:id', (req, res) => {\n  const i = todos.findIndex(t => t.id === parseInt(req.params.id));\n  if (i < 0) return res.status(404).json({ error: 'Not found' });\n  todos[i] = { ...todos[i], ...req.body, id: todos[i].id };\n  res.json(todos[i]);\n});\nrouter.delete('/:id', (req, res) => {\n  const i = todos.findIndex(t => t.id === parseInt(req.params.id));\n  if (i < 0) return res.status(404).json({ error: 'Not found' });\n  todos.splice(i, 1);\n  res.status(204).end();\n});\nmodule.exports = router;",hints:"parseInt for numeric IDs. 204 No Content for DELETE. Spread existing todo then override with body to prevent ID tampering.",solutionExplanation:"REST CRUD maps to HTTP methods. 201 Created for POST. 204 No Content for successful DELETE. findIndex for update/delete."},
  {lessonId:44,difficulty:"Medium",title:"Request Validation Middleware",problemStatement:"Build a validation middleware factory using a schema object. Validate body fields, return 400 with all errors if invalid.",examples:"validate({name:'required|string',age:'required|number|min:0'}) as middleware",starterCodeJs:"function validate(schema) {\n  return (req, res, next) => {\n    const errors = [];\n    for (const [field, rules] of Object.entries(schema)) {\n      const value = req.body[field];\n      const ruleList = rules.split('|');\n      for (const rule of ruleList) {\n        const [name, param] = rule.split(':');\n        if (name === 'required' && (value === undefined || value === null || value === '')) {\n          errors.push({ field, message: `${field} is required` }); break;\n        }\n        if (value === undefined) continue;\n        if (name === 'string' && typeof value !== 'string') errors.push({ field, message: `${field} must be a string` });\n        if (name === 'number' && typeof value !== 'number') errors.push({ field, message: `${field} must be a number` });\n        if (name === 'email' && !/^[^@]+@[^@]+\\.[^@]+$/.test(value)) errors.push({ field, message: `${field} must be a valid email` });\n        if (name === 'min' && value < Number(param)) errors.push({ field, message: `${field} must be at least ${param}` });\n        if (name === 'max' && value > Number(param)) errors.push({ field, message: `${field} must be at most ${param}` });\n        if (name === 'minLength' && String(value).length < Number(param)) errors.push({ field, message: `${field} must be at least ${param} characters` });\n      }\n    }\n    if (errors.length) return res.status(400).json({ errors });\n    next();\n  };\n}",hints:"Return all errors at once (not just first). Break on required failure to avoid checking further rules. Middleware factory returns a middleware function.",solutionExplanation:"Validation middleware factory pattern. Split rules on | and : for rule name/param. Collect all errors before responding."},
  {lessonId:44,difficulty:"Medium",title:"API Rate Limiter Middleware",problemStatement:"Write Express middleware that rate limits by IP: max 100 requests per 15 minutes. Return 429 with Retry-After header when exceeded.",examples:"POST /api/login limited to 5 per 15min per IP. 429 with Retry-After:900 header.",starterCodeJs:"function rateLimit({ windowMs = 15*60*1000, max = 100, message = 'Too many requests' } = {}) {\n  const store = new Map();\n  return (req, res, next) => {\n    const key = req.ip || req.connection.remoteAddress;\n    const now = Date.now();\n    const windowStart = now - windowMs;\n    if (!store.has(key)) store.set(key, []);\n    let hits = store.get(key).filter(t => t > windowStart);\n    store.set(key, hits);\n    res.setHeader('X-RateLimit-Limit', max);\n    res.setHeader('X-RateLimit-Remaining', Math.max(0, max - hits.length - 1));\n    if (hits.length >= max) {\n      const resetAt = hits[0] + windowMs;\n      res.setHeader('Retry-After', Math.ceil((resetAt - now) / 1000));\n      return res.status(429).json({ error: message, retryAfter: Math.ceil((resetAt - now) / 1000) });\n    }\n    hits.push(now);\n    store.set(key, hits);\n    next();\n  };\n}",hints:"Sliding window: filter out timestamps older than windowMs. Set standard rate limit headers. Retry-After in seconds.",solutionExplanation:"Sliding window rate limiter. Standard headers: X-RateLimit-Limit, X-RateLimit-Remaining. 429 Too Many Requests with Retry-After header."},
  {lessonId:44,difficulty:"Hard",title:"JWT Authentication Middleware",problemStatement:"Build JWT authentication middleware for Express. Include: generateToken, verifyToken middleware, and refresh token endpoint.",examples:"POST /auth/login -> {token, refreshToken}. Middleware: verifyToken adds req.user. POST /auth/refresh exchanges refresh token.",starterCodeJs:"const jwt = require('jsonwebtoken');\nconst SECRET = process.env.JWT_SECRET || 'dev-secret';\nconst REFRESH_SECRET = process.env.JWT_REFRESH_SECRET || 'dev-refresh';\nfunction generateTokens(user) {\n  const payload = { sub: user.id, email: user.email, role: user.role };\n  const token = jwt.sign(payload, SECRET, { expiresIn: '15m' });\n  const refreshToken = jwt.sign({ sub: user.id }, REFRESH_SECRET, { expiresIn: '7d' });\n  return { token, refreshToken };\n}\nfunction verifyToken(req, res, next) {\n  const auth = req.headers.authorization;\n  if (!auth?.startsWith('Bearer ')) return res.status(401).json({ error: 'No token provided' });\n  try {\n    const decoded = jwt.verify(auth.slice(7), SECRET);\n    req.user = decoded;\n    next();\n  } catch (err) {\n    if (err.name === 'TokenExpiredError') return res.status(401).json({ error: 'Token expired' });\n    return res.status(401).json({ error: 'Invalid token' });\n  }\n}\nfunction optionalAuth(req, res, next) {\n  const auth = req.headers.authorization;\n  if (auth?.startsWith('Bearer ')) {\n    try { req.user = jwt.verify(auth.slice(7), SECRET); } catch {}\n  }\n  next();\n}",hints:"Short-lived access token (15m) + long-lived refresh token (7d). Distinguish TokenExpiredError from invalid token. optionalAuth for public-but-enhanced routes.",solutionExplanation:"JWT auth: access token is short-lived for security. Refresh token exchanges for new access token without re-login. Bearer prefix is convention."},
  {lessonId:44,difficulty:"Easy",title:"Express Router Organization",problemStatement:"Organize an Express app with separate routers for /users, /posts, and /auth. Show how to structure routes in separate files and mount them.",examples:"app.use('/api/users', usersRouter). app.use('/api/posts', postsRouter). app.use('/api/auth', authRouter).",starterCodeJs:"// routes/users.js\nconst express = require('express');\nconst router = express.Router();\nrouter.get('/', async (req, res) => { res.json(await db.user.findMany()); });\nrouter.get('/:id', async (req, res) => {\n  const user = await db.user.findUnique({ where: { id: parseInt(req.params.id) } });\n  if (!user) return res.status(404).json({ error: 'User not found' });\n  res.json(user);\n});\nmodule.exports = router;\n// app.js\nconst express = require('express');\nconst app = express();\napp.use(express.json());\nconst usersRouter = require('./routes/users');\nconst postsRouter = require('./routes/posts');\nconst authRouter = require('./routes/auth');\napp.use('/api/users', usersRouter);\napp.use('/api/posts', postsRouter);\napp.use('/api/auth', authRouter);\nmodule.exports = app;",hints:"Each router file exports a Router instance. app.use mounts it at a prefix. Routes inside the file are relative to the prefix.",solutionExplanation:"Modular routing: each feature gets its own router file. Mounted with prefix so /users inside file becomes /api/users in the app."},
  {lessonId:44,difficulty:"Medium",title:"File Upload Handler",problemStatement:"Build an Express endpoint that accepts file uploads using multer. Validate file type (images only), limit size to 5MB, and return the file URL.",examples:"POST /upload with multipart/form-data -> {url:'/uploads/uuid.jpg', size:12345}",starterCodeJs:"const multer = require('multer');\nconst path = require('path');\nconst { v4: uuid } = require('uuid');\nconst storage = multer.diskStorage({\n  destination: (req, file, cb) => cb(null, 'uploads/'),\n  filename: (req, file, cb) => cb(null, uuid() + path.extname(file.originalname).toLowerCase())\n});\nconst upload = multer({\n  storage,\n  limits: { fileSize: 5 * 1024 * 1024 },\n  fileFilter: (req, file, cb) => {\n    const allowed = /jpeg|jpg|png|gif|webp/;\n    const ext = allowed.test(path.extname(file.originalname).toLowerCase());\n    const mime = allowed.test(file.mimetype);\n    if (ext && mime) cb(null, true); else cb(new Error('Only images allowed'));\n  }\n});\nconst router = require('express').Router();\nrouter.post('/upload', upload.single('file'), (req, res) => {\n  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });\n  res.json({ url: `/uploads/${req.file.filename}`, size: req.file.size, mimetype: req.file.mimetype });\n});\nrouter.use((err, req, res, next) => {\n  if (err instanceof multer.MulterError) return res.status(400).json({ error: err.message });\n  res.status(400).json({ error: err.message });\n});",hints:"Check both extension and mimetype for security. uuid() for unique filename prevents collisions. MulterError instanceof check for specific multer errors.",solutionExplanation:"Check mimetype AND extension - mimetype alone can be spoofed. UUID filename prevents conflicts and path traversal attacks."},
  {lessonId:44,difficulty:"Hard",title:"Response Caching Middleware",problemStatement:"Build Express middleware that caches GET responses in memory with TTL. Skip cache for authenticated requests. Include cache-control headers.",examples:"First GET /api/products -> hits DB, caches 60s. Second GET -> from cache. Cache-Control: max-age=60",starterCodeJs:"function cacheMiddleware({ ttl = 60, skipAuth = true } = {}) {\n  const cache = new Map();\n  return (req, res, next) => {\n    if (req.method !== 'GET') return next();\n    if (skipAuth && req.headers.authorization) return next();\n    const key = req.originalUrl;\n    const cached = cache.get(key);\n    if (cached && Date.now() < cached.expiresAt) {\n      res.setHeader('X-Cache', 'HIT');\n      res.setHeader('Cache-Control', `max-age=${Math.ceil((cached.expiresAt - Date.now()) / 1000)}`);\n      return res.status(cached.status).json(cached.body);\n    }\n    const originalJson = res.json.bind(res);\n    res.json = (body) => {\n      if (res.statusCode < 400) {\n        cache.set(key, { body, status: res.statusCode, expiresAt: Date.now() + ttl * 1000 });\n      }\n      res.setHeader('X-Cache', 'MISS');\n      res.setHeader('Cache-Control', `max-age=${ttl}`);\n      return originalJson(body);\n    };\n    next();\n  };\n}",hints:"Monkey-patch res.json to intercept the response before it's sent. Only cache successful responses. Skip cache for authenticated users.",solutionExplanation:"Intercept res.json by replacing it. Cache key = full URL. Skip auth responses to prevent serving one user's data to another."},
  {lessonId:44,difficulty:"Easy",title:"Environment-based Config",problemStatement:"Create an Express app config system that loads different settings for development, test, and production environments.",examples:"NODE_ENV=production -> shorter logs, stricter CORS. NODE_ENV=development -> verbose, any origin.",starterCodeJs:"const configs = {\n  development: {\n    port: 3000,\n    cors: { origin: '*' },\n    logLevel: 'debug',\n    rateLimit: { max: 1000, windowMs: 60000 }\n  },\n  test: {\n    port: 3001,\n    cors: { origin: '*' },\n    logLevel: 'silent',\n    rateLimit: { max: 10000, windowMs: 60000 }\n  },\n  production: {\n    port: parseInt(process.env.PORT) || 8080,\n    cors: { origin: (process.env.ALLOWED_ORIGINS || '').split(','), credentials: true },\n    logLevel: 'warn',\n    rateLimit: { max: 100, windowMs: 15 * 60 * 1000 }\n  }\n};\nconst env = process.env.NODE_ENV || 'development';\nif (!configs[env]) throw new Error(`Unknown environment: ${env}`);\nconst config = configs[env];\nmodule.exports = config;",hints:"NODE_ENV drives all config. Fail fast if unknown env. Production CORS must be explicit origins list, not wildcard.",solutionExplanation:"Environment-based config: one object per env. Fail on unknown NODE_ENV to prevent misconfiguration. Production has strictest settings."},
  {lessonId:44,difficulty:"Medium",title:"Logging Middleware",problemStatement:"Build an Express request logging middleware that logs method, path, status, and duration. Support different log formats and exclude health check endpoints.",examples:"GET /api/users 200 45ms [2024-01-01T00:00:00Z]",starterCodeJs:"function logger({ format = 'common', exclude = ['/health'] } = {}) {\n  return (req, res, next) => {\n    if (exclude.includes(req.path)) return next();\n    const start = Date.now();\n    const { method, url, ip } = req;\n    res.on('finish', () => {\n      const ms = Date.now() - start;\n      const { statusCode } = res;\n      const color = statusCode >= 500 ? '\\x1b[31m' : statusCode >= 400 ? '\\x1b[33m' : statusCode >= 300 ? '\\x1b[36m' : '\\x1b[32m';\n      const reset = '\\x1b[0m';\n      if (format === 'json') {\n        console.log(JSON.stringify({ time: new Date().toISOString(), method, url, status: statusCode, ms, ip }));\n      } else {\n        console.log(`${color}${method}${reset} ${url} ${color}${statusCode}${reset} ${ms}ms`);\n      }\n    });\n    next();\n  };\n}",hints:"Listen to res 'finish' event to log after response sent. Date.now() before next() and in finish handler gives duration. ANSI codes for color.",solutionExplanation:"Log on 'finish' event (not before next()) to capture actual status code. Duration = finish time - request start time."}
];

const quizQuestions = [
  // Lesson 49 - SQL Databases
  {lessonId:49,question:"What is a primary key in SQL?",options:["A foreign reference","A unique identifier for each row in a table","An index on a column","A table alias"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:49,question:"What does a JOIN do in SQL?",options:["Deletes related rows","Combines rows from two or more tables based on a condition","Creates a new table","Copies data between tables"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:49,question:"What is the difference between INNER JOIN and LEFT JOIN?",options:["No difference","INNER JOIN returns only matching rows; LEFT JOIN returns all left table rows plus matches","LEFT JOIN is faster","INNER JOIN includes NULLs"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:49,question:"What does GROUP BY do?",options:["Sorts results","Groups rows with the same values in specified columns for aggregate functions","Filters groups","Joins tables"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:49,question:"What is a transaction in SQL?",options:["A query","A sequence of operations treated as a single unit - all succeed or all fail","A stored procedure","A view"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:49,question:"What does ACID stand for in databases?",options:["Access Control ID","Atomicity, Consistency, Isolation, Durability","Advanced Concurrent Integrated Database","Automated Cache Invalidation Design"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:49,question:"What is a database index and what is its purpose?",options:["A backup copy","A data structure that speeds up data retrieval at the cost of storage","A foreign key constraint","A table view"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:49,question:"What is SQL injection and how do you prevent it?",options:["A type of index","An attack via unsanitized SQL input; prevented by parameterized queries","A backup strategy","A JOIN type"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:49,question:"What is the difference between DELETE and TRUNCATE?",options:["No difference","DELETE removes rows one by one (can filter); TRUNCATE removes all rows faster without logging","TRUNCATE is slower","DELETE cannot use WHERE"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:49,question:"What is a database view?",options:["A physical table","A virtual table based on a SELECT query","A stored procedure","A trigger"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 50 - NoSQL Databases
  {lessonId:50,question:"What type of database is MongoDB?",options:["Relational","Document-oriented NoSQL","Key-value store","Graph database"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:50,question:"What is a MongoDB collection?",options:["A SQL table equivalent that stores documents","A database index","A query result","A stored procedure"],correctAnswer:0,difficulty:"Easy"},
  {lessonId:50,question:"What is the difference between SQL and NoSQL databases?",options:["SQL is newer","SQL uses tables with fixed schema; NoSQL uses flexible schemas with various data models","NoSQL is always faster","SQL cannot scale horizontally"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:50,question:"What is sharding in NoSQL?",options:["Data encryption","Horizontal partitioning of data across multiple servers for scalability","Data compression","Indexing strategy"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:50,question:"What is Redis primarily used for?",options:["Storing large files","In-memory key-value store for caching and session storage","Graph traversal","Full-text search"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:50,question:"What does eventual consistency mean in distributed databases?",options:["Data is always immediately consistent","Given enough time without new updates, all replicas will converge to the same value","Data is never consistent","Consistency is enforced by locks"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:50,question:"What is the CAP theorem?",options:["A query optimization technique","A distributed system can only guarantee 2 of 3: Consistency, Availability, Partition Tolerance","A caching algorithm","A database design pattern"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:50,question:"What is a MongoDB document?",options:["A SQL row","A BSON (JSON-like) record stored in a collection","A database schema","A query result set"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:50,question:"When should you choose NoSQL over SQL?",options:["Never","For flexible/evolving schemas, high volume unstructured data, or horizontal scaling needs","For all financial data","For simple applications only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:50,question:"What is a Redis TTL?",options:["Transaction Type Level","Time To Live - expiry time after which a key is automatically deleted","Transfer Token Limit","Thread Task Lock"],correctAnswer:1,difficulty:"Easy"},

  // Lesson 51 - ORM and Prisma
  {lessonId:51,question:"What is an ORM?",options:["A query language","Object-Relational Mapper - maps database tables to programming language objects","A database type","A caching layer"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:51,question:"What does Prisma Client do?",options:["Provides a GUI for databases","Auto-generated type-safe database client based on your schema","Manages migrations only","Handles authentication"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:51,question:"What is the Prisma schema used for?",options:["Frontend styling","Defining data models, relations, and database configuration","API documentation","Authentication config"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:51,question:"What does prisma migrate dev do?",options:["Deploys to production","Creates and applies database migrations in development","Generates Prisma Client","Seeds the database"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:51,question:"How do you define a one-to-many relation in Prisma schema?",options:["With @join","With @relation and foreign key fields on the many side","With @hasMany","With a junction table only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:51,question:"What is Prisma's findUnique vs findFirst?",options:["No difference","findUnique requires a unique field; findFirst returns first match of any query","findFirst is faster","findUnique can return multiple"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:51,question:"What is an N+1 query problem in ORMs?",options:["A type of SQL error","Fetching a list then making one query per item instead of joining","A migration issue","A connection pool problem"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:51,question:"How does Prisma handle transactions?",options:["It doesn't support transactions","Via prisma.$transaction() which takes an array of operations or interactive callback","With raw SQL only","Automatically for all operations"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:51,question:"What is the purpose of @default in Prisma schema?",options:["Marks required fields","Sets the default value for a field when not provided","Defines index","Sets field as unique"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:51,question:"What does Prisma's include do?",options:["Adds new fields","Eagerly loads related records (like JOIN) in the query result","Filters results","Sets field visibility"],correctAnswer:1,difficulty:"Medium"},

  // Lesson 52 - Database Design
  {lessonId:52,question:"What is database normalization?",options:["Encrypting the database","Organizing data to reduce redundancy and improve data integrity","Adding more columns","Indexing all fields"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:52,question:"What is a foreign key constraint?",options:["A unique field","A reference to a primary key in another table that enforces referential integrity","A composite index","A table alias"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:52,question:"What is denormalization and when is it used?",options:["Deleting normalized data","Intentionally adding redundancy for read performance at the cost of write complexity","A backup strategy","Removing indexes"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:52,question:"What is the difference between 1NF, 2NF, and 3NF?",options:["Just naming conventions","Progressive levels of normalization - atomic values, full dependency, no transitive dependency","Different database types","Query optimization levels"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:52,question:"What is a junction table (bridge table)?",options:["A temporary table","A table resolving many-to-many relationships between two entities","A view","An index table"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:52,question:"What is the purpose of a composite primary key?",options:["Faster queries","A primary key made of multiple columns, used when no single column is unique","To allow NULLs","To improve joins"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:52,question:"What is an entity-relationship (ER) diagram?",options:["A flowchart","A visual representation of database tables and their relationships","A query plan","A backup schema"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:52,question:"When should you add a database index?",options:["On every column","On columns frequently used in WHERE, JOIN, or ORDER BY clauses with high cardinality","On primary keys only","Never, the DB optimizes automatically"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:52,question:"What is soft delete vs hard delete?",options:["No difference","Soft delete marks record as deleted (deleted_at column); hard delete removes the row","Soft is faster","Hard is reversible"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:52,question:"What is database sharding?",options:["Database encryption","Horizontal partitioning - splitting data across multiple database instances by a shard key","Vertical scaling","Table compression"],correctAnswer:1,difficulty:"Hard"},

  // Lesson 53 - Database Performance
  {lessonId:53,question:"What is the N+1 query problem?",options:["A SQL syntax error","Fetching N parent records then making N additional queries for children, instead of 1 JOIN","A connection limit","A transaction error"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:53,question:"What is query execution plan and how do you view it?",options:["A database backup","The steps a database takes to execute a query; viewed with EXPLAIN or EXPLAIN ANALYZE","A stored procedure","A migration file"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:53,question:"What is database connection pooling?",options:["Backing up connections","Reusing a pool of pre-established database connections instead of creating new ones per request","Load balancing","Caching query results"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:53,question:"What is a covering index?",options:["An index on all columns","An index that contains all columns needed by a query, avoiding table lookups","A primary index","A partial index"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:53,question:"What is read replica and when do you use it?",options:["A database backup","A copy of the primary database for read operations, reducing load on primary","A caching layer","A standby database"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:53,question:"What does EXPLAIN ANALYZE show that EXPLAIN alone doesn't?",options:["No difference","Actual execution times and row counts (runs the query), not just estimated plan","More columns","Table structure"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:53,question:"What is database caching and what are common strategies?",options:["Only Redis caching","Storing query results to reduce DB load; strategies: cache-aside, write-through, write-behind","Only in-app memory","Database internal only"],correctAnswer:1,difficulty:"Medium"},
  {lessonId:53,question:"What is a slow query log?",options:["A query that failed","A database feature that logs queries exceeding a time threshold for optimization","An error log","A transaction log"],correctAnswer:1,difficulty:"Easy"},
  {lessonId:53,question:"What is optimistic locking in databases?",options:["A locking strategy that always acquires locks","Assumes no conflict, uses version field to detect concurrent modifications without locking","A deadlock prevention","A transaction isolation level"],correctAnswer:1,difficulty:"Hard"},
  {lessonId:53,question:"What is a database deadlock?",options:["A slow query","Two or more transactions waiting for each other's locks, causing permanent block","A connection timeout","A failed migration"],correctAnswer:1,difficulty:"Medium"}
];

async function main() {
  let qi = 0, qs = 0, ci = 0, cs = 0;
  for (const q of quizQuestions) {
    const exists = await p.quizQuestion.findFirst({ where: { lessonId: q.lessonId, question: q.question } });
    if (!exists) { await p.quizQuestion.create({ data: q }); qi++; } else qs++;
  }
  for (const q of codingQuestions) {
    const exists = await p.practiceQuestion.findFirst({ where: { lessonId: q.lessonId, title: q.title } });
    if (!exists) { await p.practiceQuestion.create({ data: q }); ci++; } else cs++;
  }
  console.log(`Quiz: ${qi} inserted, ${qs} skipped. Coding: ${ci} inserted, ${cs} skipped.`);
}

main().catch(console.error).finally(() => p.$disconnect());
