const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const quizQuestions = [
  // Lesson 31 - React Fundamentals
  {lessonId:31,sortOrder:1,difficulty:"Easy",question:"What is JSX?",options:["JavaScript XML","A build tool","A CSS preprocessor","A templating engine"],correctAnswer:0,explanation:"JSX = JavaScript XML. Syntax extension that looks like HTML but compiles to React.createElement() calls."},
  {lessonId:31,sortOrder:2,difficulty:"Easy",question:"What does a React component return?",options:["HTML string","JSX which describes the UI","CSS styles","A DOM node"],correctAnswer:1,explanation:"Components return JSX (React elements). React renders these elements to the DOM via reconciliation."},
  {lessonId:31,sortOrder:3,difficulty:"Medium",question:"What is the Virtual DOM?",options:["A browser feature","A lightweight JavaScript object tree that React uses to diff and batch DOM updates","A CSS module","A build optimization"],correctAnswer:1,explanation:"React maintains a virtual DOM. On state change, it diffs old and new virtual DOM trees, then applies minimal real DOM changes."},
  {lessonId:31,sortOrder:4,difficulty:"Medium",question:"What triggers a React re-render?",options:["Any JS variable change","State change, prop change, or parent re-render (unless memoized)","Every second","DOM mutation"],correctAnswer:1,explanation:"React re-renders when: useState/useReducer state changes, props change, or parent re-renders. Context changes also trigger re-renders."},
  {lessonId:31,sortOrder:5,difficulty:"Medium",question:"What is the key prop used for in lists?",options:["CSS styling","Helping React identify which items changed, were added, or removed during reconciliation","A performance flag","An HTML attribute"],correctAnswer:1,explanation:"Keys help React identify list items. Without stable keys, React may incorrectly reuse DOM nodes. Use stable IDs, not array indices."},
  {lessonId:31,sortOrder:6,difficulty:"Medium",question:"What is the difference between controlled and uncontrolled components?",options:["No difference","Controlled: React state owns input value. Uncontrolled: DOM owns value via ref","Controlled is faster","Uncontrolled is deprecated"],correctAnswer:1,explanation:"Controlled: onChange + value in state. Uncontrolled: ref.current.value. Controlled is preferred for validation and forms."},
  {lessonId:31,sortOrder:7,difficulty:"Hard",question:"What is React reconciliation?",options:["State management","The process of diffing two React element trees to determine minimal DOM mutations","A build process","Component mounting"],correctAnswer:1,explanation:"Reconciliation: React diffs the old and new element trees. Same type = update, different type = replace. Keys optimize list reconciliation."},
  {lessonId:31,sortOrder:8,difficulty:"Hard",question:"What does React.StrictMode do?",options:["Enforces TypeScript","Detects side effects by double-invoking render, effects, and reducers in development","Enables strict CSS","Prevents XSS"],correctAnswer:1,explanation:"StrictMode double-invokes functions to detect impure renders and deprecated APIs. Only active in development mode."},
  {lessonId:31,sortOrder:9,difficulty:"Hard",question:"What is the difference between React.memo and useMemo?",options:["No difference","React.memo memoizes component re-renders; useMemo memoizes values inside a component","useMemo is for components","React.memo is deprecated"],correctAnswer:1,explanation:"React.memo wraps a component to skip re-render if props haven't changed. useMemo caches a computed value between renders."},
  {lessonId:31,sortOrder:10,difficulty:"Hard",question:"What is the Fiber architecture?",options:["A CSS feature","React's reconciliation engine that enables incremental rendering, prioritization, and concurrent features","A build tool","A data fetching pattern"],correctAnswer:1,explanation:"React Fiber reimplemented reconciliation as a linked list of work units (fibers). Enables pausing, aborting, and prioritizing work."},

  // Lesson 32 - React Hooks
  {lessonId:32,sortOrder:1,difficulty:"Easy",question:"What does useState return?",options:["A value only","An array with [currentState, setterFunction]","An object with state and dispatch","A Promise"],correctAnswer:1,explanation:"const [count, setCount] = useState(0). Destructure [state, setter] from the array returned by useState."},
  {lessonId:32,sortOrder:2,difficulty:"Easy",question:"When does useEffect run?",options:["Before render","After every render by default, or when specified dependencies change","Only on mount","Only on unmount"],correctAnswer:1,explanation:"With []: mount only. With [dep]: when dep changes. Without array: every render. Return a cleanup function for unmount."},
  {lessonId:32,sortOrder:3,difficulty:"Medium",question:"What is the purpose of useCallback?",options:["Creates a callback URL","Memoizes a function reference so it stays stable across renders unless dependencies change","Debounces a callback","Creates async callbacks"],correctAnswer:1,explanation:"useCallback prevents function recreation on every render. Important when passing callbacks to memoized child components or useEffect deps."},
  {lessonId:32,sortOrder:4,difficulty:"Medium",question:"What does useRef return?",options:["A reactive value","A mutable ref object {current: value} that persists across renders without causing re-renders","A DOM element","A callback"],correctAnswer:1,explanation:"useRef persists data without triggering re-renders. Used for: DOM references, interval IDs, previous values, instance variables."},
  {lessonId:32,sortOrder:5,difficulty:"Medium",question:"What is useReducer used for?",options:["HTTP requests","Complex state logic with multiple sub-values or when next state depends on previous in complex ways","Global state","Async operations"],correctAnswer:1,explanation:"useReducer(reducer, initialState) returns [state, dispatch]. Better than multiple useStates for complex state logic."},
  {lessonId:32,sortOrder:6,difficulty:"Medium",question:"What does useLayoutEffect differ from useEffect?",options:["No difference","useLayoutEffect fires synchronously after DOM mutations but before browser paint. Blocks paint.","useLayoutEffect is async","useEffect fires before DOM mutations"],correctAnswer:1,explanation:"useLayoutEffect: read DOM measurements, prevent visual flash. Fires before paint. Prefer useEffect for most cases to avoid blocking paint."},
  {lessonId:32,sortOrder:7,difficulty:"Hard",question:"What are the rules of hooks?",options:["Any rules","Only call hooks at top level (not in conditions/loops), only in React functions (not regular JS)","Hooks must be named useX","Hooks cannot return values"],correctAnswer:1,explanation:"Rules: 1) Only call hooks at top level - not in loops, conditions, or nested functions. 2) Only call in React function components or custom hooks."},
  {lessonId:32,sortOrder:8,difficulty:"Hard",question:"What is a custom hook?",options:["A native browser hook","A function prefixed with 'use' that composes built-in hooks into reusable stateful logic","A component","An event handler"],correctAnswer:1,explanation:"Custom hooks are regular functions that use other hooks. They extract stateful logic and can be shared between components."},
  {lessonId:32,sortOrder:9,difficulty:"Hard",question:"What is the stale closure problem in useEffect?",options:["Memory leak","The effect captures the value of state/props at creation time. If state updates, the effect still sees the old value unless re-run.","A render bug","A TypeScript issue"],correctAnswer:1,explanation:"Solution: add the dependency to the deps array so the effect re-runs with fresh values, or use a ref to always have current value."},
  {lessonId:32,sortOrder:10,difficulty:"Hard",question:"What does the useImperativeHandle hook do?",options:["Handles user events","Customizes the ref value exposed when using forwardRef — lets parent call specific methods on child","Handles form submission","Manages animations"],correctAnswer:1,explanation:"useImperativeHandle(ref, () => ({focus, reset})) with forwardRef lets parent call child.current.focus() etc."},

  // Lesson 33 - State Management
  {lessonId:33,sortOrder:1,difficulty:"Easy",question:"What problem does Context API solve?",options:["Performance","Prop drilling — passing data through many component levels without passing props manually at every level","Async state","Module imports"],correctAnswer:1,explanation:"Context provides a way to share values between components without explicitly passing props through every intermediate component."},
  {lessonId:33,sortOrder:2,difficulty:"Easy",question:"What is prop drilling?",options:["A build tool","Passing props through many intermediate component layers that don't need the data just to reach a deeply nested component","A state pattern","A CSS technique"],correctAnswer:1,explanation:"Prop drilling makes intermediate components tightly coupled to unrelated data. Context, Redux, or Zustand solve this."},
  {lessonId:33,sortOrder:3,difficulty:"Medium",question:"What triggers a re-render when using useContext?",options:["Any parent re-render","When the context value changes — every component consuming the context re-renders","Only on mount","Manual triggers"],correctAnswer:1,explanation:"All consumers of a context re-render when the value changes. Split contexts by update frequency to minimize unnecessary re-renders."},
  {lessonId:33,sortOrder:4,difficulty:"Medium",question:"What is Redux Toolkit's createSlice()?",options:["Splits the store","Generates action creators and reducers from a single object with reducers, actions, and initial state","A middleware","A code splitting tool"],correctAnswer:1,explanation:"createSlice generates: action creators (slice.actions), a reducer (slice.reducer), and optionally extraReducers for async thunks."},
  {lessonId:33,sortOrder:5,difficulty:"Medium",question:"What is Zustand compared to Redux?",options:["A larger library","A minimal state management library with less boilerplate — no actions/reducers required, just a store with set()","A styling library","A form library"],correctAnswer:1,explanation:"Zustand: const useStore = create(set => ({count:0, inc:()=>set(s=>({count:s.count+1}))})) — much less ceremony than Redux."},
  {lessonId:33,sortOrder:6,difficulty:"Medium",question:"What is the difference between local state and global state?",options:["No practical difference","Local: component-scoped via useState. Global: shared across many components via Context, Redux, Zustand, etc.","Local is deprecated","Global state is always persisted"],correctAnswer:1,explanation:"Colocate state as close as possible. Lift only when needed. Not everything belongs in global state."},
  {lessonId:33,sortOrder:7,difficulty:"Hard",question:"What is the Flux pattern?",options:["A CSS framework","Unidirectional data flow: Action -> Dispatcher -> Store -> View. Actions are the only way to update store.","A build tool","A routing pattern"],correctAnswer:1,explanation:"Flux ensures predictable state updates. Redux is an implementation of Flux's unidirectional data flow idea."},
  {lessonId:33,sortOrder:8,difficulty:"Hard",question:"What is React Query (TanStack Query) used for?",options:["React component styling","Server state management: fetching, caching, synchronizing, and updating server data in React apps","Routing","Testing"],correctAnswer:1,explanation:"React Query handles: loading/error states, caching, background refetch, optimistic updates — all for async server data."},
  {lessonId:33,sortOrder:9,difficulty:"Hard",question:"What is the difference between server state and client state?",options:["No difference","Server state: asynchronous, lives on server, can be stale. Client state: synchronous, UI-only (theme, modal open).","Client state is persisted","Server state never changes"],correctAnswer:1,explanation:"Server state needs: caching, synchronization, loading/error handling. Tools: React Query, SWR. Client state: useState, Zustand."},
  {lessonId:33,sortOrder:10,difficulty:"Hard",question:"What is atomic state management (Jotai/Recoil)?",options:["A CSS methodology","State is split into small atoms; components subscribe only to atoms they use, minimizing re-renders","A single global object","A Redux alternative with actions"],correctAnswer:1,explanation:"Atoms are minimal state units. Components re-render only when their specific atoms change. More granular than Context."},

  // Lesson 34 - React Routing
  {lessonId:34,sortOrder:1,difficulty:"Easy",question:"What is client-side routing?",options:["Server renders each page","JavaScript intercepts navigation and renders new content without full page reload — URL changes without HTTP request","Browser history API","CSS transitions"],correctAnswer:1,explanation:"SPA client routing updates URL via History API and renders components without server round-trip. Faster but requires JS."},
  {lessonId:34,sortOrder:2,difficulty:"Easy",question:"What does the <Link> component do in React Router?",options:["Creates a hyperlink to external site","Renders an <a> tag that uses client-side navigation instead of full page reload","Creates a button","A form link"],correctAnswer:1,explanation:"<Link to='/about'> prevents default browser navigation and uses React Router's client-side routing instead."},
  {lessonId:34,sortOrder:3,difficulty:"Medium",question:"What is a dynamic route segment?",options:["A route that changes","A route parameter like /users/:id where :id can be any value","An animated route","A protected route"],correctAnswer:1,explanation:"/users/:id matches /users/1, /users/abc, etc. Access the param with useParams() hook."},
  {lessonId:34,sortOrder:4,difficulty:"Medium",question:"What is the useNavigate hook?",options:["Gets current URL","Returns a navigate function to programmatically change routes — used after form submission, login, etc.","Creates a link","Gets URL params"],correctAnswer:1,explanation:"const navigate = useNavigate(); navigate('/dashboard') or navigate(-1) for back. Used for programmatic navigation."},
  {lessonId:34,sortOrder:5,difficulty:"Medium",question:"What is a nested route?",options:["A route inside CSS","A child route rendered inside a parent route's Outlet component","A route with parameters","A protected route"],correctAnswer:1,explanation:"Parent route renders <Outlet/> where child routes appear. /users renders User layout, /users/:id renders UserDetail inside it."},
  {lessonId:34,sortOrder:6,difficulty:"Medium",question:"What is a loader in React Router v6?",options:["A loading spinner","A function that fetches data before a route renders — data available via useLoaderData()","An async route","A middleware"],correctAnswer:1,explanation:"Route loaders run before the component renders, providing data synchronously to the component via useLoaderData()."},
  {lessonId:34,sortOrder:7,difficulty:"Hard",question:"What is the difference between hash routing and history routing?",options:["No difference","Hash: #/path (works without server config). History: /path (requires server to return app for all paths)","Hash is deprecated","History is less secure"],correctAnswer:1,explanation:"Hash routes use the URL fragment. History routes use the full path but require server-side catch-all routing (return index.html for all paths)."},
  {lessonId:34,sortOrder:8,difficulty:"Hard",question:"What is route-based code splitting?",options:["Splitting code by file","Loading a route's JavaScript bundle only when the user navigates to that route — reduces initial bundle size","A routing pattern","Server rendering"],correctAnswer:1,explanation:"const About = lazy(() => import('./About')). Only loads About's bundle when /about is visited. Wrapped in <Suspense fallback=...>"},
  {lessonId:34,sortOrder:9,difficulty:"Hard",question:"How do you implement a protected route?",options:["CSS visibility","A wrapper component that checks authentication and redirects to login if not authenticated","A server route","A private CSS class"],correctAnswer:1,explanation:"function ProtectedRoute({children}){ return isAuth ? children : <Navigate to='/login'/> } Wrap protected routes with this."},
  {lessonId:34,sortOrder:10,difficulty:"Hard",question:"What is scroll restoration in SPAs?",options:["CSS overflow","Saving and restoring scroll position when navigating between routes — lost by default in client-side routing","A CSS animation","A browser feature"],correctAnswer:1,explanation:"Browser naturally restores scroll on back/forward for full page loads. SPAs need to manually handle this with useEffect on route change."},

  // Lesson 35 - React Performance
  {lessonId:35,sortOrder:1,difficulty:"Easy",question:"What does React.memo do?",options:["Memoizes state","Higher-order component that prevents re-render if props haven't changed using shallow comparison","Caches API calls","Memoizes the DOM"],correctAnswer:1,explanation:"React.memo(Component) wraps a component. If the parent re-renders but props haven't changed, the component is skipped."},
  {lessonId:35,sortOrder:2,difficulty:"Medium",question:"What is the danger of missing deps in useEffect?",options:["No danger","Stale closures — the effect uses outdated values. ESLint exhaustive-deps rule catches this.","Performance issue","Memory leak"],correctAnswer:1,explanation:"Missing deps means the effect doesn't re-run when those values change, leading to stale data. Always follow eslint-plugin-react-hooks."},
  {lessonId:35,sortOrder:3,difficulty:"Medium",question:"When should you use useMemo?",options:["Always","When a computation is expensive and its inputs (deps) don't change every render","For all state","For async operations"],correctAnswer:1,explanation:"useMemo is for referential stability of expensive computations. Don't overuse it — the overhead may exceed the benefit for cheap operations."},
  {lessonId:35,sortOrder:4,difficulty:"Medium",question:"What is concurrent rendering?",options:["Parallel component rendering","React 18's ability to interrupt, pause, and prioritize rendering work — urgent updates (typing) don't block less urgent ones","Multi-threaded rendering","SSR"],correctAnswer:1,explanation:"Concurrent mode allows React to work on multiple state updates simultaneously, keeping UI responsive during heavy rendering work."},
  {lessonId:35,sortOrder:5,difficulty:"Medium",question:"What does the Profiler component do?",options:["Profiles CSS","Measures how often components render and the cost of each render — for identifying performance bottlenecks","Profiles network","Profiles memory"],correctAnswer:1,explanation:"<Profiler id='Nav' onRender={callback}> measures render times. Use with React DevTools Profiler for visual analysis."},
  {lessonId:35,sortOrder:6,difficulty:"Hard",question:"What is React 18's useTransition?",options:["Animates components","Marks a state update as non-urgent — React can interrupt it for more urgent updates like user input","Manages CSS transitions","Handles form transitions"],correctAnswer:1,explanation:"const [isPending, startTransition] = useTransition(); startTransition(() => setTab(newTab)) — tab change won't block typing."},
  {lessonId:35,sortOrder:7,difficulty:"Hard",question:"What is automatic batching in React 18?",options:["CSS batch operations","Multiple setState calls in any async context are batched into a single re-render — previously only in event handlers","Build batching","Network request batching"],correctAnswer:1,explanation:"React 17 only batched in event handlers. React 18 batches all updates (setTimeout, Promises, native events) automatically."},
  {lessonId:35,sortOrder:8,difficulty:"Hard",question:"What is virtualization in React lists?",options:["Virtual DOM","Rendering only visible items in a long list — unmounted items are replaced with placeholder spacers","CSS virtualization","Memory virtualization"],correctAnswer:1,explanation:"react-window and react-virtual render only visible rows. A list of 10,000 items renders ~20 DOM nodes at a time."},
  {lessonId:35,sortOrder:9,difficulty:"Hard",question:"What is the reconciliation bailout?",options:["Error handling","React skipping a subtree's reconciliation if the component returns the same element reference","State reset","Route bailout"],correctAnswer:1,explanation:"If a component returns the exact same element reference (via useMemo), React skips reconciling that subtree entirely."},
  {lessonId:35,sortOrder:10,difficulty:"Hard",question:"What is hydration in React?",options:["Adding water to code","Attaching React event listeners and making SSR-rendered HTML interactive — React 'takes over' server HTML","Fetching data","Loading assets"],correctAnswer:1,explanation:"Hydration: React reads server-rendered HTML, reconciles with virtual DOM, and attaches event listeners. Faster than client-side rendering from scratch."},

  // Lesson 36 - React Patterns
  {lessonId:36,sortOrder:1,difficulty:"Easy",question:"What is the compound component pattern?",options:["Nested CSS","Components that share implicit state via Context, designed to work together — like <Select> and <Option>","A HOC pattern","A routing pattern"],correctAnswer:1,explanation:"Example: <Accordion><Item title='Q1'>Answer</Item></Accordion> — Item accesses Accordion's state via Context."},
  {lessonId:36,sortOrder:2,difficulty:"Medium",question:"What is a Higher-Order Component (HOC)?",options:["A component with many children","A function that takes a component and returns a new enhanced component with additional behavior","A pure component","A context consumer"],correctAnswer:1,explanation:"withAuth(Component) returns AuthenticatedComponent. HOCs add cross-cutting concerns (auth, logging) without modifying the component."},
  {lessonId:36,sortOrder:3,difficulty:"Medium",question:"What is the render props pattern?",options:["Rendering arrays","A technique where a component receives a function as a prop that it calls to determine what to render","CSS render","A routing pattern"],correctAnswer:1,explanation:"<DataProvider render={data => <Display data={data}/>}/> or children-as-function. Replaced largely by hooks."},
  {lessonId:36,sortOrder:4,difficulty:"Medium",question:"What is the headless component pattern?",options:["Components without headers","Components that manage behavior/state but render nothing themselves — consumers provide their own UI","A CSS module","An invisible component"],correctAnswer:1,explanation:"Headless: provides logic (open/close, keyboard nav) without styles. Examples: Headless UI, Radix UI, React Aria."},
  {lessonId:36,sortOrder:5,difficulty:"Medium",question:"What is prop spreading and when is it risky?",options:["CSS spreading","Passing {...props} to a DOM element — risky when unknown props cause DOM warnings or security issues","A context pattern","A performance pattern"],correctAnswer:1,explanation:"<div {...props}> with unknown props causes React DOM warnings. Destructure known props and spread the rest selectively."},
  {lessonId:36,sortOrder:6,difficulty:"Hard",question:"What is the Container/Presenter pattern?",options:["Docker containers","Separating data-fetching/logic (Container) from rendering (Presenter/Dumb) components","A CSS pattern","A routing pattern"],correctAnswer:1,explanation:"Less prevalent with hooks, but still useful. Containers fetch data; Presenters are pure, testable UI components."},
  {lessonId:36,sortOrder:7,difficulty:"Hard",question:"What is the Provider pattern?",options:["Data providing","Using Context to inject dependencies into a component tree — like a dependency injection container for React","A HOC alternative","A state pattern"],correctAnswer:1,explanation:"<ThemeProvider> wraps the tree. Child components access theme via useContext(ThemeContext). Enables theming, DI, testing."},
  {lessonId:36,sortOrder:8,difficulty:"Hard",question:"What is the slots pattern in React?",options:["Time slots","Composing component layouts by accepting JSX as props (header, footer, sidebar) instead of predefined structure","A named render prop","A CSS grid slot"],correctAnswer:1,explanation:"function Card({header, body, footer}) — the Card layout is fixed but content slots accept any JSX from the consumer."},
  {lessonId:36,sortOrder:9,difficulty:"Hard",question:"What is the controlled props pattern?",options:["CSS control","A component that can work as either controlled (parent owns state) or uncontrolled (internal state) based on props","A HOC pattern","A form pattern"],correctAnswer:1,explanation:"If value prop is provided, use it (controlled). Otherwise use internal state (uncontrolled). Downshift implements this as 'state reducers'."},
  {lessonId:36,sortOrder:10,difficulty:"Hard",question:"What is code co-location in React?",options:["Merging files","Putting code (state, effects, tests) as close as possible to where it's used rather than centralizing everything","A file structure","A build optimization"],correctAnswer:1,explanation:"Co-location: move state down to the component that needs it. Only lift state when multiple components need it."},

  // Lesson 37 - Next.js
  {lessonId:37,sortOrder:1,difficulty:"Easy",question:"What is the App Router in Next.js 14?",options:["A server router","The new default routing system using the app/ directory with React Server Components, layouts, and streaming","An API router","A navigation library"],correctAnswer:1,explanation:"App Router (app/) replaces Pages Router (pages/). Each folder is a route. page.tsx renders the UI. layout.tsx wraps routes."},
  {lessonId:37,sortOrder:2,difficulty:"Easy",question:"What is a React Server Component (RSC)?",options:["A component that runs only on server with no client-side JS, cannot use hooks or browser APIs","A component with SSR","A server-side cache","An API component"],correctAnswer:0,explanation:"RSCs run on server. Zero client JS. Can be async, access DB directly. Cannot use useState, useEffect, or browser APIs."},
  {lessonId:37,sortOrder:3,difficulty:"Medium",question:"What does 'use client' do in Next.js?",options:["Marks a server component","Creates a boundary — the component and all its imports become client components with full React capabilities","Enables client caching","Disables SSR"],correctAnswer:1,explanation:"'use client' at top of file makes it a Client Component. Needed for: useState, useEffect, event handlers, browser APIs."},
  {lessonId:37,sortOrder:4,difficulty:"Medium",question:"What is static vs dynamic rendering in Next.js?",options:["No difference","Static: rendered at build time, cached (fastest). Dynamic: rendered per request (fresh data but slower).","Static is deprecated","Dynamic is always used"],correctAnswer:1,explanation:"Static rendering uses cached HTML. Dynamic rendering happens per request. Next.js automatically chooses based on data fetching patterns."},
  {lessonId:37,sortOrder:5,difficulty:"Medium",question:"What is a Route Handler in Next.js app router?",options:["A React component","A file (route.ts) that creates API endpoints — replaces pages/api directory in the pages router","A layout file","A server action"],correctAnswer:1,explanation:"app/api/users/route.ts with export async function GET() creates a GET /api/users endpoint."},
  {lessonId:37,sortOrder:6,difficulty:"Medium",question:"What are Server Actions?",options:["Server events","Async functions marked with 'use server' that run on the server and can be called from client components — replaces API routes for mutations","Server-side hooks","Build actions"],correctAnswer:1,explanation:"Server Actions: async function with 'use server' in a form action or called from event handler. Handle mutations without API routes."},
  {lessonId:37,sortOrder:7,difficulty:"Hard",question:"What is Incremental Static Regeneration (ISR)?",options:["Progressive CSS","Regenerating static pages in the background at specified intervals — stale-while-revalidate for pages","A caching layer","A build optimization"],correctAnswer:1,explanation:"ISR: serve stale static page while regenerating in background. next: {revalidate: 60} — page revalidates every 60 seconds."},
  {lessonId:37,sortOrder:8,difficulty:"Hard",question:"What is the difference between generateStaticParams and getStaticPaths?",options:["No difference","generateStaticParams is the App Router equivalent of getStaticPaths for pre-generating dynamic route pages at build time","generateStaticParams is deprecated","getStaticPaths works in app/"],correctAnswer:1,explanation:"export function generateStaticParams() in app/ replaces getStaticPaths in pages/. Returns array of param objects for pre-rendering."},
  {lessonId:37,sortOrder:9,difficulty:"Hard",question:"What is streaming in Next.js?",options:["Video streaming","Sending HTML in chunks as server components resolve — users see content progressively instead of waiting for all data","CSS streaming","Asset streaming"],correctAnswer:1,explanation:"Streaming with <Suspense> lets React send HTML chunks as each component's data resolves. No blank screen waiting for slowest data."},
  {lessonId:37,sortOrder:10,difficulty:"Hard",question:"What is the Next.js Image component optimization?",options:["CSS image styles","Automatic: WebP/AVIF conversion, lazy loading, size optimization, CLS prevention via reserved space","A CSS utility","An image library"],correctAnswer:1,explanation:"next/image: automatically serves modern formats, lazy loads, prevents layout shift with reserved space, and generates srcsets."},

  // Lesson 38 - Node.js Fundamentals
  {lessonId:38,sortOrder:1,difficulty:"Easy",question:"What makes Node.js non-blocking?",options:["Multiple threads","Event loop + async I/O — I/O operations are offloaded to the OS and callbacks run when complete","Hardware acceleration","Worker threads only"],correctAnswer:1,explanation:"Node.js is single-threaded but non-blocking. libuv handles async I/O via the OS. The event loop processes callbacks when I/O completes."},
  {lessonId:38,sortOrder:2,difficulty:"Easy",question:"What is the difference between require() and import in Node.js?",options:["No difference","require() is CommonJS (synchronous, dynamic). import is ESM (static, async-capable). Node supports both with configuration.","import is not supported","require() is deprecated"],correctAnswer:1,explanation:"CJS: require() at runtime, module.exports. ESM: import at parse time, export. Use .mjs or type:module in package.json for ESM."},
  {lessonId:38,sortOrder:3,difficulty:"Medium",question:"What is the process object in Node.js?",options:["A CPU process","A global object providing info about the current Node.js process: argv, env, exit(), stdout, stdin","A child process","A worker process"],correctAnswer:1,explanation:"process.env.NODE_ENV reads environment. process.argv gets CLI args. process.exit() terminates. process.stdout writes to stdout."},
  {lessonId:38,sortOrder:4,difficulty:"Medium",question:"What are Node.js streams?",options:["Network requests","Objects that let you read or write data in chunks rather than loading everything into memory — ReadStream, WriteStream, Transform","A file type","An async pattern"],correctAnswer:1,explanation:"Streams enable processing large files without loading them entirely. Pipe: fs.createReadStream().pipe(transform).pipe(res)"},
  {lessonId:38,sortOrder:5,difficulty:"Medium",question:"What is the purpose of the cluster module?",options:["CSS clustering","Creating child processes that share a server port — enables utilizing multiple CPU cores","Database clustering","Code organization"],correctAnswer:1,explanation:"cluster.fork() creates worker processes. Master process accepts connections and distributes them. Overcomes Node's single-thread limitation."},
  {lessonId:38,sortOrder:6,difficulty:"Medium",question:"What is the EventEmitter in Node.js?",options:["A DOM event system","The core pub/sub pattern: emit events, subscribe with .on(). Base class for streams, http, and many core modules.","An async queue","A worker pool"],correctAnswer:1,explanation:"EventEmitter.on('data', fn) and .emit('data', payload). Most Node.js core modules extend EventEmitter."},
  {lessonId:38,sortOrder:7,difficulty:"Hard",question:"What is libuv?",options:["A build tool","The C library that provides Node.js with its event loop, async I/O, and thread pool for OS operations","A JavaScript engine","A module loader"],correctAnswer:1,explanation:"libuv provides: the event loop, async DNS, file I/O thread pool (4 threads default), OS async I/O on each platform."},
  {lessonId:38,sortOrder:8,difficulty:"Hard",question:"What is the difference between setImmediate and setTimeout(fn, 0)?",options:["No difference","setImmediate fires in the check phase (after I/O). setTimeout(0) fires in timers phase. Order depends on context.","setImmediate is synchronous","setTimeout(0) is immediate"],correctAnswer:1,explanation:"In the main module, order is non-deterministic. Inside I/O callbacks, setImmediate always fires before setTimeout(0)."},
  {lessonId:38,sortOrder:9,difficulty:"Hard",question:"What is backpressure in Node.js streams?",options:["Memory pressure","When a writable stream cannot consume data as fast as it's being produced — readable should pause until writable drains","CPU pressure","Network pressure"],correctAnswer:1,explanation:"pipe() handles backpressure automatically. Manual streaming: check write() return — false means pause, drain event means resume."},
  {lessonId:38,sortOrder:10,difficulty:"Hard",question:"What is Worker Threads in Node.js?",options:["Browser Web Workers","True threads for CPU-intensive work — share memory via SharedArrayBuffer, communicate via postMessage","Cluster workers","Child processes"],correctAnswer:1,explanation:"Worker Threads are actual threads (unlike cluster which uses processes). Share memory with SharedArrayBuffer. Good for CPU-bound tasks."},

  // Lesson 39 - Node.js File System and HTTP
  {lessonId:39,sortOrder:1,difficulty:"Easy",question:"What is the difference between fs.readFile and fs.createReadStream?",options:["No difference","readFile loads entire file into memory. createReadStream reads in chunks — essential for large files.","readStream is synchronous","readFile is deprecated"],correctAnswer:1,explanation:"readFile buffers entire file — bad for large files. ReadStream pipes chunks, keeping memory constant regardless of file size."},
  {lessonId:39,sortOrder:2,difficulty:"Medium",question:"What does http.createServer() return?",options:["A function","An HTTP server that emits 'request' events. Pass (req, res) callback or attach listener.","A middleware","A router"],correctAnswer:1,explanation:"http.createServer((req,res)=>{res.end('Hello')}).listen(3000) creates a basic HTTP server."},
  {lessonId:39,sortOrder:3,difficulty:"Medium",question:"What is the path module used for?",options:["URL paths","Cross-platform file path manipulation: join, resolve, dirname, basename, extname","Routing paths","Network paths"],correctAnswer:1,explanation:"path.join(__dirname, 'public', 'index.html') creates platform-correct paths. Use instead of string concatenation."},
  {lessonId:39,sortOrder:4,difficulty:"Medium",question:"What is fs.promises (or fsPromises)?",options:["A future feature","The promise-based version of fs — same functions as callbacks but return Promises","A deprecated module","A stream module"],correctAnswer:1,explanation:"import { readFile, writeFile } from 'fs/promises' — modern async file operations without callbacks."},
  {lessonId:39,sortOrder:5,difficulty:"Hard",question:"What is piping in Node.js streams?",options:["A UNIX concept only","Connecting a ReadStream to a WriteStream so data flows automatically with backpressure handling","A network protocol","A child process connection"],correctAnswer:1,explanation:"readable.pipe(writable) automatically manages the data flow and backpressure. Multiple pipes chain: read.pipe(transform).pipe(write)."},
  {lessonId:39,sortOrder:6,difficulty:"Hard",question:"What does the os module provide?",options:["Operating system simulation","System information: cpu count, total memory, free memory, hostname, platform","File operations","Process management"],correctAnswer:1,explanation:"os.cpus().length for core count. os.totalmem()/os.freemem() for memory. Used in cluster workers and health endpoints."},
  {lessonId:39,sortOrder:7,difficulty:"Medium",question:"What is a buffer in Node.js?",options:["A queue","A fixed-size region of memory for handling binary data — TCP streams, file I/O, crypto","A JavaScript array","An async buffer"],correctAnswer:1,explanation:"Buffer.from('hello', 'utf8') or Buffer.alloc(size). Used when working with binary protocols, images, encryption."},
  {lessonId:39,sortOrder:8,difficulty:"Hard",question:"What is the difference between synchronous and asynchronous file operations?",options:["No difference","Sync (readFileSync) blocks the event loop. Async (readFile/promises) lets other work continue while waiting.","Async is synchronous","Sync is deprecated"],correctAnswer:1,explanation:"Never use sync file ops in HTTP servers — blocks all requests while reading. Sync is only appropriate for startup config loading."},
  {lessonId:39,sortOrder:9,difficulty:"Hard",question:"What is child_process.spawn vs exec?",options:["No difference","spawn streams output incrementally. exec buffers all output and returns it in callback — use spawn for large output","exec is async only","spawn is deprecated"],correctAnswer:1,explanation:"spawn: data streamed via stdout. exec: entire stdout buffered (default 200KB limit). Use spawn for long-running commands."},
  {lessonId:39,sortOrder:10,difficulty:"Medium",question:"What is the url module and URL class?",options:["A routing module","WHATWG URL API for parsing and constructing URLs: new URL(href), url.searchParams.get('key')","A fetch module","A network module"],correctAnswer:1,explanation:"const url = new URL('https://example.com?page=1'); url.searchParams.get('page') === '1'. Cross-platform URL parsing."},

  // Lesson 40 - npm and Package Management
  {lessonId:40,sortOrder:1,difficulty:"Easy",question:"What is the difference between dependencies and devDependencies?",options:["No practical difference","dependencies are needed in production. devDependencies are only needed during development (build tools, testing, linting).","devDependencies are smaller","dependencies are optional"],correctAnswer:1,explanation:"npm install --production skips devDependencies. Keeps production images smaller by excluding build tools."},
  {lessonId:40,sortOrder:2,difficulty:"Easy",question:"What does ^ mean in package.json version ranges?",options:["Exact version","Compatible updates allowed — ^1.2.3 allows 1.x.x but not 2.0.0 (major version locked)","Any version","Latest version"],correctAnswer:1,explanation:"^1.2.3 = >=1.2.3 <2.0.0. ~ means ~1.2.3 = >=1.2.3 <1.3.0 (patch only). No prefix = exact match."},
  {lessonId:40,sortOrder:3,difficulty:"Medium",question:"What is package-lock.json?",options:["An executable file","A lockfile that records the exact version of every installed package and its dependencies","A configuration file","A build output"],correctAnswer:1,explanation:"Lockfile ensures reproducible installs across machines and CI. Always commit package-lock.json. npm ci installs from lockfile exactly."},
  {lessonId:40,sortOrder:4,difficulty:"Medium",question:"What does npm audit do?",options:["Audits code style","Checks installed packages against a vulnerability database and reports security issues","Runs tests","Checks performance"],correctAnswer:1,explanation:"npm audit lists known vulnerabilities. npm audit fix upgrades vulnerable packages when safe. CI pipelines should run npm audit."},
  {lessonId:40,sortOrder:5,difficulty:"Medium",question:"What is a monorepo and what tools support it?",options:["A single module","A repository containing multiple packages/apps — tools: npm workspaces, pnpm, Turborepo, Nx","A massive repository","A single-file repository"],correctAnswer:1,explanation:"Monorepos share dependencies and tooling. npm workspaces link packages. Turborepo caches build artifacts across packages."},
  {lessonId:40,sortOrder:6,difficulty:"Hard",question:"What is the node_modules resolution algorithm?",options:["Linear search","Walk up directories looking for node_modules until the module is found or the root is reached","Package.json lookup","Environment variable"],correctAnswer:1,explanation:"require('lodash'): look in ./node_modules, ../node_modules, ../../node_modules... up to root. Enables package deduplication."},
  {lessonId:40,sortOrder:7,difficulty:"Hard",question:"What is pnpm's advantage over npm?",options:["More packages available","Content-addressable storage: packages installed once, hard-linked into projects. Saves disk space.","Faster registry","Better security"],correctAnswer:1,explanation:"pnpm stores each package version once globally and hard-links into node_modules. Much faster and dramatically less disk space."},
  {lessonId:40,sortOrder:8,difficulty:"Hard",question:"What is the exports field in package.json?",options:["A list of exports","Defines the public API of a package — controls which files can be imported and provides conditions (require, import, browser)","An import map","A build config"],correctAnswer:1,explanation:"exports: {'.':{import:'./esm/index.js', require:'./cjs/index.js'}} — dual CJS/ESM package with controlled exports."},
  {lessonId:40,sortOrder:9,difficulty:"Hard",question:"What does npm link do?",options:["Links to a URL","Symlinks a local package into another local project's node_modules — enables testing local packages before publishing","Links npm accounts","Creates shortcuts"],correctAnswer:1,explanation:"cd my-lib && npm link then cd my-app && npm link my-lib — app uses local symlinked version for development."},
  {lessonId:40,sortOrder:10,difficulty:"Medium",question:"What is a prepublish vs prepare script?",options:["No difference","prepare runs on install (npm install in the package) and before publish. prepublishOnly runs only before publish.","prepublish is deprecated","prepare is optional"],correctAnswer:1,explanation:"prepare: build step that runs for both npm install of the package and npm publish. prepublishOnly: only before npm publish."}
];

async function main() {
  let qi = 0, qs = 0;
  for (const q of quizQuestions) {
    const exists = await p.quizQuestion.findFirst({ where: { lessonId: q.lessonId, question: q.question } });
    if (!exists) { await p.quizQuestion.create({ data: q }); qi++; } else qs++;
  }
  console.log(`Quiz: ${qi} inserted, ${qs} skipped.`);
}

main().catch(console.error).finally(() => p.$disconnect());
